-- Create DP01_Stage staging table for high-throughput imports
IF OBJECT_ID('dbo.DP01_Stage', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DP01_Stage (
        NGAY_DL              datetime2      NOT NULL,
        MA_CN                nvarchar(100)  NULL,
        TAI_KHOAN_HACH_TOAN  nvarchar(100)  NULL,
        MA_KH                nvarchar(100)  NULL,
        TEN_KH               nvarchar(200)  NULL,
        DP_TYPE_NAME         nvarchar(200)  NULL,
        CCY                  nvarchar(10)   NULL,
        CURRENT_BALANCE      decimal(18,2)  NULL,
        RATE                 decimal(18,6)  NULL,
        SO_TAI_KHOAN         nvarchar(100)  NULL,
        OPENING_DATE         datetime2      NULL,
        MATURITY_DATE        datetime2      NULL,
        ADDRESS              nvarchar(500)  NULL,
        NOTENO               nvarchar(100)  NULL,
        MONTH_TERM           nvarchar(50)   NULL,
        TERM_DP_NAME         nvarchar(200)  NULL,
        TIME_DP_NAME         nvarchar(200)  NULL,
        MA_PGD               nvarchar(50)   NULL,
        TEN_PGD              nvarchar(200)  NULL,
        DP_TYPE_CODE         nvarchar(50)   NULL,
        RENEW_DATE           datetime2      NULL,
        CUST_TYPE            nvarchar(50)   NULL,
        CUST_TYPE_NAME       nvarchar(200)  NULL,
        CUST_TYPE_DETAIL     nvarchar(200)  NULL,
        CUST_DETAIL_NAME     nvarchar(200)  NULL,
        PREVIOUS_DP_CAP_DATE datetime2      NULL,
        NEXT_DP_CAP_DATE     datetime2      NULL,
        ID_NUMBER            nvarchar(50)   NULL,
        ISSUED_BY            nvarchar(200)  NULL,
        ISSUE_DATE           datetime2      NULL,
        SEX_TYPE             nvarchar(10)   NULL,
        BIRTH_DATE           datetime2      NULL,
        TELEPHONE            nvarchar(50)   NULL,
        ACRUAL_AMOUNT        decimal(18,2)  NULL,
        ACRUAL_AMOUNT_END    decimal(18,2)  NULL,
        ACCOUNT_STATUS       nvarchar(50)   NULL,
        DRAMT                decimal(18,2)  NULL,
        CRAMT                decimal(18,2)  NULL,
        EMPLOYEE_NUMBER      nvarchar(50)   NULL,
        EMPLOYEE_NAME        nvarchar(200)  NULL,
        SPECIAL_RATE         decimal(18,6)  NULL,
        AUTO_RENEWAL         nvarchar(20)   NULL,
        CLOSE_DATE           datetime2      NULL,
        LOCAL_PROVIN_NAME    nvarchar(200)  NULL,
        LOCAL_DISTRICT_NAME  nvarchar(200)  NULL,
        LOCAL_WARD_NAME      nvarchar(200)  NULL,
        TERM_DP_TYPE         nvarchar(50)   NULL,
        TIME_DP_TYPE         nvarchar(50)   NULL,
        STATES_CODE          nvarchar(50)   NULL,
        ZIP_CODE             nvarchar(20)   NULL,
        COUNTRY_CODE         nvarchar(10)   NULL,
        TAX_CODE_LOCATION    nvarchar(100)  NULL,
        MA_CAN_BO_PT         nvarchar(50)   NULL,
        TEN_CAN_BO_PT        nvarchar(200)  NULL,
        PHONG_CAN_BO_PT      nvarchar(200)  NULL,
        NGUOI_NUOC_NGOAI     nvarchar(10)   NULL,
        QUOC_TICH            nvarchar(100)  NULL,
        MA_CAN_BO_AGRIBANK   nvarchar(50)   NULL,
        NGUOI_GIOI_THIEU     nvarchar(200)  NULL,
        TEN_NGUOI_GIOI_THIEU nvarchar(200)  NULL,
        CONTRACT_COUTS_DAY   nvarchar(50)   NULL,
        SO_KY_AD_LSDB        nvarchar(50)   NULL,
        UNTBUSCD             nvarchar(50)   NULL,
        TYGIA                decimal(18,6)  NULL,
        FILE_NAME            nvarchar(500)  NULL,
        DataSource           nvarchar(100)  NULL,
        ImportDateTime       datetime2      NULL,
        CreatedAt            datetime2      NULL,
        UpdatedAt            datetime2      NULL,
        CreatedBy            nvarchar(100)  NULL,
        UpdatedBy            nvarchar(100)  NULL
    );
END
GO

-- Optional index to speed up replace-by-date operations
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_DP01_Stage_NGAY_DL' AND object_id = OBJECT_ID('dbo.DP01_Stage'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_DP01_Stage_NGAY_DL ON dbo.DP01_Stage(NGAY_DL);
END
GO
