-- Script để rebuild DP01 với NGAY_DL là cột đầu tiên (vật lý)
-- Tác giả: GitHub Copilot
-- Ngày tạo: 08/08/2025

/*
HƯỚNG DẪN TỐI ƯU BỐ TRÍ CỘT TRONG SQL SERVER

I. NGUYÊN TẮC TỐI ƯU BỐ TRÍ CỘT:
----------------------------
1. Cột được truy vấn thường xuyên đặt đầu tiên để tận dụng ROW/PAGE compression
2. Cột có kích thước cố định (INT, DATE) đặt trước cột có kích thước thay đổi (VARCHAR, NVARCHAR)
3. Cột có độ dài nhỏ đặt trước cột có độ dài lớn
4. Cột NULL đặt sau cùng do chỉ tốn 1 bit trong bitmask

II. THỨ TỰ CỘT TỐI ƯU CHO DP01:
----------------------------
1. Cột phân đoạn dữ liệu (nhất là cột được dùng trong INDEX)
   - NGAY_DL (date): Cột thời gian, thường dùng để phân mảnh/lọc dữ liệu
   - MA_CN (varchar): Mã chi nhánh
   - MA_DON_VI (varchar): Mã đơn vị
   - MA_KHOAN (varchar): Mã khoản mục

2. Cột số liệu tính toán chính
   - SO_DU_DAU_KY, SO_PHAT_SINH_NO, SO_PHAT_SINH_CO, SO_DU_CUOI_KY

3. Cột metadata và ít được truy vấn
   - Các cột thông tin bổ sung
   - Cột có thể NULL đặt sau cùng
*/

-- Tạo bảng mới với cấu trúc cột đã sắp xếp lại
CREATE TABLE dbo.DP01_New (
    -- Cột phân mảnh dữ liệu (thường dùng cho filter)
    NGAY_DL DATETIME2 NOT NULL,
    MA_CN NVARCHAR(200) NULL,
    TAI_KHOAN_HACH_TOAN NVARCHAR(200) NULL,
    MA_KH NVARCHAR(200) NULL,

    -- Cột số liệu chính
    CURRENT_BALANCE DECIMAL(18,0) NULL,
    RATE DECIMAL(18,2) NULL,
    ACRUAL_AMOUNT DECIMAL(18,0) NULL,
    ACRUAL_AMOUNT_END DECIMAL(18,0) NULL,

    -- Các cột business khác (theo thứ tự CSV)
    TEN_KH NVARCHAR(200) NULL,
    DP_TYPE_NAME NVARCHAR(200) NULL,
    CCY NVARCHAR(200) NULL,
    SO_TAI_KHOAN NVARCHAR(200) NULL,
    OPENING_DATE DATETIME2 NULL,
    MATURITY_DATE DATETIME2 NULL,
    ADDRESS NVARCHAR(1000) NULL,
    NOTENO NVARCHAR(200) NULL,
    MONTH_TERM NVARCHAR(200) NULL,
    TERM_DP_NAME NVARCHAR(200) NULL,
    TIME_DP_NAME NVARCHAR(200) NULL,
    MA_PGD NVARCHAR(200) NULL,
    TEN_PGD NVARCHAR(200) NULL,
    DP_TYPE_CODE NVARCHAR(200) NULL,
    RENEW_DATE DATETIME2 NULL,
    CUST_TYPE NVARCHAR(200) NULL,
    CUST_TYPE_NAME NVARCHAR(200) NULL,
    CUST_TYPE_DETAIL NVARCHAR(200) NULL,
    CUST_DETAIL_NAME NVARCHAR(200) NULL,
    PREVIOUS_DP_CAP_DATE DATETIME2 NULL,
    NEXT_DP_CAP_DATE DATETIME2 NULL,
    ID_NUMBER NVARCHAR(200) NULL,
    ISSUED_BY NVARCHAR(200) NULL,
    ISSUE_DATE DATETIME2 NULL,
    SEX_TYPE NVARCHAR(200) NULL,
    BIRTH_DATE DATETIME2 NULL,
    TELEPHONE NVARCHAR(200) NULL,
    ACCOUNT_STATUS NVARCHAR(200) NULL,
    DRAMT DECIMAL(18,0) NULL,
    CRAMT DECIMAL(18,0) NULL,
    EMPLOYEE_NUMBER NVARCHAR(200) NULL,
    EMPLOYEE_NAME NVARCHAR(200) NULL,
    SPECIAL_RATE DECIMAL(18,2) NULL,
    AUTO_RENEWAL NVARCHAR(200) NULL,
    CLOSE_DATE DATETIME2 NULL,
    LOCAL_PROVIN_NAME NVARCHAR(200) NULL,
    LOCAL_DISTRICT_NAME NVARCHAR(200) NULL,
    LOCAL_WARD_NAME NVARCHAR(200) NULL,
    TERM_DP_TYPE NVARCHAR(200) NULL,
    TIME_DP_TYPE NVARCHAR(200) NULL,
    STATES_CODE NVARCHAR(200) NULL,
    ZIP_CODE NVARCHAR(200) NULL,
    COUNTRY_CODE NVARCHAR(200) NULL,
    TAX_CODE_LOCATION NVARCHAR(200) NULL,
    MA_CAN_BO_PT NVARCHAR(200) NULL,
    TEN_CAN_BO_PT NVARCHAR(200) NULL,
    PHONG_CAN_BO_PT NVARCHAR(200) NULL,
    NGUOI_NUOC_NGOAI NVARCHAR(200) NULL,
    QUOC_TICH NVARCHAR(200) NULL,
    MA_CAN_BO_AGRIBANK NVARCHAR(200) NULL,
    NGUOI_GIOI_THIEU NVARCHAR(200) NULL,
    TEN_NGUOI_GIOI_THIEU NVARCHAR(200) NULL,
    CONTRACT_COUTS_DAY NVARCHAR(200) NULL,
    SO_KY_AD_LSDB NVARCHAR(200) NULL,
    UNTBUSCD NVARCHAR(200) NULL,
    TYGIA DECIMAL(18,4) NULL,

    -- Các cột hệ thống (đặt sau cùng)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    DataSource NVARCHAR(200) NULL,
    ImportDateTime DATETIME2 NOT NULL DEFAULT GETDATE(),
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    CreatedBy NVARCHAR(200) NULL,
    UpdatedBy NVARCHAR(200) NULL,
    ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    ValidTo DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,

    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.DP01_New_History));-- Sao chép dữ liệu sang bảng mới với thứ tự cột đã thay đổi
INSERT INTO dbo.DP01_New (
    NGAY_DL, MA_CN, TAI_KHOAN_HACH_TOAN, MA_KH, CURRENT_BALANCE, RATE,
    ACRUAL_AMOUNT, ACRUAL_AMOUNT_END, TEN_KH, DP_TYPE_NAME, CCY,
    SO_TAI_KHOAN, OPENING_DATE, MATURITY_DATE, ADDRESS, NOTENO,
    MONTH_TERM, TERM_DP_NAME, TIME_DP_NAME, MA_PGD, TEN_PGD,
    DP_TYPE_CODE, RENEW_DATE, CUST_TYPE, CUST_TYPE_NAME,
    CUST_TYPE_DETAIL, CUST_DETAIL_NAME, PREVIOUS_DP_CAP_DATE,
    NEXT_DP_CAP_DATE, ID_NUMBER, ISSUED_BY, ISSUE_DATE, SEX_TYPE,
    BIRTH_DATE, TELEPHONE, ACCOUNT_STATUS, DRAMT, CRAMT,
    EMPLOYEE_NUMBER, EMPLOYEE_NAME, SPECIAL_RATE, AUTO_RENEWAL,
    CLOSE_DATE, LOCAL_PROVIN_NAME, LOCAL_DISTRICT_NAME,
    LOCAL_WARD_NAME, TERM_DP_TYPE, TIME_DP_TYPE, STATES_CODE,
    ZIP_CODE, COUNTRY_CODE, TAX_CODE_LOCATION, MA_CAN_BO_PT,
    TEN_CAN_BO_PT, PHONG_CAN_BO_PT, NGUOI_NUOC_NGOAI, QUOC_TICH,
    MA_CAN_BO_AGRIBANK, NGUOI_GIOI_THIEU, TEN_NGUOI_GIOI_THIEU,
    CONTRACT_COUTS_DAY, SO_KY_AD_LSDB, UNTBUSCD, TYGIA,
    DataSource, ImportDateTime, CreatedBy, UpdatedBy
)
SELECT
    NGAY_DL, MA_CN, TAI_KHOAN_HACH_TOAN, MA_KH, CURRENT_BALANCE, RATE,
    ACRUAL_AMOUNT, ACRUAL_AMOUNT_END, TEN_KH, DP_TYPE_NAME, CCY,
    SO_TAI_KHOAN, OPENING_DATE, MATURITY_DATE, ADDRESS, NOTENO,
    MONTH_TERM, TERM_DP_NAME, TIME_DP_NAME, MA_PGD, TEN_PGD,
    DP_TYPE_CODE, RENEW_DATE, CUST_TYPE, CUST_TYPE_NAME,
    CUST_TYPE_DETAIL, CUST_DETAIL_NAME, PREVIOUS_DP_CAP_DATE,
    NEXT_DP_CAP_DATE, ID_NUMBER, ISSUED_BY, ISSUE_DATE, SEX_TYPE,
    BIRTH_DATE, TELEPHONE, ACCOUNT_STATUS, DRAMT, CRAMT,
    EMPLOYEE_NUMBER, EMPLOYEE_NAME, SPECIAL_RATE, AUTO_RENEWAL,
    CLOSE_DATE, LOCAL_PROVIN_NAME, LOCAL_DISTRICT_NAME,
    LOCAL_WARD_NAME, TERM_DP_TYPE, TIME_DP_TYPE, STATES_CODE,
    ZIP_CODE, COUNTRY_CODE, TAX_CODE_LOCATION, MA_CAN_BO_PT,
    TEN_CAN_BO_PT, PHONG_CAN_BO_PT, NGUOI_NUOC_NGOAI, QUOC_TICH,
    MA_CAN_BO_AGRIBANK, NGUOI_GIOI_THIEU, TEN_NGUOI_GIOI_THIEU,
    CONTRACT_COUTS_DAY, SO_KY_AD_LSDB, UNTBUSCD, TYGIA,
    DataSource, ImportDateTime, CreatedBy, UpdatedBy
FROM dbo.DP01;

-- Đổi tên bảng cũ và bảng mới (sử dụng khi sẵn sàng chuyển)
/*
EXEC sp_rename 'dbo.DP01', 'DP01_Old';
EXEC sp_rename 'dbo.DP01_New', 'DP01';
*/

-- Tạo lại các index cho bảng mới
/*
CREATE NONCLUSTERED COLUMNSTORE INDEX IX_DP01_Columnstore
ON dbo.DP01 (NGAY_DL, MA_CN, MA_DON_VI, MA_KHOAN);
*/

-- Lưu ý: Cần phải điều chỉnh các ràng buộc, trigger và temporal table nếu có
