-- ===============================================
-- MIGRATION: Add Missing Columns to DP01 Table
-- Date: $(date)
-- Purpose: Add 54 missing business columns to match CSV structure
-- ===============================================

BEGIN TRANSACTION;

-- Add missing columns to DP01 table
-- Based on CSV analysis: 63 total columns, currently have 9, need to add 54

ALTER TABLE DP01 ADD
    -- Customer Information
    MA_KH NVARCHAR(50) NULL,
    TEN_KH NVARCHAR(255) NULL,

    -- Deposit Information
    DP_TYPE_NAME NVARCHAR(100) NULL,
    CCY NVARCHAR(10) NULL,
    RATE DECIMAL(18,4) NULL,
    SO_TAI_KHOAN NVARCHAR(50) NULL,
    OPENING_DATE NVARCHAR(20) NULL,
    MATURITY_DATE NVARCHAR(20) NULL,
    ADDRESS NVARCHAR(500) NULL,
    NOTENO NVARCHAR(50) NULL,
    MONTH_TERM INT NULL,
    TERM_DP_NAME NVARCHAR(100) NULL,
    TIME_DP_NAME NVARCHAR(100) NULL,
    TEN_PGD NVARCHAR(255) NULL,
    DP_TYPE_CODE NVARCHAR(20) NULL,
    RENEW_DATE NVARCHAR(20) NULL,

    -- Customer Type Information
    CUST_TYPE NVARCHAR(20) NULL,
    CUST_TYPE_NAME NVARCHAR(100) NULL,
    CUST_TYPE_DETAIL NVARCHAR(20) NULL,
    CUST_DETAIL_NAME NVARCHAR(100) NULL,

    -- Date Information
    PREVIOUS_DP_CAP_DATE NVARCHAR(20) NULL,
    NEXT_DP_CAP_DATE NVARCHAR(20) NULL,

    -- Personal Information
    ID_NUMBER NVARCHAR(50) NULL,
    ISSUED_BY NVARCHAR(100) NULL,
    ISSUE_DATE NVARCHAR(20) NULL,
    SEX_TYPE NVARCHAR(10) NULL,
    BIRTH_DATE NVARCHAR(20) NULL,
    TELEPHONE NVARCHAR(20) NULL,

    -- Financial Information
    ACRUAL_AMOUNT DECIMAL(18,2) NULL,
    ACRUAL_AMOUNT_END DECIMAL(18,2) NULL,
    ACCOUNT_STATUS NVARCHAR(20) NULL,
    DRAMT DECIMAL(18,2) NULL,
    CRAMT DECIMAL(18,2) NULL,

    -- Employee Information
    EMPLOYEE_NUMBER NVARCHAR(50) NULL,
    EMPLOYEE_NAME NVARCHAR(255) NULL,

    -- Additional Financial
    SPECIAL_RATE DECIMAL(18,4) NULL,
    AUTO_RENEWAL NVARCHAR(10) NULL,
    CLOSE_DATE NVARCHAR(20) NULL,

    -- Location Information
    LOCAL_PROVIN_NAME NVARCHAR(100) NULL,
    LOCAL_DISTRICT_NAME NVARCHAR(100) NULL,
    LOCAL_WARD_NAME NVARCHAR(100) NULL,

    -- Type Information
    TERM_DP_TYPE NVARCHAR(20) NULL,
    TIME_DP_TYPE NVARCHAR(20) NULL,

    -- Address Details
    STATES_CODE NVARCHAR(20) NULL,
    ZIP_CODE NVARCHAR(20) NULL,
    COUNTRY_CODE NVARCHAR(10) NULL,
    TAX_CODE_LOCATION NVARCHAR(50) NULL,

    -- Staff Information
    MA_CAN_BO_PT NVARCHAR(50) NULL,
    TEN_CAN_BO_PT NVARCHAR(255) NULL,
    PHONG_CAN_BO_PT NVARCHAR(100) NULL,

    -- Foreign Customer
    NGUOI_NUOC_NGOAI NVARCHAR(10) NULL,
    QUOC_TICH NVARCHAR(50) NULL,

    -- Agribank Staff
    MA_CAN_BO_AGRIBANK NVARCHAR(50) NULL,

    -- Referral Information
    NGUOI_GIOI_THIEU NVARCHAR(50) NULL,
    TEN_NGUOI_GIOI_THIEU NVARCHAR(255) NULL,

    -- Contract Information
    CONTRACT_COUTS_DAY INT NULL,
    SO_KY_AD_LSDB INT NULL,
    UNTBUSCD NVARCHAR(20) NULL,
    TYGIA DECIMAL(18,6) NULL;

-- Add indexes for commonly queried columns
CREATE INDEX IX_DP01_MA_KH ON DP01(MA_KH);
CREATE INDEX IX_DP01_SO_TAI_KHOAN ON DP01(SO_TAI_KHOAN);
CREATE INDEX IX_DP01_MA_CN ON DP01(MA_CN);
CREATE INDEX IX_DP01_OPENING_DATE ON DP01(OPENING_DATE);

COMMIT TRANSACTION;

PRINT 'Migration completed successfully: Added 54 missing columns to DP01 table';
