-- ================================================================
-- REBUILD ALL 8 TABLES: CSV Business Columns FIRST + System/Temporal LAST
-- ================================================================

USE [TinhKhoanDB]
GO

-- ================================================================
-- 1. LN01 - TEMPORAL TABLE (79 CSV Business + System/Temporal)
-- ================================================================

-- Drop existing LN01 table và history
IF OBJECT_ID('dbo.LN01', 'U') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[LN01] SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS [dbo].[LN01_History];
    DROP TABLE IF EXISTS [dbo].[LN01];
    PRINT '🗑️ Dropped existing LN01 table and history.';
END
GO

-- Create LN01 với ĐÚNG structure: 79 CSV Business + System/Temporal
CREATE TABLE [dbo].[LN01] (
    -- ======= 79 BUSINESS COLUMNS FROM CSV (EXACT ORDER) =======
    -- Columns 1-79: exactly from 7808_ln01_20241231.csv
    BRCD NVARCHAR(50),
    CUSTSEQ NVARCHAR(100),
    CUSTNM NVARCHAR(500),
    TAI_KHOAN NVARCHAR(100),
    CCY NVARCHAR(10),
    DU_NO DECIMAL(18,2),
    DSBSSEQ NVARCHAR(100),
    TRANSACTION_DATE DATETIME,
    DSBSDT DATETIME,
    DISBUR_CCY NVARCHAR(10),
    DISBURSEMENT_AMOUNT DECIMAL(18,2),
    DSBSMATDT DATETIME,
    BSRTCD NVARCHAR(50),
    INTEREST_RATE DECIMAL(10,4),
    APPRSEQ NVARCHAR(100),
    APPRDT DATETIME,
    APPR_CCY NVARCHAR(10),
    APPRAMT DECIMAL(18,2),
    APPRMATDT DATETIME,
    LOAN_TYPE NVARCHAR(100),
    FUND_RESOURCE_CODE NVARCHAR(50),
    FUND_PURPOSE_CODE NVARCHAR(50),
    REPAYMENT_AMOUNT DECIMAL(18,2),
    NEXT_REPAY_DATE DATETIME,
    NEXT_REPAY_AMOUNT DECIMAL(18,2),
    NEXT_INT_REPAY_DATE DATETIME,
    OFFICER_ID NVARCHAR(50),
    OFFICER_NAME NVARCHAR(255),
    INTEREST_AMOUNT DECIMAL(18,2),
    PASTDUE_INTEREST_AMOUNT DECIMAL(18,2),
    TOTAL_INTEREST_REPAY_AMOUNT DECIMAL(18,2),
    CUSTOMER_TYPE_CODE NVARCHAR(50),
    CUSTOMER_TYPE_CODE_DETAIL NVARCHAR(100),
    TRCTCD NVARCHAR(50),
    TRCTNM NVARCHAR(255),
    ADDR1 NVARCHAR(500),
    PROVINCE NVARCHAR(100),
    LCLPROVINNM NVARCHAR(100),
    DISTRICT NVARCHAR(100),
    LCLDISTNM NVARCHAR(100),
    COMMCD NVARCHAR(50),
    LCLWARDNM NVARCHAR(100),
    LAST_REPAY_DATE DATETIME,
    SECURED_PERCENT DECIMAL(10,4),
    NHOM_NO INT,
    LAST_INT_CHARGE_DATE DATETIME,
    EXEMPTINT NVARCHAR(10),                 -- STRING để chứa 'N' hoặc số
    EXEMPTINTTYPE NVARCHAR(50),
    EXEMPTINTAMT DECIMAL(18,2),
    GRPNO INT,
    BUSCD NVARCHAR(50),
    BSNSSCLTPCD NVARCHAR(50),
    USRIDOP NVARCHAR(50),
    ACCRUAL_AMOUNT DECIMAL(18,2),
    ACCRUAL_AMOUNT_END_OF_MONTH DECIMAL(18,2),
    INTCMTH INT,
    INTRPYMTH INT,
    INTTRMMTH INT,
    YRDAYS INT,
    REMARK NVARCHAR(500),
    CHITIEU NVARCHAR(100),
    CTCV NVARCHAR(100),
    CREDIT_LINE_YPE NVARCHAR(50),
    INT_LUMPSUM_PARTIAL_TYPE NVARCHAR(50),
    INT_PARTIAL_PAYMENT_TYPE NVARCHAR(50),
    INT_PAYMENT_INTERVAL INT,
    AN_HAN_LAI NVARCHAR(50),
    PHUONG_THUC_GIAI_NGAN_1 NVARCHAR(50),
    TAI_KHOAN_GIAI_NGAN_1 NVARCHAR(100),
    SO_TIEN_GIAI_NGAN_1 DECIMAL(18,2),
    PHUONG_THUC_GIAI_NGAN_2 NVARCHAR(50),
    TAI_KHOAN_GIAI_NGAN_2 NVARCHAR(100),
    SO_TIEN_GIAI_NGAN_2 DECIMAL(18,2),
    CMT_HC NVARCHAR(50),
    NGAY_SINH DATETIME,
    MA_CB_AGRI NVARCHAR(50),
    MA_NGANH_KT NVARCHAR(50),
    TY_GIA DECIMAL(10,4),
    OFFICER_IPCAS NVARCHAR(50),

    -- ======= SYSTEM/TEMPORAL COLUMNS (FROM COLUMN 80+) =======
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL DATETIME NOT NULL,              -- System column (data date)
    FILE_NAME NVARCHAR(255),
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LN01_History));

PRINT '✅ LN01 created: 79 CSV business + 4 system/temporal = 83 columns total';
GO

-- ================================================================
-- 2. LN03 - TEMPORAL TABLE (17 CSV Business + System/Temporal)
-- ================================================================

-- Drop existing LN03 table và history
IF OBJECT_ID('dbo.LN03', 'U') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[LN03] SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS [dbo].[LN03_History];
    DROP TABLE IF EXISTS [dbo].[LN03];
    PRINT '🗑️ Dropped existing LN03 table and history.';
END
GO

-- Create LN03 với ĐÚNG structure: 17 CSV Business + System/Temporal
CREATE TABLE [dbo].[LN03] (
    -- ======= 17 BUSINESS COLUMNS FROM CSV (EXACT ORDER) =======
    -- Columns 1-17: exactly from 7800_ln03_20241231_fixed.csv
    MACHINHANH NVARCHAR(50),
    TENCHINHANH NVARCHAR(255),
    MAKH NVARCHAR(100),
    TENKH NVARCHAR(500),
    SOHOPDONG NVARCHAR(100),
    SOTIENXLRR DECIMAL(18,2),
    NGAYPHATSINHXL DATETIME,
    THUNOSAUXL DECIMAL(18,2),
    CONLAINGOAIBANG DECIMAL(18,2),
    DUNONOIBANG DECIMAL(18,2),
    NHOMNO INT,
    MACBTD NVARCHAR(50),
    TENCBTD NVARCHAR(255),
    MAPGD NVARCHAR(50),
    TAIKHOANHACHTOAN NVARCHAR(100),
    REFNO NVARCHAR(100),
    LOAINGUONVON NVARCHAR(100),

    -- ======= SYSTEM/TEMPORAL COLUMNS (FROM COLUMN 18+) =======
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL DATETIME NOT NULL,              -- System column (data date)
    FILE_NAME NVARCHAR(255),
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LN03_History));

PRINT '✅ LN03 created: 17 CSV business + 4 system/temporal = 21 columns total';
GO

PRINT '🎯 NEW STRUCTURE IMPLEMENTED:';
PRINT '   - CSV Business columns: FIRST (exact match with CSV files)';
PRINT '   - System columns: NGAY_DL, Id, FILE_NAME';
PRINT '   - Temporal columns: CREATED_DATE, UPDATED_DATE';
PRINT '   - NO column name transformation to Vietnamese';
PRINT '   - CSV column names are the standard reference';
GO
