USE TinhKhoanDB;
SELECT 
    c.COLUMN_NAME,
    c.DATA_TYPE,
    c.IS_NULLABLE,
    c.ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS c
WHERE c.TABLE_NAME = 'GL41'
ORDER BY c.ORDINAL_POSITION;

SELECT COUNT(*) as TotalRecords FROM GL41;
