-- Check business columns match with CSV for all 7 remaining tables

-- DPDA Business Columns Check
SELECT 'DPDA' as TableName, 'Business Columns Check' as CheckType,
    ORDINAL_POSITION, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DPDA'
    AND COLUMN_NAME NOT IN ('Id', 'NGAY_DL', 'CREATED_DATE', 'UPDATED_DATE', 'FILE_NAME', 'ValidFrom', 'ValidTo')
ORDER BY ORDINAL_POSITION;

-- EI01 Business Columns Check
SELECT 'EI01' as TableName, 'Business Columns Check' as CheckType,
    ORDINAL_POSITION, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EI01'
    AND COLUMN_NAME NOT IN ('Id', 'NGAY_DL', 'CREATED_DATE', 'UPDATED_DATE', 'FILE_NAME', 'ValidFrom', 'ValidTo')
ORDER BY ORDINAL_POSITION;

-- GL41 Business Columns Check
SELECT 'GL41' as TableName, 'Business Columns Check' as CheckType,
    ORDINAL_POSITION, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'GL41'
    AND COLUMN_NAME NOT IN ('Id', 'NGAY_DL', 'CREATED_DATE', 'UPDATED_DATE', 'FILE_NAME', 'ValidFrom', 'ValidTo')
ORDER BY ORDINAL_POSITION;

-- LN01 Business Columns Check
SELECT 'LN01' as TableName, 'Business Columns Check' as CheckType,
    ORDINAL_POSITION, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'LN01'
    AND COLUMN_NAME NOT IN ('Id', 'NGAY_DL', 'CREATED_DATE', 'UPDATED_DATE', 'FILE_NAME', 'ValidFrom', 'ValidTo')
ORDER BY ORDINAL_POSITION;

-- LN03 Business Columns Check
SELECT 'LN03' as TableName, 'Business Columns Check' as CheckType,
    ORDINAL_POSITION, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'LN03'
    AND COLUMN_NAME NOT IN ('Id', 'NGAY_DL', 'CREATED_DATE', 'UPDATED_DATE', 'FILE_NAME', 'ValidFrom', 'ValidTo')
ORDER BY ORDINAL_POSITION;

-- RR01 Business Columns Check
SELECT 'RR01' as TableName, 'Business Columns Check' as CheckType,
    ORDINAL_POSITION, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'RR01'
    AND COLUMN_NAME NOT IN ('Id', 'NGAY_DL', 'CREATED_DATE', 'UPDATED_DATE', 'FILE_NAME', 'ValidFrom', 'ValidTo')
ORDER BY ORDINAL_POSITION;
