#!/bin/bash

# ===================================================================
# SCRIPT RÀ SOÁT TOÀN BỘ BẢNG: SỐ LƯỢNG VÀ TÊN CỘT
# ===================================================================

echo "🔍 ===== RÀ SOÁT TOÀN BỘ BẢNG DỮ LIỆU ====="
echo ""

# Function to check column match
check_table() {
    local table_name="$1"
    local header_csv="$2"
    local model_file="$3"

    echo "🔍 Kiểm tra $table_name..."
    echo "   Model file: $model_file"

    # Check if model file exists
    if [ ! -f "$model_file" ]; then
        echo "   ❌ File model không tồn tại!"
        return
    fi

    # Extract columns from model (exclude system columns)
    grep "\[Column(" "$model_file" | grep -o '"[^"]*"' | tr -d '"' | grep -v "NGAY_DL" | grep -v "CREATED_DATE" | grep -v "UPDATED_DATE" | grep -v "FILE_NAME" | sort > "/tmp/${table_name}_model_cols.txt"

    # Extract columns from header CSV
    echo "$header_csv" | tr ',' '\n' | sort > "/tmp/${table_name}_header_cols.txt"

    # Count columns
    MODEL_COUNT=$(cat "/tmp/${table_name}_model_cols.txt" | wc -l | tr -d ' ')
    HEADER_COUNT=$(cat "/tmp/${table_name}_header_cols.txt" | wc -l | tr -d ' ')

    echo "   📊 Model: $MODEL_COUNT cột | Header: $HEADER_COUNT cột"

    # Check for missing columns in model
    MISSING_IN_MODEL=$(comm -23 "/tmp/${table_name}_header_cols.txt" "/tmp/${table_name}_model_cols.txt")
    if [ -n "$MISSING_IN_MODEL" ]; then
        echo "   ❌ Thiếu trong Model:"
        echo "$MISSING_IN_MODEL" | sed 's/^/      /'
    fi

    # Check for extra columns in model
    EXTRA_IN_MODEL=$(comm -13 "/tmp/${table_name}_header_cols.txt" "/tmp/${table_name}_model_cols.txt")
    if [ -n "$EXTRA_IN_MODEL" ]; then
        echo "   ❌ Thừa trong Model:"
        echo "$EXTRA_IN_MODEL" | sed 's/^/      /'
    fi

    # Final check
    if [ "$MODEL_COUNT" -eq "$HEADER_COUNT" ] && [ -z "$MISSING_IN_MODEL" ] && [ -z "$EXTRA_IN_MODEL" ]; then
        echo "   ✅ CHÍNH XÁC 100%"
    else
        echo "   ❌ CÓ SAI SÓT"
    fi

    echo ""

    # Cleanup
    rm -f "/tmp/${table_name}_model_cols.txt" "/tmp/${table_name}_header_cols.txt"
}

echo "🎯 BẮT ĐẦU KIỂM TRA TỪNG BẢNG..."
echo "================================="
echo ""

# 1. DP01
check_table "DP01" "MA_CN,TAI_KHOAN_HACH_TOAN,MA_KH,TEN_KH,DP_TYPE_NAME,CCY,CURRENT_BALANCE,RATE,SO_TAI_KHOAN,OPENING_DATE,MATURITY_DATE,ADDRESS,NOTENO,MONTH_TERM,TERM_DP_NAME,TIME_DP_NAME,MA_PGD,TEN_PGD,DP_TYPE_CODE,RENEW_DATE,CUST_TYPE,CUST_TYPE_NAME,CUST_TYPE_DETAIL,CUST_DETAIL_NAME,PREVIOUS_DP_CAP_DATE,NEXT_DP_CAP_DATE,ID_NUMBER,ISSUED_BY,ISSUE_DATE,SEX_TYPE,BIRTH_DATE,TELEPHONE,ACRUAL_AMOUNT,ACRUAL_AMOUNT_END,ACCOUNT_STATUS,DRAMT,CRAMT,EMPLOYEE_NUMBER,EMPLOYEE_NAME,SPECIAL_RATE,AUTO_RENEWAL,CLOSE_DATE,LOCAL_PROVIN_NAME,LOCAL_DISTRICT_NAME,LOCAL_WARD_NAME,TERM_DP_TYPE,TIME_DP_TYPE,STATES_CODE,ZIP_CODE,COUNTRY_CODE,TAX_CODE_LOCATION,MA_CAN_BO_PT,TEN_CAN_BO_PT,PHONG_CAN_BO_PT,NGUOI_NUOC_NGOAI,QUOC_TICH,MA_CAN_BO_AGRIBANK,NGUOI_GIOI_THIEU,TEN_NGUOI_GIOI_THIEU,CONTRACT_COUTS_DAY,SO_KY_AD_LSDB,UNTBUSCD,TYGIA" "Models/DataTables/DP01.cs"

# 2. DPDA
check_table "DPDA" "MA_CHI_NHANH,MA_KHACH_HANG,TEN_KHACH_HANG,SO_TAI_KHOAN,LOAI_THE,SO_THE,NGAY_NOP_DON,NGAY_PHAT_HANH,USER_PHAT_HANH,TRANG_THAI,PHAN_LOAI,GIAO_THE,LOAI_PHAT_HANH" "Models/DataTables/DPDA.cs"

# 3. EI01
check_table "EI01" "MA_CN,MA_KH,TEN_KH,LOAI_KH,SDT_EMB,TRANG_THAI_EMB,NGAY_DK_EMB,SDT_OTT,TRANG_THAI_OTT,NGAY_DK_OTT,SDT_SMS,TRANG_THAI_SMS,NGAY_DK_SMS,SDT_SAV,TRANG_THAI_SAV,NGAY_DK_SAV,SDT_LN,TRANG_THAI_LN,NGAY_DK_LN,USER_EMB,USER_OTT,USER_SMS,USER_SAV,USER_LN" "Models/DataTables/EI01.cs"

# 4. GL01
check_table "GL01" "STS,NGAY_GD,NGUOI_TAO,DYSEQ,TR_TYPE,DT_SEQ,TAI_KHOAN,TEN_TK,SO_TIEN_GD,POST_BR,LOAI_TIEN,DR_CR,MA_KH,TEN_KH,CCA_USRID,TR_EX_RT,REMARK,BUS_CODE,UNIT_BUS_CODE,TR_CODE,TR_NAME,REFERENCE,VALUE_DATE,DEPT_CODE,TR_TIME,COMFIRM,TRDT_TIME" "Models/DataTables/GL01.cs"

# 5. KH03
check_table "KH03" "MA_CN,MA_KH,TEN_KH,SOHD,LDS,SO_TIEN_GIAI_NGAN,NGAY_GIAI_NGAN,NGAY_DEN_HAN_GN,ACCOUNT_NAME,TY_GIA,SOTIEN_PHEDUYET,DUNO_NGAN,DUNO_TRUNGDAI,BAOLANH,NHOMNO,XLRR,MANGANH,BSRT,SPRDRT,INTRT,XEP_HANG,TONG_TSDB,BDS,DS,CCTG,CK,TAI_SAN_BAO_LANH,TAI_SAN_KHAC,KI_HAN,LOAI_KH,QUY_MO_THEO_CHAM_DIEM_KH,CCYCD,ACCOUNT_LAV,QUY_MO_THEO_TT41,LOAI_TIEN_LAV,THANG_KY_HAN,NGAY_PHE_DUYET,NGAY_DEN_HAN_LAV" "Models/DataTables/KH03.cs"

# 6. LN01
check_table "LN01" "BRCD,CUSTSEQ,CUSTNM,TAI_KHOAN,CCY,DU_NO,DSBSSEQ,TRANSACTION_DATE,DSBSDT,DISBUR_CCY,DISBURSEMENT_AMOUNT,DSBSMATDT,BSRTCD,INTEREST_RATE,APPRSEQ,APPRDT,APPR_CCY,APPRAMT,APPRMATDT,LOAN_TYPE,FUND_RESOURCE_CODE,FUND_PURPOSE_CODE,REPAYMENT_AMOUNT,NEXT_REPAY_DATE,NEXT_REPAY_AMOUNT,NEXT_INT_REPAY_DATE,OFFICER_ID,OFFICER_NAME,INTEREST_AMOUNT,PASTDUE_INTEREST_AMOUNT,TOTAL_INTEREST_REPAY_AMOUNT,CUSTOMER_TYPE_CODE,CUSTOMER_TYPE_CODE_DETAIL,TRCTCD,TRCTNM,ADDR1,PROVINCE,LCLPROVINNM,DISTRICT,LCLDISTNM,COMMCD,LCLWARDNM,LAST_REPAY_DATE,SECURED_PERCENT,NHOM_NO,LAST_INT_CHARGE_DATE,EXEMPTINT,EXEMPTINTTYPE,EXEMPTINTAMT,GRPNO,BUSCD,BSNSSCLTPCD,USRIDOP,ACCRUAL_AMOUNT,ACCRUAL_AMOUNT_END_OF_MONTH,INTCMTH,INTRPYMTH,INTTRMMTH,YRDAYS,REMARK,CHITIEU,CTCV,CREDIT_LINE_YPE,INT_LUMPSUM_PARTIAL_TYPE,INT_PARTIAL_PAYMENT_TYPE,INT_PAYMENT_INTERVAL,AN_HAN_LAI,PHUONG_THUC_GIAI_NGAN_1,TAI_KHOAN_GIAI_NGAN_1,SO_TIEN_GIAI_NGAN_1,PHUONG_THUC_GIAI_NGAN_2,TAI_KHOAN_GIAI_NGAN_2,SO_TIEN_GIAI_NGAN_2,CMT_HC,NGAY_SINH,MA_CB_AGRI,MA_NGANH_KT,TY_GIA,OFFICER_IPCAS" "Models/DataTables/LN01.cs"

# 7. LN02
check_table "LN02" "TENCHINHANH,MAKHACHHANG,TENKHACHHANG,NGAYCHUYENNHOMNO,DUNO,NHOMNOMOI,NHOMNOCU,NGUYENNHAN,MACANBO,TENCANBO,MANGANH" "Models/DataTables/LN02.cs"

# 8. LN03
check_table "LN03" "MACHINHANH,TENCHINHANH,MAKH,TENKH,SOHOPDONG,SOTIENXLRR,NGAYPHATSINHXL,THUNOSAUXL,CONLAINGOAIBANG,DUNONOIBANG,NHOMNO,MACBTD,TENCBTD,MAPGD,TAIKHOANHACHTOAN,REFNO,LOAINGUONVON" "Models/DataTables/LN03.cs"

# 9. RR01
check_table "RR01" "CN_LOAI_I,BRCD,MA_KH,TEN_KH,SO_LDS,CCY,SO_LAV,LOAI_KH,NGAY_GIAI_NGAN,NGAY_DEN_HAN,VAMC_FLG,NGAY_XLRR,DUNO_GOC_BAN_DAU,DUNO_LAI_TICHLUY_BD,DOC_DAUKY_DA_THU_HT,DUNO_GOC_HIENTAI,DUNO_LAI_HIENTAI,DUNO_NGAN_HAN,DUNO_TRUNG_HAN,DUNO_DAI_HAN,THU_GOC,THU_LAI,BDS,DS,TSK" "Models/DataTables/RR01.cs"

# 10. TSDB01
check_table "TSDB01" "MA_CN,MA_KH,TEN_KH,LOAI_KH,TONG_DU_NO,VAY_NGAN_HAN,VAY_TRUNG_HAN,VAY_DAI_HAN,DU_NO_KHONG_TSDB,TONG_TSDB,BDS,MAY_MOC,GIAY_TO_CO_GIA,TSDB_KHAC,MA_NGANH_KINH_TE,CHO_VAY_NNNT" "Models/DataTables/TSDB01.cs"

echo "🎯 KẾT QUẢ TỔNG HỢP:"
echo "==================="
echo "Đã hoàn thành kiểm tra tất cả 10 bảng dữ liệu."
echo "Xem kết quả chi tiết ở trên để biết bảng nào cần sửa chữa."
