-- Create DP01 table with temporal features and columnstore index
-- First check if table exists and drop if needed

-- Create the main DP01 table with all 63 CSV columns + 4 temporal columns
CREATE TABLE [dbo].[DP01] (
    -- Primary key
    [Id] BIGINT IDENTITY(1,1) PRIMARY KEY,

    -- CSV columns (63 total)
    [MA_CN] NVARCHAR(50) NULL,
    [MA_CHINHANH] NVARCHAR(50) NULL,
    [MA_DVU] NVARCHAR(50) NULL,
    [TEN_DVU] NVARCHAR(255) NULL,
    [MA_TAIKHOAN] NVARCHAR(50) NULL,
    [TEN_TAIKHOAN] NVARCHAR(255) NULL,
    [MA_NHOM] NVARCHAR(50) NULL,
    [TEN_NHOM] NVARCHAR(255) NULL,
    [MA_TIEUTIEU] NVARCHAR(50) NULL,
    [TEN_TIEUTIEU] NVARCHAR(255) NULL,
    [SOCHUNGTU] NVARCHAR(50) NULL,
    [NGAYCHUNGTU] DATETIME2 NULL,
    [NGAYKETOAN] DATETIME2 NULL,
    [DIENGIAI] NVARCHAR(500) NULL,
    [TAIKHOAN_NO] NVARCHAR(50) NULL,
    [TAIKHOAN_CO] NVARCHAR(50) NULL,
    [SOTIENVND] DECIMAL(18,2) NULL,
    [SOTIENNGOAITE] DECIMAL(18,2) NULL,
    [GHICHU] NVARCHAR(500) NULL,
    [MALOAICHUNGTU] NVARCHAR(50) NULL,
    [TENLOAICHUNGTU] NVARCHAR(255) NULL,
    [MATIENTE] NVARCHAR(10) NULL,
    [TENTIENTE] NVARCHAR(100) NULL,
    [TYLE] DECIMAL(18,6) NULL,
    [SODU_DAUKY_NO] DECIMAL(18,2) NULL,
    [SODU_DAUKY_CO] DECIMAL(18,2) NULL,
    [SODU_CUOIKY_NO] DECIMAL(18,2) NULL,
    [SODU_CUOIKY_CO] DECIMAL(18,2) NULL,
    [PHATSINH_NO] DECIMAL(18,2) NULL,
    [PHATSINH_CO] DECIMAL(18,2) NULL,
    [MACONGTY] NVARCHAR(50) NULL,
    [TENCONGTY] NVARCHAR(255) NULL,
    [MADONVI] NVARCHAR(50) NULL,
    [TENDONVI] NVARCHAR(255) NULL,
    [MANVKT] NVARCHAR(50) NULL,
    [TENNVKT] NVARCHAR(255) NULL,
    [NAMBAOCAO] INT NULL,
    [THANGBAOCAO] INT NULL,
    [NGAYBAOCAO] DATETIME2 NULL,
    [LOAIBAOCAO] NVARCHAR(100) NULL,
    [MADANHMUC] NVARCHAR(50) NULL,
    [TENDANHMUC] NVARCHAR(255) NULL,
    [MAPHI] NVARCHAR(50) NULL,
    [TENPHI] NVARCHAR(255) NULL,
    [SOTIEN_THUNHAP] DECIMAL(18,2) NULL,
    [SOTIEN_CHIPHI] DECIMAL(18,2) NULL,
    [LAIHANG_TINHLAI] DECIMAL(18,2) NULL,
    [LAIHANG_KHONGTINH] DECIMAL(18,2) NULL,
    [CHIPHIHOATDONG] DECIMAL(18,2) NULL,
    [CHIPHIQUANLY] DECIMAL(18,2) NULL,
    [THUEPHILAC] DECIMAL(18,2) NULL,
    [LAI_TRUOCTHUEPHILAC] DECIMAL(18,2) NULL,
    [LAI_SAUTHUEPHILAC] DECIMAL(18,2) NULL,
    [CHIPHIDUBAI] DECIMAL(18,2) NULL,
    [CHIPHIKHAC] DECIMAL(18,2) NULL,
    [THUNHAPKHAC] DECIMAL(18,2) NULL,
    [CHENHLECHSOCHUAN] DECIMAL(18,2) NULL,
    [TAISANSINHGOI] DECIMAL(18,2) NULL,
    [NGUONVONSINHGOI] DECIMAL(18,2) NULL,
    [TYLEMARGIN] DECIMAL(10,6) NULL,
    [TYLEROI] DECIMAL(10,6) NULL,
    [TYLENHIEMVU] DECIMAL(10,6) NULL,
    [CHISOHIEU] DECIMAL(18,2) NULL,
    [TYGIA] DECIMAL(18,6) NULL,

    -- Temporal columns (4 additional)
    [NGAY_DL] DATETIME2 NOT NULL DEFAULT GETDATE(),
    [CREATED_DATE] DATETIME2 NOT NULL DEFAULT GETDATE(),
    [UPDATED_DATE] DATETIME2 NOT NULL DEFAULT GETDATE(),
    [FILE_NAME] NVARCHAR(255) NULL,

    -- Temporal table columns
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,

    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[DP01_History]));

-- Create columnstore index for performance
CREATE NONCLUSTERED COLUMNSTORE INDEX [IX_DP01_Columnstore] ON [dbo].[DP01]
(
    [MA_CN], [MA_CHINHANH], [MA_DVU], [TEN_DVU], [MA_TAIKHOAN], [TEN_TAIKHOAN],
    [MA_NHOM], [TEN_NHOM], [MA_TIEUTIEU], [TEN_TIEUTIEU], [SOCHUNGTU],
    [NGAYCHUNGTU], [NGAYKETOAN], [DIENGIAI], [TAIKHOAN_NO], [TAIKHOAN_CO],
    [SOTIENVND], [SOTIENNGOAITE], [GHICHU], [MALOAICHUNGTU], [TENLOAICHUNGTU],
    [MATIENTE], [TENTIENTE], [TYLE], [SODU_DAUKY_NO], [SODU_DAUKY_CO],
    [SODU_CUOIKY_NO], [SODU_CUOIKY_CO], [PHATSINH_NO], [PHATSINH_CO],
    [MACONGTY], [TENCONGTY], [MADONVI], [TENDONVI], [MANVKT], [TENNVKT],
    [NAMBAOCAO], [THANGBAOCAO], [NGAYBAOCAO], [LOAIBAOCAO], [MADANHMUC],
    [TENDANHMUC], [MAPHI], [TENPHI], [SOTIEN_THUNHAP], [SOTIEN_CHIPHI],
    [LAIHANG_TINHLAI], [LAIHANG_KHONGTINH], [CHIPHIHOATDONG], [CHIPHIQUANLY],
    [THUEPHILAC], [LAI_TRUOCTHUEPHILAC], [LAI_SAUTHUEPHILAC], [CHIPHIDUBAI],
    [CHIPHIKHAC], [THUNHAPKHAC], [CHENHLECHSOCHUAN], [TAISANSINHGOI],
    [NGUONVONSINHGOI], [TYLEMARGIN], [TYLEROI], [TYLENHIEMVU], [CHISOHIEU],
    [TYGIA], [NGAY_DL], [CREATED_DATE], [UPDATED_DATE], [FILE_NAME]
);

PRINT 'DP01 table created successfully with temporal features and columnstore index!';
