-- ===============================================
-- TẠO CÁC BẢNG DỮ LIỆU THÔ CÒN THIẾU
-- ===============================================

USE TinhKhoanDB;
GO

-- Tạo bảng DB01 (Tài khoản)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DB01')
BEGIN
    CREATE TABLE DB01 (
        Id BIGINT IDENTITY(1,1) PRIMARY KEY,
        MA_TK NVARCHAR(50),
        TEN_TK NVARCHAR(255),
        SO_DU DECIMAL(18,2),
        NGAY_DL DATE,
        CREATED_DATE DATETIME2 DEFAULT GETDATE(),
        UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
        SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETDATE(),
        SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN DEFAULT '9999-12-31 23:59:59.9999999',
        PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime)
    ) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.DB01_History));

    CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_DB01 ON DB01 (MA_TK, TEN_TK, SO_DU, NGAY_DL);
    PRINT '✅ DB01 - Temporal table + Columnstore index';
END
ELSE
    PRINT 'ℹ️ DB01 đã tồn tại';

-- Tạo bảng GL01 (Giao dịch)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'GL01')
BEGIN
    CREATE TABLE GL01 (
        Id BIGINT IDENTITY(1,1) PRIMARY KEY,
        SO_CT NVARCHAR(50),
        NGAY_GD DATE,
        SO_TIEN DECIMAL(18,2),
        MA_TK NVARCHAR(50),
        DIEN_GIAI NVARCHAR(500),
        NGAY_DL DATE,
        CREATED_DATE DATETIME2 DEFAULT GETDATE(),
        UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
        SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETDATE(),
        SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN DEFAULT '9999-12-31 23:59:59.9999999',
        PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime)
    ) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.GL01_History));

    CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_GL01 ON GL01 (SO_CT, NGAY_GD, SO_TIEN, MA_TK, NGAY_DL);
    PRINT '✅ GL01 - Temporal table + Columnstore index';
END
ELSE
    PRINT 'ℹ️ GL01 đã tồn tại';

-- Tạo bảng GL41 (Bút toán GDV)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'GL41')
BEGIN
    CREATE TABLE GL41 (
        Id BIGINT IDENTITY(1,1) PRIMARY KEY,
        SO_CT NVARCHAR(50),
        NGAY_CT DATE,
        SO_TIEN DECIMAL(18,2),
        LOAI_TIEN NVARCHAR(10),
        LOAI_BT NVARCHAR(50),
        NGAY_DL DATE,
        CREATED_DATE DATETIME2 DEFAULT GETDATE(),
        UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
        SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETDATE(),
        SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN DEFAULT '9999-12-31 23:59:59.9999999',
        PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime)
    ) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.GL41_History));

    CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_GL41 ON GL41 (SO_CT, NGAY_CT, SO_TIEN, LOAI_TIEN, LOAI_BT, NGAY_DL);
    PRINT '✅ GL41 - Temporal table + Columnstore index';
END
ELSE
    PRINT 'ℹ️ GL41 đã tồn tại';

-- Tạo bảng LN01 (Cho vay)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LN01')
BEGIN
    CREATE TABLE LN01 (
        Id BIGINT IDENTITY(1,1) PRIMARY KEY,
        SO_HD NVARCHAR(50),
        MA_KH NVARCHAR(50),
        TEN_KH NVARCHAR(255),
        SO_TIEN_VAY DECIMAL(18,2),
        LAI_SUAT DECIMAL(5,4),
        NGAY_VAY DATE,
        NGAY_DEN_HAN DATE,
        NGAY_DL DATE,
        CREATED_DATE DATETIME2 DEFAULT GETDATE(),
        UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
        SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETDATE(),
        SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN DEFAULT '9999-12-31 23:59:59.9999999',
        PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime)
    ) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LN01_History));

    CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_LN01 ON LN01 (SO_HD, MA_KH, TEN_KH, SO_TIEN_VAY, LAI_SUAT, NGAY_VAY, NGAY_DL);
    PRINT '✅ LN01 - Temporal table + Columnstore index';
END
ELSE
    PRINT 'ℹ️ LN01 đã tồn tại';

-- Tạo bảng LN03 (Nợ XLRR)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LN03')
BEGIN
    CREATE TABLE LN03 (
        Id BIGINT IDENTITY(1,1) PRIMARY KEY,
        SO_HD NVARCHAR(50),
        MA_KH NVARCHAR(50),
        TEN_KH NVARCHAR(255),
        DU_NO DECIMAL(18,2),
        NHOM_NO INT,
        NGAY_DL DATE,
        CREATED_DATE DATETIME2 DEFAULT GETDATE(),
        UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
        SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETDATE(),
        SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN DEFAULT '9999-12-31 23:59:59.9999999',
        PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime)
    ) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LN03_History));

    CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_LN03 ON LN03 (SO_HD, MA_KH, TEN_KH, DU_NO, NHOM_NO, NGAY_DL);
    PRINT '✅ LN03 - Temporal table + Columnstore index';
END
ELSE
    PRINT 'ℹ️ LN03 đã tồn tại';

-- Tạo bảng EI01 (Mobile Banking)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'EI01')
BEGIN
    CREATE TABLE EI01 (
        Id BIGINT IDENTITY(1,1) PRIMARY KEY,
        MA_KH NVARCHAR(50),
        TEN_KH NVARCHAR(255),
        SO_GD INT,
        SO_TIEN DECIMAL(18,2),
        LOAI_GD NVARCHAR(50),
        NGAY_DL DATE,
        CREATED_DATE DATETIME2 DEFAULT GETDATE(),
        UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
        SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETDATE(),
        SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN DEFAULT '9999-12-31 23:59:59.9999999',
        PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime)
    ) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.EI01_History));

    CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_EI01 ON EI01 (MA_KH, TEN_KH, SO_GD, SO_TIEN, LOAI_GD, NGAY_DL);
    PRINT '✅ EI01 - Temporal table + Columnstore index';
END
ELSE
    PRINT 'ℹ️ EI01 đã tồn tại';

-- Tạo bảng RR01 (Dư nợ gốc, lãi XLRR)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'RR01')
BEGIN
    CREATE TABLE RR01 (
        Id BIGINT IDENTITY(1,1) PRIMARY KEY,
        SO_HD NVARCHAR(50),
        MA_KH NVARCHAR(50),
        TEN_KH NVARCHAR(255),
        DU_NO_GOC DECIMAL(18,2),
        DU_NO_LAI DECIMAL(18,2),
        TONG_DU_NO DECIMAL(18,2),
        NGAY_DL DATE,
        CREATED_DATE DATETIME2 DEFAULT GETDATE(),
        UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
        SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETDATE(),
        SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN DEFAULT '9999-12-31 23:59:59.9999999',
        PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime)
    ) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RR01_History));

    CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_RR01 ON RR01 (SO_HD, MA_KH, TEN_KH, DU_NO_GOC, DU_NO_LAI, TONG_DU_NO, NGAY_DL);
    PRINT '✅ RR01 - Temporal table + Columnstore index';
END
ELSE
    PRINT 'ℹ️ RR01 đã tồn tại';

PRINT '🎉 Hoàn thành tạo tất cả bảng dữ liệu thô với Temporal Tables + Columnstore Indexes!';
