-- Tạo indexes cho 8 bảng dữ liệu để tối ưu performance
-- Chỉ tạo indexes mới, không drop gì cả

-- 1. Tạo index cho NGAY_DL trên tất cả 8 bảng
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_DP01_NGAY_DL' AND object_id = OBJECT_ID('DP01'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_DP01_NGAY_DL ON DP01 (NGAY_DL);
    PRINT 'Tạo index IX_DP01_NGAY_DL thành công';
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_DPDA_NGAY_DL' AND object_id = OBJECT_ID('DPDA'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_DPDA_NGAY_DL ON DPDA (NGAY_DL);
    PRINT 'Tạo index IX_DPDA_NGAY_DL thành công';
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EI01_NGAY_DL' AND object_id = OBJECT_ID('EI01'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_EI01_NGAY_DL ON EI01 (NGAY_DL);
    PRINT 'Tạo index IX_EI01_NGAY_DL thành công';
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GL01_NGAY_DL' AND object_id = OBJECT_ID('GL01'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_GL01_NGAY_DL ON GL01 (NGAY_DL);
    PRINT 'Tạo index IX_GL01_NGAY_DL thành công';
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GL41_NGAY_DL' AND object_id = OBJECT_ID('GL41'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_GL41_NGAY_DL ON GL41 (NGAY_DL);
    PRINT 'Tạo index IX_GL41_NGAY_DL thành công';
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LN01_NGAY_DL' AND object_id = OBJECT_ID('LN01'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_LN01_NGAY_DL ON LN01 (NGAY_DL);
    PRINT 'Tạo index IX_LN01_NGAY_DL thành công';
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LN03_NGAY_DL' AND object_id = OBJECT_ID('LN03'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_LN03_NGAY_DL ON LN03 (NGAY_DL);
    PRINT 'Tạo index IX_LN03_NGAY_DL thành công';
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_RR01_NGAY_DL' AND object_id = OBJECT_ID('RR01'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_RR01_NGAY_DL ON RR01 (NGAY_DL);
    PRINT 'Tạo index IX_RR01_NGAY_DL thành công';
END;

-- 2. Tạo indexes cho các cột thường dùng để filter/search
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_DP01_MA_CN_MA_KH' AND object_id = OBJECT_ID('DP01'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_DP01_MA_CN_MA_KH ON DP01 (MA_CN, MA_KH);
    PRINT 'Tạo index IX_DP01_MA_CN_MA_KH thành công';
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LN01_BRCD_CUSTSEQ' AND object_id = OBJECT_ID('LN01'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_LN01_BRCD_CUSTSEQ ON LN01 (BRCD, CUSTSEQ);
    PRINT 'Tạo index IX_LN01_BRCD_CUSTSEQ thành công';
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_RR01_MA_KH_NHOM_NO' AND object_id = OBJECT_ID('RR01'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_RR01_MA_KH_NHOM_NO ON RR01 (MA_KH, NHOM_NO);
    PRINT 'Tạo index IX_RR01_MA_KH_NHOM_NO thành công';
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GL01_BRCD_TRAD_ACCT' AND object_id = OBJECT_ID('GL01'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_GL01_BRCD_TRAD_ACCT ON GL01 (BRCD, TRAD_ACCT);
    PRINT 'Tạo index IX_GL01_BRCD_TRAD_ACCT thành công';
END;

PRINT 'Hoàn thành tạo indexes cho 8 bảng dữ liệu - Performance optimized!';
