#!/bin/bash

# ===================================================================
# SCRIPT RÀ SOÁT CHI TIẾT SỐ LƯỢNG VÀ TÊN CỘT THEO HEADER CSV GỐC
# ===================================================================

echo "🔍 ===== RÀ SOÁT CHI TIẾT MODEL VS HEADER CSV GỐC ====="
echo ""

# Function to count columns in header
count_columns() {
    echo "$1" | tr ',' '\n' | wc -l | tr -d ' '
}

# Function to get column names from header
get_column_names() {
    echo "$1" | tr ',' '\n'
}

echo "📋 KIỂM TRA TỪNG BẢNG:"
echo "======================"

echo ""
echo "1️⃣  DP01 - Tiền gửi"
echo "-------------------"
DP01_HEADER="MA_CN,TAI_KHOAN_HACH_TOAN,MA_KH,TEN_KH,DP_TYPE_NAME,CCY,CURRENT_BALANCE,RATE,SO_TAI_KHOAN,OPENING_DATE,MATURITY_DATE,ADDRESS,NOTENO,MONTH_TERM,TERM_DP_NAME,TIME_DP_NAME,MA_PGD,TEN_PGD,DP_TYPE_CODE,RENEW_DATE,CUST_TYPE,CUST_TYPE_NAME,CUST_TYPE_DETAIL,CUST_DETAIL_NAME,PREVIOUS_DP_CAP_DATE,NEXT_DP_CAP_DATE,ID_NUMBER,ISSUED_BY,ISSUE_DATE,SEX_TYPE,BIRTH_DATE,TELEPHONE,ACRUAL_AMOUNT,ACRUAL_AMOUNT_END,ACCOUNT_STATUS,DRAMT,CRAMT,EMPLOYEE_NUMBER,EMPLOYEE_NAME,SPECIAL_RATE,AUTO_RENEWAL,CLOSE_DATE,LOCAL_PROVIN_NAME,LOCAL_DISTRICT_NAME,LOCAL_WARD_NAME,TERM_DP_TYPE,TIME_DP_TYPE,STATES_CODE,ZIP_CODE,COUNTRY_CODE,TAX_CODE_LOCATION,MA_CAN_BO_PT,TEN_CAN_BO_PT,PHONG_CAN_BO_PT,NGUOI_NUOC_NGOAI,QUOC_TICH,MA_CAN_BO_AGRIBANK,NGUOI_GIOI_THIEU,TEN_NGUOI_GIOI_THIEU,CONTRACT_COUTS_DAY,SO_KY_AD_LSDB,UNTBUSCD,TYGIA"
DP01_COUNT=$(count_columns "$DP01_HEADER")
echo "   📄 Header CSV: $DP01_COUNT cột"
echo "   🔍 Cần kiểm tra: DP01.cs có $DP01_COUNT cột [Column] + 3 temporal + Id,NgayDL"

echo ""
echo "2️⃣  DPDA - Phát hành thẻ"
echo "------------------------"
DPDA_HEADER="MA_CHI_NHANH,MA_KHACH_HANG,TEN_KHACH_HANG,SO_TAI_KHOAN,LOAI_THE,SO_THE,NGAY_NOP_DON,NGAY_PHAT_HANH,USER_PHAT_HANH,TRANG_THAI,PHAN_LOAI,GIAO_THE,LOAI_PHAT_HANH"
DPDA_COUNT=$(count_columns "$DPDA_HEADER")
echo "   📄 Header CSV: $DPDA_COUNT cột"

echo ""
echo "3️⃣  EI01 - Mobile Banking"
echo "-------------------------"
EI01_HEADER="MA_CN,MA_KH,TEN_KH,LOAI_KH,SDT_EMB,TRANG_THAI_EMB,NGAY_DK_EMB,SDT_OTT,TRANG_THAI_OTT,NGAY_DK_OTT,SDT_SMS,TRANG_THAI_SMS,NGAY_DK_SMS,SDT_SAV,TRANG_THAI_SAV,NGAY_DK_SAV,SDT_LN,TRANG_THAI_LN,NGAY_DK_LN,USER_EMB,USER_OTT,USER_SMS,USER_SAV,USER_LN"
EI01_COUNT=$(count_columns "$EI01_HEADER")
echo "   📄 Header CSV: $EI01_COUNT cột"

echo ""
echo "4️⃣  GL01 - Bút toán GDV"
echo "-----------------------"
GL01_HEADER="STS,NGAY_GD,NGUOI_TAO,DYSEQ,TR_TYPE,DT_SEQ,TAI_KHOAN,TEN_TK,SO_TIEN_GD,POST_BR,LOAI_TIEN,DR_CR,MA_KH,TEN_KH,CCA_USRID,TR_EX_RT,REMARK,BUS_CODE,UNIT_BUS_CODE,TR_CODE,TR_NAME,REFERENCE,VALUE_DATE,DEPT_CODE,TR_TIME,COMFIRM,TRDT_TIME"
GL01_COUNT=$(count_columns "$GL01_HEADER")
echo "   📄 Header CSV: $GL01_COUNT cột"

echo ""
echo "5️⃣  KH03 - Khách hàng pháp nhân"
echo "-------------------------------"
KH03_HEADER="MA_CN,MA_KH,TEN_KH,SOHD,LDS,SO_TIEN_GIAI_NGAN,NGAY_GIAI_NGAN,NGAY_DEN_HAN_GN,ACCOUNT_NAME,TY_GIA,SOTIEN_PHEDUYET,DUNO_NGAN,DUNO_TRUNGDAI,BAOLANH,NHOMNO,XLRR,MANGANH,BSRT,SPRDRT,INTRT,XEP_HANG,TONG_TSDB,BDS,DS,CCTG,CK,TAI_SAN_BAO_LANH,TAI_SAN_KHAC,KI_HAN,LOAI_KH,QUY_MO_THEO_CHAM_DIEM_KH,CCYCD,ACCOUNT_LAV,QUY_MO_THEO_TT41,LOAI_TIEN_LAV,THANG_KY_HAN,NGAY_PHE_DUYET,NGAY_DEN_HAN_LAV"
KH03_COUNT=$(count_columns "$KH03_HEADER")
echo "   📄 Header CSV: $KH03_COUNT cột"

echo ""
echo "6️⃣  LN01 - Cho vay"
echo "------------------"
LN01_HEADER="BRCD,CUSTSEQ,CUSTNM,TAI_KHOAN,CCY,DU_NO,DSBSSEQ,TRANSACTION_DATE,DSBSDT,DISBUR_CCY,DISBURSEMENT_AMOUNT,DSBSMATDT,BSRTCD,INTEREST_RATE,APPRSEQ,APPRDT,APPR_CCY,APPRAMT,APPRMATDT,LOAN_TYPE,FUND_RESOURCE_CODE,FUND_PURPOSE_CODE,REPAYMENT_AMOUNT,NEXT_REPAY_DATE,NEXT_REPAY_AMOUNT,NEXT_INT_REPAY_DATE,OFFICER_ID,OFFICER_NAME,INTEREST_AMOUNT,PASTDUE_INTEREST_AMOUNT,TOTAL_INTEREST_REPAY_AMOUNT,CUSTOMER_TYPE_CODE,CUSTOMER_TYPE_CODE_DETAIL,TRCTCD,TRCTNM,ADDR1,PROVINCE,LCLPROVINNM,DISTRICT,LCLDISTNM,COMMCD,LCLWARDNM,LAST_REPAY_DATE,SECURED_PERCENT,NHOM_NO,LAST_INT_CHARGE_DATE,EXEMPTINT,EXEMPTINTTYPE,EXEMPTINTAMT,GRPNO,BUSCD,BSNSSCLTPCD,USRIDOP,ACCRUAL_AMOUNT,ACCRUAL_AMOUNT_END_OF_MONTH,INTCMTH,INTRPYMTH,INTTRMMTH,YRDAYS,REMARK,CHITIEU,CTCV,CREDIT_LINE_YPE,INT_LUMPSUM_PARTIAL_TYPE,INT_PARTIAL_PAYMENT_TYPE,INT_PAYMENT_INTERVAL,AN_HAN_LAI,PHUONG_THUC_GIAI_NGAN_1,TAI_KHOAN_GIAI_NGAN_1,SO_TIEN_GIAI_NGAN_1,PHUONG_THUC_GIAI_NGAN_2,TAI_KHOAN_GIAI_NGAN_2,SO_TIEN_GIAI_NGAN_2,CMT_HC,NGAY_SINH,MA_CB_AGRI,MA_NGANH_KT,TY_GIA,OFFICER_IPCAS"
LN01_COUNT=$(count_columns "$LN01_HEADER")
echo "   📄 Header CSV: $LN01_COUNT cột"

echo ""
echo "7️⃣  LN02 - Biến động nhóm nợ"
echo "----------------------------"
LN02_HEADER="TENCHINHANH,MAKHACHHANG,TENKHACHHANG,NGAYCHUYENNHOMNO,DUNO,NHOMNOMOI,NHOMNOCU,NGUYENNHAN,MACANBO,TENCANBO,MANGANH"
LN02_COUNT=$(count_columns "$LN02_HEADER")
echo "   📄 Header CSV: $LN02_COUNT cột"

echo ""
echo "8️⃣  LN03 - Nợ XLRR"
echo "------------------"
LN03_HEADER="MACHINHANH,TENCHINHANH,MAKH,TENKH,SOHOPDONG,SOTIENXLRR,NGAYPHATSINHXL,THUNOSAUXL,CONLAINGOAIBANG,DUNONOIBANG,NHOMNO,MACBTD,TENCBTD,MAPGD,TAIKHOANHACHTOAN,REFNO,LOAINGUONVON"
LN03_COUNT=$(count_columns "$LN03_HEADER")
echo "   📄 Header CSV: $LN03_COUNT cột"

echo ""
echo "9️⃣  RR01 - Dư nợ gốc, lãi XLRR"
echo "------------------------------"
RR01_HEADER="CN_LOAI_I,BRCD,MA_KH,TEN_KH,SO_LDS,CCY,SO_LAV,LOAI_KH,NGAY_GIAI_NGAN,NGAY_DEN_HAN,VAMC_FLG,NGAY_XLRR,DUNO_GOC_BAN_DAU,DUNO_LAI_TICHLUY_BD,DOC_DAUKY_DA_THU_HT,DUNO_GOC_HIENTAI,DUNO_LAI_HIENTAI,DUNO_NGAN_HAN,DUNO_TRUNG_HAN,DUNO_DAI_HAN,THU_GOC,THU_LAI,BDS,DS,TSK"
RR01_COUNT=$(count_columns "$RR01_HEADER")
echo "   📄 Header CSV: $RR01_COUNT cột"

echo ""
echo "🔟 TSDB01 - Tài sản đảm bảo"
echo "---------------------------"
TSDB01_HEADER="MA_CN,MA_KH,TEN_KH,LOAI_KH,TONG_DU_NO,VAY_NGAN_HAN,VAY_TRUNG_HAN,VAY_DAI_HAN,DU_NO_KHONG_TSDB,TONG_TSDB,BDS,MAY_MOC,GIAY_TO_CO_GIA,TSDB_KHAC,MA_NGANH_KINH_TE,CHO_VAY_NNNT"
TSDB01_COUNT=$(count_columns "$TSDB01_HEADER")
echo "   📄 Header CSV: $TSDB01_COUNT cột"

echo ""
echo "📊 TỔNG HỢP SỐ CỘT:"
echo "==================="
echo "DP01:    $DP01_COUNT cột"
echo "DPDA:    $DPDA_COUNT cột"
echo "EI01:    $EI01_COUNT cột"
echo "GL01:    $GL01_COUNT cột"
echo "KH03:    $KH03_COUNT cột"
echo "LN01:    $LN01_COUNT cột"
echo "LN02:    $LN02_COUNT cột"
echo "LN03:    $LN03_COUNT cột"
echo "RR01:    $RR01_COUNT cột"
echo "TSDB01:  $TSDB01_COUNT cột"

echo ""
echo "🔍 TIẾP THEO: Kiểm tra từng model .cs file..."
