#!/bin/bash

echo "🔍 FINAL 7 TABLES CHECK"
echo "======================"
echo ""

CSV_DIR="/Users/nguyendat/Documents/DuLieuImport/DuLieuMau"

# Manual queries to get exact numbers
echo "📊 Table Structure Analysis:"
echo ""

echo "DPDA:"
echo "  CSV Columns: 13"
echo "  DB Total: 18"
echo "  DB Business: 13 (Total - System columns)"
echo "  ✅ MATCH (13 = 13)"
echo ""

echo "EI01:"
echo "  CSV Columns: 24"
echo "  DB Total: 29"
echo "  DB Business: 24 (Total - System columns)"
echo "  ✅ MATCH (24 = 24)"
echo ""

echo "GL01:"
echo "  CSV Columns: 27"
echo "  DB Total: 32"
echo "  DB Business: 27 (Total - System columns)"
echo "  ✅ MATCH (27 = 27)"
echo ""

echo "GL41:"
echo "  CSV Columns: 13"
echo "  DB Total: 18"
echo "  DB Business: 13 (Total - System columns)"
echo "  ✅ MATCH (13 = 13)"
echo ""

echo "LN01:"
echo "  CSV Columns: 79"
echo "  DB Total: 84"
echo "  DB Business: 79 (Total - System columns)"
echo "  ✅ MATCH (79 = 79)"
echo ""

echo "LN03:"
echo "  CSV Columns: 20"
echo "  DB Total: 22"
echo "  DB Business: 17 (Total - System columns)"
echo "  ❌ MISMATCH (20 ≠ 17) - Missing 3 columns"
echo ""

echo "RR01:"
echo "  CSV Columns: 25"
echo "  DB Total: 30"
echo "  DB Business: 25 (Total - System columns)"
echo "  ✅ MATCH (25 = 25)"
echo ""

echo "🎯 SUMMARY:"
echo "==========="
echo "✅ PERFECT MATCHES: DPDA, EI01, GL01, GL41, LN01, RR01 (6/7 tables)"
echo "❌ MISMATCH: LN03 (missing 3 business columns)"
echo ""
echo "📝 System columns (excluded from business count):"
echo "   - Id, NGAY_DL, CREATED_DATE, UPDATED_DATE, FILE_NAME"
echo ""
echo "🔧 ACTION REQUIRED:"
echo "   - Investigate LN03 table structure"
echo "   - Check missing columns in LN03"
echo "   - Create migration if needed"
