-- ================================================================
-- FIX LN01 TABLE: Chỉ chứa ĐÚNG 79 columns từ CSV gốc + NGAY_DL + system/temporal
-- ================================================================

USE [TinhKhoanDB]
GO

-- Drop existing LN01 table và history
IF OBJECT_ID('dbo.LN01', 'U') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[LN01] SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS [dbo].[LN01_History];
    DROP TABLE IF EXISTS [dbo].[LN01];
    PRINT '🗑️ Dropped existing LN01 table and history.';
END
GO

-- Create LN01 với ĐÚNG structure từ CSV
CREATE TABLE [dbo].[LN01] (
    -- NGAY_DL column FIRST (system column)
    NGAY_DL DATETIME NOT NULL,

    -- 79 Business columns từ CSV LN01 (exact order from file 7808_ln01_20241231.csv)
    BRCD NVARCHAR(50),
    CUSTSEQ NVARCHAR(100),
    CUSTNM NVARCHAR(500),
    TAI_KHOAN NVARCHAR(100),
    CCY NVARCHAR(10),
    DU_NO DECIMAL(18,2),
    DSBSSEQ NVARCHAR(100),
    TRANSACTION_DATE DATETIME,
    DSBSDT DATETIME,
    DISBUR_CCY NVARCHAR(10),
    DISBURSEMENT_AMOUNT DECIMAL(18,2),
    DSBSMATDT DATETIME,
    BSRTCD NVARCHAR(50),
    INTEREST_RATE DECIMAL(10,4),
    APPRSEQ NVARCHAR(100),
    APPRDT DATETIME,
    APPR_CCY NVARCHAR(10),
    APPRAMT DECIMAL(18,2),
    APPRMATDT DATETIME,
    LOAN_TYPE NVARCHAR(100),
    FUND_RESOURCE_CODE NVARCHAR(50),
    FUND_PURPOSE_CODE NVARCHAR(50),
    REPAYMENT_AMOUNT DECIMAL(18,2),
    NEXT_REPAY_DATE DATETIME,
    NEXT_REPAY_AMOUNT DECIMAL(18,2),
    NEXT_INT_REPAY_DATE DATETIME,
    OFFICER_ID NVARCHAR(50),
    OFFICER_NAME NVARCHAR(255),
    INTEREST_AMOUNT DECIMAL(18,2),
    PASTDUE_INTEREST_AMOUNT DECIMAL(18,2),
    TOTAL_INTEREST_REPAY_AMOUNT DECIMAL(18,2),
    CUSTOMER_TYPE_CODE NVARCHAR(50),
    CUSTOMER_TYPE_CODE_DETAIL NVARCHAR(100),
    TRCTCD NVARCHAR(50),
    TRCTNM NVARCHAR(255),
    ADDR1 NVARCHAR(500),
    PROVINCE NVARCHAR(100),
    LCLPROVINNM NVARCHAR(100),
    DISTRICT NVARCHAR(100),
    LCLDISTNM NVARCHAR(100),
    COMMCD NVARCHAR(50),
    LCLWARDNM NVARCHAR(100),
    LAST_REPAY_DATE DATETIME,
    SECURED_PERCENT DECIMAL(10,4),
    NHOM_NO INT,
    LAST_INT_CHARGE_DATE DATETIME,
    EXEMPTINT DECIMAL(18,2),
    EXEMPTINTTYPE NVARCHAR(50),
    EXEMPTINTAMT DECIMAL(18,2),
    GRPNO INT,
    BUSCD NVARCHAR(50),
    BSNSSCLTPCD NVARCHAR(50),
    USRIDOP NVARCHAR(50),
    ACCRUAL_AMOUNT DECIMAL(18,2),
    ACCRUAL_AMOUNT_END_OF_MONTH DECIMAL(18,2),
    INTCMTH INT,
    INTRPYMTH INT,
    INTTRMMTH INT,
    YRDAYS INT,
    REMARK NVARCHAR(500),
    CHITIEU NVARCHAR(100),
    CTCV NVARCHAR(100),
    CREDIT_LINE_YPE NVARCHAR(50),
    INT_LUMPSUM_PARTIAL_TYPE NVARCHAR(50),
    INT_PARTIAL_PAYMENT_TYPE NVARCHAR(50),
    INT_PAYMENT_INTERVAL INT,
    AN_HAN_LAI NVARCHAR(50),
    PHUONG_THUC_GIAI_NGAN_1 NVARCHAR(50),
    TAI_KHOAN_GIAI_NGAN_1 NVARCHAR(100),
    SO_TIEN_GIAI_NGAN_1 DECIMAL(18,2),
    PHUONG_THUC_GIAI_NGAN_2 NVARCHAR(50),
    TAI_KHOAN_GIAI_NGAN_2 NVARCHAR(100),
    SO_TIEN_GIAI_NGAN_2 DECIMAL(18,2),
    CMT_HC NVARCHAR(50),
    NGAY_SINH DATETIME,
    MA_CB_AGRI NVARCHAR(50),
    MA_NGANH_KT NVARCHAR(50),
    TY_GIA DECIMAL(10,4),
    OFFICER_IPCAS NVARCHAR(50),

    -- System/Temporal columns LAST
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    FILE_NAME NVARCHAR(255),
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LN01_History));

PRINT '✅ LN01 recreated with EXACT 79 columns from CSV gốc.';
PRINT '📊 Total columns: 1 NGAY_DL + 79 CSV business + 4 system/temporal = 84 columns';
GO
