-- Simple fix NGAY_DL from NVARCHAR to DATETIME2
-- Clear data first, then alter column types

PRINT '🔧 Starting NGAY_DL to DATETIME2 conversion (DD/MM/YYYY format)...'

-- Clear existing data to avoid conversion errors
PRINT '🗑️ Clearing existing data...'
DELETE FROM DP01
DELETE FROM EI01
DELETE FROM GL01
DELETE FROM GL41
DELETE FROM LN01
DELETE FROM LN03
DELETE FROM RR01
DELETE FROM DPDA

PRINT '🔄 Converting NGAY_DL columns to DATETIME2...'

-- Convert all NGAY_DL columns to DATETIME2
ALTER TABLE DP01 ALTER COLUMN NGAY_DL DATETIME2 NOT NULL
ALTER TABLE EI01 ALTER COLUMN NGAY_DL DATETIME2 NOT NULL
ALTER TABLE GL01 ALTER COLUMN NGAY_DL DATETIME2 NOT NULL
ALTER TABLE GL41 ALTER COLUMN NGAY_DL DATETIME2 NOT NULL
ALTER TABLE LN01 ALTER COLUMN NGAY_DL DATETIME2 NOT NULL
ALTER TABLE LN03 ALTER COLUMN NGAY_DL DATETIME2 NOT NULL
ALTER TABLE RR01 ALTER COLUMN NGAY_DL DATETIME2 NOT NULL
ALTER TABLE DPDA ALTER COLUMN NGAY_DL DATETIME2 NOT NULL

PRINT '✅ NGAY_DL conversion completed!'

-- Verify the changes
PRINT '🔍 Verification - All NGAY_DL columns should now be datetime2:'
SELECT
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'NGAY_DL'
    AND TABLE_NAME IN ('DP01', 'EI01', 'GL01', 'GL41', 'LN01', 'LN03', 'RR01', 'DPDA')
ORDER BY TABLE_NAME

PRINT '📅 Ready for DD/MM/YYYY format imports!'
