-- Fix All 4 Temporal Tables Structure - Proper Approach
-- Step 1: Disable system versioning, then drop tables

-- Fix EI01
ALTER TABLE EI01 SET (SYSTEM_VERSIONING = OFF);
DROP TABLE IF EXISTS EI01;
DROP TABLE IF EXISTS EI01_History;

-- Fix GL41
ALTER TABLE GL41 SET (SYSTEM_VERSIONING = OFF);
DROP TABLE IF EXISTS GL41;
DROP TABLE IF EXISTS GL41_History;

-- Fix LN03
ALTER TABLE LN03 SET (SYSTEM_VERSIONING = OFF);
DROP TABLE IF EXISTS LN03;
DROP TABLE IF EXISTS LN03_History;

-- Fix RR01
ALTER TABLE RR01 SET (SYSTEM_VERSIONING = OFF);
DROP TABLE IF EXISTS RR01;
DROP TABLE IF EXISTS RR01_History;

PRINT '✅ Step 1: All temporal tables disabled and dropped';
