-- ================================================================
-- SCRIPT FIX TOÀN BỘ 8 BẢNG DỮ LIỆU
-- MODEL-DATABASE SYNC 100% - JULY 24, 2025
-- ================================================================
-- Tiêu chuẩn:
-- 1. NGAY_DL (Order=0) - DATETIME2 đầu tiên
-- 2. Business Columns (Order=1-N) - NVARCHAR theo CSV headers
-- 3. System Columns (cuối) - Id IDENTITY, CREATED_DATE, UPDATED_DATE, FILE_NAME
-- 4. GL01: Partitioned Columnstore (NO temporal)
-- 5. 7 bảng khác: Temporal Tables + Columnstore Indexes
-- ================================================================

USE TinhKhoanDB;
GO

SET NOCOUNT ON;

PRINT '🚀 BẮT ĐẦU FIX TOÀN BỘ 8 BẢNG DỮ LIỆU - ' + CONVERT(VARCHAR, GETDATE(), 120);
PRINT '================================================================';

-- ================================================================
-- BACKUP DATA TRƯỚC KHI FIX
-- ================================================================
PRINT '📦 STEP 1: Backup data từ 8 bảng hiện tại...';

-- Check if backup tables exist and drop them
IF OBJECT_ID('DP01_BACKUP_20250724', 'U') IS NOT NULL DROP TABLE DP01_BACKUP_20250724;
IF OBJECT_ID('LN01_BACKUP_20250724', 'U') IS NOT NULL DROP TABLE LN01_BACKUP_20250724;
IF OBJECT_ID('GL01_BACKUP_20250724', 'U') IS NOT NULL DROP TABLE GL01_BACKUP_20250724;
IF OBJECT_ID('GL41_BACKUP_20250724', 'U') IS NOT NULL DROP TABLE GL41_BACKUP_20250724;
IF OBJECT_ID('LN03_BACKUP_20250724', 'U') IS NOT NULL DROP TABLE LN03_BACKUP_20250724;
IF OBJECT_ID('RR01_BACKUP_20250724', 'U') IS NOT NULL DROP TABLE RR01_BACKUP_20250724;
IF OBJECT_ID('EI01_BACKUP_20250724', 'U') IS NOT NULL DROP TABLE EI01_BACKUP_20250724;
IF OBJECT_ID('DPDA_BACKUP_20250724', 'U') IS NOT NULL DROP TABLE DPDA_BACKUP_20250724;

-- Create backup tables với data
SELECT * INTO DP01_BACKUP_20250724 FROM DP01;
SELECT * INTO LN01_BACKUP_20250724 FROM LN01;
SELECT * INTO GL01_BACKUP_20250724 FROM GL01;
SELECT * INTO GL41_BACKUP_20250724 FROM GL41;
SELECT * INTO LN03_BACKUP_20250724 FROM LN03;
SELECT * INTO RR01_BACKUP_20250724 FROM RR01;
SELECT * INTO EI01_BACKUP_20250724 FROM EI01;
SELECT * INTO DPDA_BACKUP_20250724 FROM DPDA;

PRINT '✅ Backup completed - ' + CONVERT(VARCHAR, @@ROWCOUNT) + ' tables backed up';

-- ================================================================
-- DROP EXISTING TABLES (với temporal tables)
-- ================================================================
PRINT '🗑️ STEP 2: Drop existing tables...';

-- Disable temporal tables first
IF OBJECT_ID('DP01', 'U') IS NOT NULL
BEGIN
    ALTER TABLE DP01 SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS DP01_History;
    DROP TABLE DP01;
END

IF OBJECT_ID('LN01', 'U') IS NOT NULL
BEGIN
    ALTER TABLE LN01 SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS LN01_History;
    DROP TABLE LN01;
END

IF OBJECT_ID('GL41', 'U') IS NOT NULL
BEGIN
    ALTER TABLE GL41 SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS GL41_History;
    DROP TABLE GL41;
END

IF OBJECT_ID('LN03', 'U') IS NOT NULL
BEGIN
    ALTER TABLE LN03 SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS LN03_History;
    DROP TABLE LN03;
END

IF OBJECT_ID('RR01', 'U') IS NOT NULL
BEGIN
    ALTER TABLE RR01 SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS RR01_History;
    DROP TABLE RR01;
END

IF OBJECT_ID('EI01', 'U') IS NOT NULL
BEGIN
    ALTER TABLE EI01 SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS EI01_History;
    DROP TABLE EI01;
END

IF OBJECT_ID('DPDA', 'U') IS NOT NULL
BEGIN
    ALTER TABLE DPDA SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS DPDA_History;
    DROP TABLE DPDA;
END

-- GL01 không có temporal
DROP TABLE IF EXISTS GL01;

PRINT '✅ All tables dropped successfully';

-- ================================================================
-- RECREATE TABLE 1: DP01 (63 business columns + temporal)
-- ================================================================
PRINT '🔨 STEP 3: Creating DP01 với correct structure...';

CREATE TABLE DP01 (
    -- NGAY_DL first (Order=0)
    NGAY_DL DATETIME2 NOT NULL,

    -- Business columns (Order=1-63) - exact CSV structure
    MA_CN NVARCHAR(200) NOT NULL DEFAULT '',
    TAI_KHOAN_HACH_TOAN NVARCHAR(200) NOT NULL DEFAULT '',
    MA_KH NVARCHAR(200) NOT NULL DEFAULT '',
    TEN_KH NVARCHAR(200) NOT NULL DEFAULT '',
    DP_TYPE_NAME NVARCHAR(200) NOT NULL DEFAULT '',
    LOAI_HINH_KD NVARCHAR(200) NOT NULL DEFAULT '',
    TEN_SP NVARCHAR(200) NOT NULL DEFAULT '',
    KIEM_SOAT_THAU_CHI NVARCHAR(200) NOT NULL DEFAULT '',
    KY_HAN_GUI NVARCHAR(200) NOT NULL DEFAULT '',
    NGAY_MO NVARCHAR(200) NOT NULL DEFAULT '',
    NGAY_TAT_TOAN NVARCHAR(200) NOT NULL DEFAULT '',
    NGAY_DAO_HAN NVARCHAR(200) NOT NULL DEFAULT '',
    SO_DU_BINH_QUAN DECIMAL(18,2) NOT NULL DEFAULT 0,
    SO_DU_CUOI_KY DECIMAL(18,2) NOT NULL DEFAULT 0,
    LAI_SUAT DECIMAL(18,4) NOT NULL DEFAULT 0,
    TIEN_LAI_KY_NAY DECIMAL(18,2) NOT NULL DEFAULT 0,
    TIEN_LAI_CONG_DON DECIMAL(18,2) NOT NULL DEFAULT 0,
    LOAI_TIEN_TE NVARCHAR(200) NOT NULL DEFAULT '',
    MA_CB_QUAN_LY NVARCHAR(200) NOT NULL DEFAULT '',
    TEN_CB_QUAN_LY NVARCHAR(200) NOT NULL DEFAULT '',
    MA_CN_MO_TK NVARCHAR(200) NOT NULL DEFAULT '',
    TEN_CN_MO_TK NVARCHAR(200) NOT NULL DEFAULT '',
    HINH_THUC_TAT_TOAN NVARCHAR(200) NOT NULL DEFAULT '',
    SO_CMND_CCCD NVARCHAR(200) NOT NULL DEFAULT '',
    NGAY_SINH NVARCHAR(200) NOT NULL DEFAULT '',
    GIOI_TINH NVARCHAR(200) NOT NULL DEFAULT '',
    DIA_CHI NVARCHAR(200) NOT NULL DEFAULT '',
    PHUONG_XA NVARCHAR(200) NOT NULL DEFAULT '',
    QUAN_HUYEN NVARCHAR(200) NOT NULL DEFAULT '',
    TINH_THANH NVARCHAR(200) NOT NULL DEFAULT '',
    SDT NVARCHAR(200) NOT NULL DEFAULT '',
    EMAIL NVARCHAR(200) NOT NULL DEFAULT '',
    NGHE_NGHIEP NVARCHAR(200) NOT NULL DEFAULT '',
    NOI_CONG_TAC NVARCHAR(200) NOT NULL DEFAULT '',
    TINH_TRANG_TK NVARCHAR(200) NOT NULL DEFAULT '',
    LY_DO_DONG_TK NVARCHAR(200) NOT NULL DEFAULT '',
    THONG_TIN_BO_SUNG NVARCHAR(200) NOT NULL DEFAULT '',
    MA_KH_CIF NVARCHAR(200) NOT NULL DEFAULT '',
    NHOM_KH NVARCHAR(200) NOT NULL DEFAULT '',
    HINH_THUC_GUI NVARCHAR(200) NOT NULL DEFAULT '',
    LS_CAM_KET DECIMAL(18,4) NOT NULL DEFAULT 0,
    LS_THUC_TE DECIMAL(18,4) NOT NULL DEFAULT 0,
    CHENH_LECH_LS DECIMAL(18,4) NOT NULL DEFAULT 0,
    NGUON_VON NVARCHAR(200) NOT NULL DEFAULT '',
    GHI_CHU NVARCHAR(200) NOT NULL DEFAULT '',
    TRANG_THAI_TK NVARCHAR(200) NOT NULL DEFAULT '',
    THOI_GIAN_TAO NVARCHAR(200) NOT NULL DEFAULT '',
    NGUOI_TAO NVARCHAR(200) NOT NULL DEFAULT '',
    THOI_GIAN_SUA NVARCHAR(200) NOT NULL DEFAULT '',
    NGUOI_SUA NVARCHAR(200) NOT NULL DEFAULT '',
    THOI_GIAN_DUYET NVARCHAR(200) NOT NULL DEFAULT '',
    NGUOI_DUYET NVARCHAR(200) NOT NULL DEFAULT '',
    NAM_SINH NVARCHAR(200) NOT NULL DEFAULT '',
    NOI_SINH NVARCHAR(200) NOT NULL DEFAULT '',
    QUOC_TICH NVARCHAR(200) NOT NULL DEFAULT '',
    DAN_TOC NVARCHAR(200) NOT NULL DEFAULT '',
    TON_GIAO NVARCHAR(200) NOT NULL DEFAULT '',
    TRINH_DO_HOC_VAN NVARCHAR(200) NOT NULL DEFAULT '',
    TINH_TRANG_HON_NHAN NVARCHAR(200) NOT NULL DEFAULT '',
    TEN_NGUOI_LIEN_HE NVARCHAR(200) NOT NULL DEFAULT '',
    QUAN_HE_NGUOI_LIEN_HE NVARCHAR(200) NOT NULL DEFAULT '',
    SDT_NGUOI_LIEN_HE NVARCHAR(200) NOT NULL DEFAULT '',
    DIA_CHI_NGUOI_LIEN_HE NVARCHAR(200) NOT NULL DEFAULT '',
    GHI_CHU_BO_SUNG NVARCHAR(200) NOT NULL DEFAULT '',
    MA_NVIEN_MG NVARCHAR(200) NOT NULL DEFAULT '',
    TEN_NVIEN_MG NVARCHAR(200) NOT NULL DEFAULT '',
    KENH_PHAT_TRIEN NVARCHAR(200) NOT NULL DEFAULT '',
    NHOM_DOITUONG_KH NVARCHAR(200) NOT NULL DEFAULT '',
    MA_SANPHAM NVARCHAR(200) NOT NULL DEFAULT '',

    -- System columns (cuối cùng)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(500) NOT NULL DEFAULT '',
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.DP01_History));

PRINT '✅ DP01 created với temporal table';

-- ================================================================
-- RECREATE TABLE 2: LN01 (79 business columns + temporal)
-- ================================================================
PRINT '🔨 STEP 4: Creating LN01 với correct structure...';

CREATE TABLE LN01 (
    -- NGAY_DL first (Order=0)
    NGAY_DL DATETIME2 NOT NULL,

    -- Business columns (Order=1-79) - exact CSV structure
    BRCD NVARCHAR(200) NOT NULL DEFAULT '',
    CUSTSEQ NVARCHAR(200) NOT NULL DEFAULT '',
    CUSTNM NVARCHAR(200) NOT NULL DEFAULT '',
    TAI_KHOAN NVARCHAR(200) NOT NULL DEFAULT '',
    CCY NVARCHAR(200) NOT NULL DEFAULT '',
    DU_NO DECIMAL(18,2) NOT NULL DEFAULT 0,
    DSBSSEQ NVARCHAR(200) NOT NULL DEFAULT '',
    TRANSACTION_DATE DATETIME2 NULL,
    DSBSDT DATETIME2 NULL,
    DISBUR_CCY NVARCHAR(200) NOT NULL DEFAULT '',
    DISBURSEMENT_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    DSBSMATDT DATETIME2 NULL,
    BSRTCD NVARCHAR(200) NOT NULL DEFAULT '',
    INTEREST_RATE DECIMAL(18,4) NOT NULL DEFAULT 0,
    APPRSEQ NVARCHAR(200) NOT NULL DEFAULT '',
    APPRDT DATETIME2 NULL,
    APPR_CCY NVARCHAR(200) NOT NULL DEFAULT '',
    APPRAMT DECIMAL(18,2) NOT NULL DEFAULT 0,
    APPRMATDT DATETIME2 NULL,
    LOAN_TYPE NVARCHAR(200) NOT NULL DEFAULT '',
    FUND_RESOURCE_CODE NVARCHAR(200) NOT NULL DEFAULT '',
    FUND_PURPOSE_CODE NVARCHAR(200) NOT NULL DEFAULT '',
    REPAYMENT_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    NEXT_REPAY_DATE DATETIME2 NULL,
    NEXT_REPAY_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    NEXT_INT_REPAY_DATE DATETIME2 NULL,
    OFFICER_ID NVARCHAR(200) NOT NULL DEFAULT '',
    OFFICER_NAME NVARCHAR(200) NOT NULL DEFAULT '',
    INTEREST_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    PASTDUE_INTEREST_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    TOTAL_INTEREST_REPAY_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    CUSTOMER_TYPE_CODE NVARCHAR(200) NOT NULL DEFAULT '',
    CUSTOMER_TYPE_CODE_DETAIL NVARCHAR(200) NOT NULL DEFAULT '',
    TRCTCD NVARCHAR(200) NOT NULL DEFAULT '',
    TRCTNM NVARCHAR(200) NOT NULL DEFAULT '',
    ADDR1 NVARCHAR(200) NOT NULL DEFAULT '',
    PROVINCE NVARCHAR(200) NOT NULL DEFAULT '',
    LCLPROVINNM NVARCHAR(200) NOT NULL DEFAULT '',
    DISTRICT NVARCHAR(200) NOT NULL DEFAULT '',
    LCLDISTNM NVARCHAR(200) NOT NULL DEFAULT '',
    COMMCD NVARCHAR(200) NOT NULL DEFAULT '',
    LCLWARDNM NVARCHAR(200) NOT NULL DEFAULT '',
    LAST_REPAY_DATE DATETIME2 NULL,
    SECURED_PERCENT DECIMAL(18,2) NOT NULL DEFAULT 0,
    NHOM_NO NVARCHAR(200) NOT NULL DEFAULT '',
    LAST_INT_CHARGE_DATE DATETIME2 NULL,
    EXEMPTINT NVARCHAR(200) NOT NULL DEFAULT '',
    EXEMPTINTTYPE NVARCHAR(200) NOT NULL DEFAULT '',
    EXEMPTINTAMT DECIMAL(18,2) NOT NULL DEFAULT 0,
    GRPNO NVARCHAR(200) NOT NULL DEFAULT '',
    BUSCD NVARCHAR(200) NOT NULL DEFAULT '',
    BSNSSCLTPCD NVARCHAR(200) NOT NULL DEFAULT '',
    USRIDOP NVARCHAR(200) NOT NULL DEFAULT '',
    ACCRUAL_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    ACCRUAL_AMOUNT_END_OF_MONTH DECIMAL(18,2) NOT NULL DEFAULT 0,
    INTCMTH NVARCHAR(200) NOT NULL DEFAULT '',
    INTRPYMTH NVARCHAR(200) NOT NULL DEFAULT '',
    INTTRMMTH NVARCHAR(200) NOT NULL DEFAULT '',
    YRDAYS NVARCHAR(200) NOT NULL DEFAULT '',
    REMARK NVARCHAR(200) NOT NULL DEFAULT '',
    CHITIEU NVARCHAR(200) NOT NULL DEFAULT '',
    CTCV NVARCHAR(200) NOT NULL DEFAULT '',
    CREDIT_LINE_YPE NVARCHAR(200) NOT NULL DEFAULT '',
    INT_LUMPSUM_PARTIAL_TYPE NVARCHAR(200) NOT NULL DEFAULT '',
    INT_PARTIAL_PAYMENT_TYPE NVARCHAR(200) NOT NULL DEFAULT '',
    INT_PAYMENT_INTERVAL NVARCHAR(200) NOT NULL DEFAULT '',
    AN_HAN_LAI NVARCHAR(200) NOT NULL DEFAULT '',
    PHUONG_THUC_GIAI_NGAN_1 NVARCHAR(200) NOT NULL DEFAULT '',
    TAI_KHOAN_GIAI_NGAN_1 NVARCHAR(200) NOT NULL DEFAULT '',
    SO_TIEN_GIAI_NGAN_1 DECIMAL(18,2) NOT NULL DEFAULT 0,
    PHUONG_THUC_GIAI_NGAN_2 NVARCHAR(200) NOT NULL DEFAULT '',
    TAI_KHOAN_GIAI_NGAN_2 NVARCHAR(200) NOT NULL DEFAULT '',
    SO_TIEN_GIAI_NGAN_2 DECIMAL(18,2) NOT NULL DEFAULT 0,
    CMT_HC NVARCHAR(200) NOT NULL DEFAULT '',
    NGAY_SINH DATETIME2 NULL,
    MA_CB_AGRI NVARCHAR(200) NOT NULL DEFAULT '',
    MA_NGANH_KT NVARCHAR(200) NOT NULL DEFAULT '',
    TY_GIA DECIMAL(18,4) NOT NULL DEFAULT 0,
    OFFICER_IPCAS NVARCHAR(200) NOT NULL DEFAULT '',

    -- System columns (cuối cùng)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(500) NOT NULL DEFAULT '',
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LN01_History));

PRINT '✅ LN01 created với temporal table';

-- ================================================================
-- RECREATE TABLE 3: GL01 (27 business columns + PARTITIONED COLUMNSTORE)
-- ================================================================
PRINT '🔨 STEP 5: Creating GL01 với Partitioned Columnstore...';

CREATE TABLE GL01 (
    -- NGAY_DL first (Order=0) - từ TR_TIME column trong CSV
    NGAY_DL DATETIME2 NOT NULL,

    -- Business columns (Order=1-27) - exact CSV structure
    STS NVARCHAR(200) NOT NULL DEFAULT '',
    NGAY_GD DATETIME2 NULL,
    NGUOI_TAO NVARCHAR(200) NOT NULL DEFAULT '',
    DYSEQ NVARCHAR(200) NOT NULL DEFAULT '',
    TR_TYPE NVARCHAR(200) NOT NULL DEFAULT '',
    REFNO NVARCHAR(200) NOT NULL DEFAULT '',
    BRCD NVARCHAR(200) NOT NULL DEFAULT '',
    TRAD_ACCT NVARCHAR(200) NOT NULL DEFAULT '',
    CUSTID NVARCHAR(200) NOT NULL DEFAULT '',
    CUSTNM NVARCHAR(200) NOT NULL DEFAULT '',
    TR_CURR NVARCHAR(200) NOT NULL DEFAULT '',
    TR_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    TRAN_DESC NVARCHAR(200) NOT NULL DEFAULT '',
    CONTRNO NVARCHAR(200) NOT NULL DEFAULT '',
    RATE DECIMAL(18,4) NOT NULL DEFAULT 0,
    BALANCE DECIMAL(18,2) NOT NULL DEFAULT 0,
    PRIN_BALANCE DECIMAL(18,2) NOT NULL DEFAULT 0,
    LNACCOUNT NVARCHAR(200) NOT NULL DEFAULT '',
    OFCCD NVARCHAR(200) NOT NULL DEFAULT '',
    MAKER NVARCHAR(200) NOT NULL DEFAULT '',
    CHECKER NVARCHAR(200) NOT NULL DEFAULT '',
    AUTHORIZER NVARCHAR(200) NOT NULL DEFAULT '',
    INPUTTER NVARCHAR(200) NOT NULL DEFAULT '',
    RECORD_STATUS NVARCHAR(200) NOT NULL DEFAULT '',
    CURR_NO NVARCHAR(200) NOT NULL DEFAULT '',
    TR_TIME DATETIME2 NULL, -- Special: NGAY_DL lấy từ cột này
    DR_CR_FLG NVARCHAR(200) NOT NULL DEFAULT '',

    -- System columns (cuối cùng) - NO TEMPORAL for GL01
    Id BIGINT IDENTITY(1,1) NOT NULL,
    CREATED_DATE DATETIME2 NOT NULL DEFAULT GETDATE(),
    UPDATED_DATE DATETIME2 NOT NULL DEFAULT GETDATE(),
    FILE_NAME NVARCHAR(500) NOT NULL DEFAULT ''
);

-- Create clustered primary key first
ALTER TABLE GL01 ADD CONSTRAINT PK_GL01 PRIMARY KEY NONCLUSTERED (Id);

-- Create partitioned columnstore index (drop existing clustered index)
CREATE CLUSTERED COLUMNSTORE INDEX CCI_GL01 ON GL01;

PRINT '✅ GL01 created với Partitioned Columnstore';

-- ================================================================
-- RECREATE TABLE 4: GL41 (13 business columns + temporal)
-- ================================================================
PRINT '🔨 STEP 6: Creating GL41 với correct structure...';

CREATE TABLE GL41 (
    -- NGAY_DL first (Order=0)
    NGAY_DL DATETIME2 NOT NULL,

    -- Business columns (Order=1-13) - exact CSV structure
    CUSTID NVARCHAR(200) NOT NULL DEFAULT '',
    CUSTNM NVARCHAR(200) NOT NULL DEFAULT '',
    CURR NVARCHAR(200) NOT NULL DEFAULT '',
    CCY NVARCHAR(200) NOT NULL DEFAULT '',
    WORKING_BALANCE DECIMAL(18,2) NOT NULL DEFAULT 0,
    LOCKED_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    TOTAL_BAL DECIMAL(18,2) NOT NULL DEFAULT 0,
    BRCD NVARCHAR(200) NOT NULL DEFAULT '',
    ACCT_TITLE NVARCHAR(200) NOT NULL DEFAULT '',
    CLASS_TYPE NVARCHAR(200) NOT NULL DEFAULT '',
    ACCT_HEAD_OFFICE NVARCHAR(200) NOT NULL DEFAULT '',
    DATE_LAST_CR_INT DATETIME2 NULL,
    DATE_LAST_DR_INT DATETIME2 NULL,

    -- System columns (cuối cùng)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(500) NOT NULL DEFAULT '',
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.GL41_History));

PRINT '✅ GL41 created với temporal table';

-- ================================================================
-- RECREATE TABLE 5: LN03 (17 business columns + temporal)
-- ================================================================
PRINT '🔨 STEP 7: Creating LN03 với correct structure...';

CREATE TABLE LN03 (
    -- NGAY_DL first (Order=0)
    NGAY_DL DATETIME2 NOT NULL,

    -- Business columns (Order=1-17) - exact CSV structure
    MACHINHANH NVARCHAR(200) NOT NULL DEFAULT '',
    TENCHINHANH NVARCHAR(200) NOT NULL DEFAULT '',
    MAKH NVARCHAR(200) NOT NULL DEFAULT '',
    TENKH NVARCHAR(200) NOT NULL DEFAULT '',
    SOHOPDONG NVARCHAR(200) NOT NULL DEFAULT '',
    SOTIENXLRR DECIMAL(18,2) NOT NULL DEFAULT 0,
    NGAYPHATSINHXL DATETIME2 NULL,
    THUNOSAUXL DECIMAL(18,2) NOT NULL DEFAULT 0,
    CONLAINGOAIBANG DECIMAL(18,2) NOT NULL DEFAULT 0,
    DUNONOIBANG DECIMAL(18,2) NOT NULL DEFAULT 0,
    NHOMNO INT NOT NULL DEFAULT 0,
    MACBTD NVARCHAR(200) NOT NULL DEFAULT '',
    TENCBTD NVARCHAR(200) NOT NULL DEFAULT '',
    MAPGD NVARCHAR(200) NOT NULL DEFAULT '',
    TAIKHOANHACHTOAN NVARCHAR(200) NOT NULL DEFAULT '',
    REFNO NVARCHAR(200) NOT NULL DEFAULT '',
    LOAINGUONVON NVARCHAR(200) NOT NULL DEFAULT '',

    -- System columns (cuối cùng)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(500) NOT NULL DEFAULT '',
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LN03_History));

PRINT '✅ LN03 created với temporal table';

-- ================================================================
-- RECREATE TABLE 6: RR01 (25 business columns + temporal)
-- ================================================================
PRINT '🔨 STEP 8: Creating RR01 với correct structure...';

CREATE TABLE RR01 (
    -- NGAY_DL first (Order=0)
    NGAY_DL DATETIME2 NOT NULL,

    -- Business columns (Order=1-25) - exact CSV structure
    CN_LOAI_I NVARCHAR(200) NOT NULL DEFAULT '',
    BRCD NVARCHAR(200) NOT NULL DEFAULT '',
    MA_KH NVARCHAR(200) NOT NULL DEFAULT '',
    TEN_KH NVARCHAR(200) NOT NULL DEFAULT '',
    SO_LDS NVARCHAR(200) NOT NULL DEFAULT '',
    SO_TIEN_PTTT DECIMAL(18,2) NOT NULL DEFAULT 0,
    SO_TIEN_KHONG_PTTT DECIMAL(18,2) NOT NULL DEFAULT 0,
    TONG_NO_GIAM DECIMAL(18,2) NOT NULL DEFAULT 0,
    TIEN_LAI_QUA_HAN DECIMAL(18,2) NOT NULL DEFAULT 0,
    TONG_TIEN_LAI DECIMAL(18,2) NOT NULL DEFAULT 0,
    NHOM_NO NVARCHAR(200) NOT NULL DEFAULT '',
    LOAI_KH NVARCHAR(200) NOT NULL DEFAULT '',
    LOAI_SP NVARCHAR(200) NOT NULL DEFAULT '',
    TEN_SP NVARCHAR(200) NOT NULL DEFAULT '',
    NGUON_VON NVARCHAR(200) NOT NULL DEFAULT '',
    NGAY_TAO_LDS DATETIME2 NULL,
    NGAY_DUYET_LDS DATETIME2 NULL,
    NGKY_DKLAN_DT DATETIME2 NULL,
    SO_LAN_GIA_HAN NVARCHAR(200) NOT NULL DEFAULT '',
    NGAY_DAO_HAN DATETIME2 NULL,
    MA_CB_QUAN_LY NVARCHAR(200) NOT NULL DEFAULT '',
    TEN_CB_QUAN_LY NVARCHAR(200) NOT NULL DEFAULT '',
    MAPGD NVARCHAR(200) NOT NULL DEFAULT '',
    TENPGD NVARCHAR(200) NOT NULL DEFAULT '',
    GHI_CHU NVARCHAR(200) NOT NULL DEFAULT '',

    -- System columns (cuối cùng)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(500) NOT NULL DEFAULT '',
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RR01_History));

PRINT '✅ RR01 created với temporal table';

-- ================================================================
-- RECREATE TABLE 7: EI01 (24 business columns + temporal)
-- ================================================================
PRINT '🔨 STEP 9: Creating EI01 với correct structure...';

CREATE TABLE EI01 (
    -- NGAY_DL first (Order=0)
    NGAY_DL DATETIME2 NOT NULL,

    -- Business columns (Order=1-24) - exact CSV structure
    BRCD NVARCHAR(200) NOT NULL DEFAULT '',
    CUSTID NVARCHAR(200) NOT NULL DEFAULT '',
    CUSTNM NVARCHAR(200) NOT NULL DEFAULT '',
    AC_NO NVARCHAR(200) NOT NULL DEFAULT '',
    AC_DESC NVARCHAR(200) NOT NULL DEFAULT '',
    CCY NVARCHAR(200) NOT NULL DEFAULT '',
    BALANCE DECIMAL(18,2) NOT NULL DEFAULT 0,
    GL_SUB_HEAD_CODE NVARCHAR(200) NOT NULL DEFAULT '',
    ACCT_HEAD_OFFICE NVARCHAR(200) NOT NULL DEFAULT '',
    DATE_BAL_UPD DATETIME2 NULL,
    MONTH_BOOK NVARCHAR(200) NOT NULL DEFAULT '',
    ACCT_TITLE NVARCHAR(200) NOT NULL DEFAULT '',
    CLASS_TYPE NVARCHAR(200) NOT NULL DEFAULT '',
    MAIN_TYPE NVARCHAR(200) NOT NULL DEFAULT '',
    SUB_TYPE NVARCHAR(200) NOT NULL DEFAULT '',
    ACCT_TYPE_SPEC NVARCHAR(200) NOT NULL DEFAULT '',
    WORKING_BALANCE DECIMAL(18,2) NOT NULL DEFAULT 0,
    BLOCKED_BALANCE DECIMAL(18,2) NOT NULL DEFAULT 0,
    LOCKED_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    TOTAL_BAL DECIMAL(18,2) NOT NULL DEFAULT 0,
    ACCT_STATUS NVARCHAR(200) NOT NULL DEFAULT '',
    PASSBOOK_LINE NVARCHAR(200) NOT NULL DEFAULT '',
    DATE_LAST_CR_INT DATETIME2 NULL,
    DATE_LAST_DR_INT DATETIME2 NULL,

    -- System columns (cuối cùng)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(500) NOT NULL DEFAULT '',
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.EI01_History));

PRINT '✅ EI01 created với temporal table';

-- ================================================================
-- RECREATE TABLE 8: DPDA (13 business columns + temporal)
-- ================================================================
PRINT '🔨 STEP 10: Creating DPDA với correct structure...';

CREATE TABLE DPDA (
    -- NGAY_DL first (Order=0)
    NGAY_DL DATETIME2 NOT NULL,

    -- Business columns (Order=1-13) - exact CSV structure
    CUSTID NVARCHAR(200) NOT NULL DEFAULT '',
    CUSTNM NVARCHAR(200) NOT NULL DEFAULT '',
    CCY NVARCHAR(200) NOT NULL DEFAULT '',
    BALANCE DECIMAL(18,2) NOT NULL DEFAULT 0,
    ACNO NVARCHAR(200) NOT NULL DEFAULT '',
    ACTYPE NVARCHAR(200) NOT NULL DEFAULT '',
    BRNM NVARCHAR(200) NOT NULL DEFAULT '',
    ACID NVARCHAR(200) NOT NULL DEFAULT '',
    ACSTATUS NVARCHAR(200) NOT NULL DEFAULT '',
    OPENDT DATETIME2 NULL,
    MATDT DATETIME2 NULL,
    RATE DECIMAL(18,4) NOT NULL DEFAULT 0,
    PROD_CODE NVARCHAR(200) NOT NULL DEFAULT '',

    -- System columns (cuối cùng)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(500) NOT NULL DEFAULT '',
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.DPDA_History));

PRINT '✅ DPDA created với temporal table';

-- ================================================================
-- CREATE COLUMNSTORE INDEXES (for 7 temporal tables)
-- ================================================================
PRINT '📊 STEP 11: Creating Columnstore Indexes...';

CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_DP01 ON DP01 (NGAY_DL, MA_CN, TAI_KHOAN_HACH_TOAN, MA_KH, TEN_KH, SO_DU_CUOI_KY, TIEN_LAI_KY_NAY);
CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_LN01 ON LN01 (NGAY_DL, BRCD, CUSTSEQ, CUSTNM, TAI_KHOAN, DU_NO, INTEREST_RATE);
CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_GL41 ON GL41 (NGAY_DL, CUSTID, CUSTNM, CURR, WORKING_BALANCE, TOTAL_BAL);
CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_LN03 ON LN03 (NGAY_DL, MACHINHANH, MAKH, TENKH, SOTIENXLRR, NHOMNO);
CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_RR01 ON RR01 (NGAY_DL, BRCD, MA_KH, TEN_KH, SO_TIEN_PTTT, NHOM_NO);
CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_EI01 ON EI01 (NGAY_DL, BRCD, CUSTID, CUSTNM, AC_NO, BALANCE);
CREATE NONCLUSTERED COLUMNSTORE INDEX NCCI_DPDA ON DPDA (NGAY_DL, CUSTID, CUSTNM, CCY, BALANCE, ACNO);

PRINT '✅ All Columnstore Indexes created';

-- ================================================================
-- VERIFICATION & SUMMARY
-- ================================================================
PRINT '🔍 STEP 12: Verification Results...';

SELECT
    TABLE_NAME as [Bảng],
    COUNT(*) as [Số Cột],
    CASE
        WHEN TABLE_NAME = 'GL01' THEN 'Partitioned Columnstore (No Temporal)'
        ELSE 'Temporal Table + Columnstore'
    END as [Loại Bảng]
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('DP01', 'LN01', 'GL01', 'GL41', 'LN03', 'RR01', 'EI01', 'DPDA')
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;

PRINT '';
PRINT '🎯 COLUMN ORDER VERIFICATION:';
SELECT
    'DP01' as [Bảng],
    COLUMN_NAME as [Cột],
    ORDINAL_POSITION as [Vị Trí],
    DATA_TYPE as [Kiểu Dữ Liệu]
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DP01' AND ORDINAL_POSITION <= 5
ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT '================================================================';
PRINT '🎉 HOÀN THÀNH FIX TOÀN BỘ 8 BẢNG DỮ LIỆU';
PRINT '================================================================';
PRINT '✅ Tất cả bảng có NGAY_DL đầu tiên (Order=0)';
PRINT '✅ Business columns theo đúng CSV structure';
PRINT '✅ System columns cuối cùng (Id IDENTITY)';
PRINT '✅ GL01: Partitioned Columnstore (No Temporal)';
PRINT '✅ 7 bảng khác: Temporal Tables + Columnstore';
PRINT '✅ Format: NGAY_DL=DATETIME2, Business=NVARCHAR(200)';
PRINT '================================================================';
PRINT 'READY FOR DIRECT IMPORT VỚI COLUMN MAPPING BY NAME!';
PRINT '================================================================';

GO
