-- Script di chuyển cho LN03: Thay đổi các kiểu dữ liệu từ chuỗi sang số và ngày tháng
-- QUAN TRỌNG: Script này giữ nguyên các bảng thời gian và chỉ mục columnstore
-- CẢNH BÁO: Sao lưu dữ liệu trước khi thực hiện script này

-- Tạo bảng tạm thời để lưu trữ dữ liệu hiện có
CREATE TABLE #TempLN03 (
    NGAY_DL DATETIME2 NOT NULL,
    MACHINHANH NVARCHAR(200) NOT NULL,
    TENCHINHANH NVARCHAR(200) NOT NULL,
    MAKH NVARCHAR(200) NOT NULL,
    TENKH NVARCHAR(200) NOT NULL,
    SOHOPDONG NVARCHAR(200) NOT NULL,
    SOTIENXLRR DECIMAL(18,2) NULL,
    NGAYPHATSINHXL DATETIME2 NULL,
    THUNOSAUXL DECIMAL(18,2) NULL,
    CONLAINGOAIBANG DECIMAL(18,2) NULL,
    DUNONOIBANG DECIMAL(18,2) NULL,
    NHOMNO NVARCHAR(200) NOT NULL,
    MACBTD NVARCHAR(200) NOT NULL,
    TENCBTD NVARCHAR(200) NOT NULL,
    MAPGD NVARCHAR(200) NOT NULL,
    TAIKHOANHACHTOAN NVARCHAR(200) NOT NULL,
    REFNO NVARCHAR(200) NOT NULL,
    LOAINGUONVON NVARCHAR(200) NOT NULL,
    Id BIGINT NOT NULL,
    CREATED_DATE DATETIME2 NOT NULL,
    UPDATED_DATE DATETIME2 NOT NULL,
    FILE_NAME NVARCHAR(255) NOT NULL
);

-- Sao chép dữ liệu từ bảng chính sang bảng tạm, chuyển đổi kiểu dữ liệu
INSERT INTO #TempLN03 (
    NGAY_DL, MACHINHANH, TENCHINHANH, MAKH, TENKH, SOHOPDONG,
    SOTIENXLRR, NGAYPHATSINHXL, THUNOSAUXL, CONLAINGOAIBANG, DUNONOIBANG,
    NHOMNO, MACBTD, TENCBTD, MAPGD, TAIKHOANHACHTOAN, REFNO, LOAINGUONVON,
    Id, CREATED_DATE, UPDATED_DATE, FILE_NAME
)
SELECT 
    NGAY_DL, MACHINHANH, TENCHINHANH, MAKH, TENKH, SOHOPDONG,
    CASE WHEN SOTIENXLRR IS NULL OR SOTIENXLRR = '' THEN NULL
         WHEN ISNUMERIC(REPLACE(REPLACE(SOTIENXLRR, ',', ''), '.', '')) = 1 THEN TRY_CAST(REPLACE(SOTIENXLRR, ',', '') AS DECIMAL(18,2))
         ELSE NULL END AS SOTIENXLRR,
    CASE WHEN NGAYPHATSINHXL IS NULL OR NGAYPHATSINHXL = '' THEN NULL
         ELSE TRY_CAST(NGAYPHATSINHXL AS DATETIME2) END AS NGAYPHATSINHXL,
    CASE WHEN THUNOSAUXL IS NULL OR THUNOSAUXL = '' THEN NULL
         WHEN ISNUMERIC(REPLACE(REPLACE(THUNOSAUXL, ',', ''), '.', '')) = 1 THEN TRY_CAST(REPLACE(THUNOSAUXL, ',', '') AS DECIMAL(18,2))
         ELSE NULL END AS THUNOSAUXL,
    CASE WHEN CONLAINGOAIBANG IS NULL OR CONLAINGOAIBANG = '' THEN NULL
         WHEN ISNUMERIC(REPLACE(REPLACE(CONLAINGOAIBANG, ',', ''), '.', '')) = 1 THEN TRY_CAST(REPLACE(CONLAINGOAIBANG, ',', '') AS DECIMAL(18,2))
         ELSE NULL END AS CONLAINGOAIBANG,
    CASE WHEN DUNONOIBANG IS NULL OR DUNONOIBANG = '' THEN NULL
         WHEN ISNUMERIC(REPLACE(REPLACE(DUNONOIBANG, ',', ''), '.', '')) = 1 THEN TRY_CAST(REPLACE(DUNONOIBANG, ',', '') AS DECIMAL(18,2))
         ELSE NULL END AS DUNONOIBANG,
    NHOMNO, MACBTD, TENCBTD, MAPGD, TAIKHOANHACHTOAN, REFNO, LOAINGUONVON,
    Id, CREATED_DATE, UPDATED_DATE, FILE_NAME
FROM LN03;

-- Tắt tạm thời bảng thời gian
ALTER TABLE LN03 SET (SYSTEM_VERSIONING = OFF);

-- Xóa bảng lịch sử (sẽ được tạo lại tự động)
DECLARE @historyTableName NVARCHAR(100) = QUOTENAME(SCHEMA_NAME(SCHEMA_ID('dbo'))) + '.' + QUOTENAME('LN03History');
DECLARE @sql NVARCHAR(MAX) = N'DROP TABLE ' + @historyTableName;
EXEC sp_executesql @sql;

-- Thay đổi cấu trúc bảng chính
ALTER TABLE LN03 ALTER COLUMN SOTIENXLRR DECIMAL(18,2) NULL;
ALTER TABLE LN03 ALTER COLUMN NGAYPHATSINHXL DATETIME2 NULL;
ALTER TABLE LN03 ALTER COLUMN THUNOSAUXL DECIMAL(18,2) NULL;
ALTER TABLE LN03 ALTER COLUMN CONLAINGOAIBANG DECIMAL(18,2) NULL;
ALTER TABLE LN03 ALTER COLUMN DUNONOIBANG DECIMAL(18,2) NULL;

-- Xóa dữ liệu cũ
TRUNCATE TABLE LN03;

-- Chèn lại dữ liệu từ bảng tạm
INSERT INTO LN03 (
    NGAY_DL, MACHINHANH, TENCHINHANH, MAKH, TENKH, SOHOPDONG,
    SOTIENXLRR, NGAYPHATSINHXL, THUNOSAUXL, CONLAINGOAIBANG, DUNONOIBANG,
    NHOMNO, MACBTD, TENCBTD, MAPGD, TAIKHOANHACHTOAN, REFNO, LOAINGUONVON,
    Id, CREATED_DATE, UPDATED_DATE, FILE_NAME
)
SELECT 
    NGAY_DL, MACHINHANH, TENCHINHANH, MAKH, TENKH, SOHOPDONG,
    SOTIENXLRR, NGAYPHATSINHXL, THUNOSAUXL, CONLAINGOAIBANG, DUNONOIBANG,
    NHOMNO, MACBTD, TENCBTD, MAPGD, TAIKHOANHACHTOAN, REFNO, LOAINGUONVON,
    Id, CREATED_DATE, UPDATED_DATE, FILE_NAME
FROM #TempLN03;

-- Bật lại bảng thời gian
ALTER TABLE LN03 ADD
    ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL CONSTRAINT DF_LN03_ValidFrom DEFAULT SYSUTCDATETIME(),
    ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL CONSTRAINT DF_LN03_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);

ALTER TABLE LN03 SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LN03History));

-- Tạo lại chỉ mục Columnstore (nếu tồn tại trước đó)
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LN03_Columnstore' AND object_id = OBJECT_ID('LN03'))
BEGIN
    CREATE CLUSTERED COLUMNSTORE INDEX IX_LN03_Columnstore ON LN03;
END

-- Xóa bảng tạm
DROP TABLE #TempLN03;

PRINT 'Đã hoàn thành cập nhật kiểu dữ liệu cho bảng LN03';
