-- ========================================================================
-- FIX LN01 TABLE STRUCTURE - CORRECTED TEMPORAL DEFINITION
-- ========================================================================

USE TinhKhoanDB;
GO

-- Bước 1: Backup dữ liệu nếu có
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'LN01')
BEGIN
    SELECT * INTO LN01_BACKUP_20250808_V2 FROM LN01;
    PRINT 'Backup created';
END
GO

-- Bước 2: Clean up completely
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'LN01' AND temporal_type = 2)
BEGIN
    ALTER TABLE LN01 SET (SYSTEM_VERSIONING = OFF);
END

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'LN01_History')
    DROP TABLE LN01_History;

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'LN01')
    DROP TABLE LN01;

PRINT 'Cleaned up existing tables';
GO

-- Bước 3: Tạo bảng LN01 với temporal definition đúng
CREATE TABLE LN01 (
    -- System Column đầu tiên - NGAY_DL (position 1)
    NGAY_DL datetime2 NOT NULL DEFAULT GETDATE(),

    -- 79 Business Columns theo thứ tự CSV (positions 2-80)
    BRCD nvarchar(200) NULL,
    CUSTSEQ nvarchar(200) NULL,
    CUSTNM nvarchar(200) NULL,
    TAI_KHOAN nvarchar(200) NULL,
    CCY nvarchar(200) NULL,
    DU_NO decimal(18,2) NULL,
    DSBSSEQ nvarchar(200) NULL,
    TRANSACTION_DATE datetime2 NULL,
    DSBSDT datetime2 NULL,
    DISBUR_CCY nvarchar(200) NULL,
    DISBURSEMENT_AMOUNT decimal(18,2) NULL,
    DSBSMATDT datetime2 NULL,
    BSRTCD nvarchar(200) NULL,
    INTEREST_RATE decimal(18,2) NULL,
    APPRSEQ nvarchar(200) NULL,
    APPRDT datetime2 NULL,
    APPR_CCY nvarchar(200) NULL,
    APPRAMT decimal(18,2) NULL,
    APPRMATDT datetime2 NULL,
    LOAN_TYPE nvarchar(200) NULL,
    FUND_RESOURCE_CODE nvarchar(200) NULL,
    FUND_PURPOSE_CODE nvarchar(200) NULL,
    REPAYMENT_AMOUNT decimal(18,2) NULL,
    NEXT_REPAY_DATE datetime2 NULL,
    NEXT_REPAY_AMOUNT decimal(18,2) NULL,
    NEXT_INT_REPAY_DATE datetime2 NULL,
    OFFICER_ID nvarchar(200) NULL,
    OFFICER_NAME nvarchar(200) NULL,
    INTEREST_AMOUNT decimal(18,2) NULL,
    PASTDUE_INTEREST_AMOUNT decimal(18,2) NULL,
    TOTAL_INTEREST_REPAY_AMOUNT decimal(18,2) NULL,
    CUSTOMER_TYPE_CODE nvarchar(200) NULL,
    CUSTOMER_TYPE_CODE_DETAIL nvarchar(200) NULL,
    TRCTCD nvarchar(200) NULL,
    TRCTNM nvarchar(200) NULL,
    ADDR1 nvarchar(200) NULL,
    PROVINCE nvarchar(200) NULL,
    LCLPROVINNM nvarchar(200) NULL,
    DISTRICT nvarchar(200) NULL,
    LCLDISTNM nvarchar(200) NULL,
    COMMCD nvarchar(200) NULL,
    LCLWARDNM nvarchar(200) NULL,
    LAST_REPAY_DATE datetime2 NULL,
    SECURED_PERCENT nvarchar(200) NULL,
    NHOM_NO nvarchar(200) NULL,
    LAST_INT_CHARGE_DATE datetime2 NULL,
    EXEMPTINT nvarchar(200) NULL,
    EXEMPTINTTYPE nvarchar(200) NULL,
    EXEMPTINTAMT decimal(18,2) NULL,
    GRPNO nvarchar(200) NULL,
    BUSCD nvarchar(200) NULL,
    BSNSSCLTPCD nvarchar(200) NULL,
    USRIDOP nvarchar(200) NULL,
    ACCRUAL_AMOUNT decimal(18,2) NULL,
    ACCRUAL_AMOUNT_END_OF_MONTH decimal(18,2) NULL,
    INTCMTH nvarchar(200) NULL,
    INTRPYMTH nvarchar(200) NULL,
    INTTRMMTH nvarchar(200) NULL,
    YRDAYS nvarchar(200) NULL,
    REMARK nvarchar(1000) NULL,
    CHITIEU nvarchar(200) NULL,
    CTCV nvarchar(200) NULL,
    CREDIT_LINE_YPE nvarchar(200) NULL,
    INT_LUMPSUM_PARTIAL_TYPE nvarchar(200) NULL,
    INT_PARTIAL_PAYMENT_TYPE nvarchar(200) NULL,
    INT_PAYMENT_INTERVAL nvarchar(200) NULL,
    AN_HAN_LAI nvarchar(200) NULL,
    PHUONG_THUC_GIAI_NGAN_1 nvarchar(200) NULL,
    TAI_KHOAN_GIAI_NGAN_1 nvarchar(200) NULL,
    SO_TIEN_GIAI_NGAN_1 decimal(18,2) NULL,
    PHUONG_THUC_GIAI_NGAN_2 nvarchar(200) NULL,
    TAI_KHOAN_GIAI_NGAN_2 nvarchar(200) NULL,
    SO_TIEN_GIAI_NGAN_2 decimal(18,2) NULL,
    CMT_HC nvarchar(200) NULL,
    NGAY_SINH datetime2 NULL,
    MA_CB_AGRI nvarchar(200) NULL,
    MA_NGANH_KT nvarchar(200) NULL,
    TY_GIA decimal(18,2) NULL,
    OFFICER_IPCAS nvarchar(200) NULL,

    -- System Columns (positions 81-85) - CORRECTED TEMPORAL
    Id bigint IDENTITY(1,1) NOT NULL,
    FILE_NAME nvarchar(255) NULL,
    CREATED_DATE datetime2 NULL DEFAULT GETDATE(),

    -- Temporal columns - FIXED DEFINITION
    ValidFrom datetime2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
    ValidTo datetime2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,

    -- Constraints
    CONSTRAINT PK_LN01 PRIMARY KEY (Id),
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LN01_History));

PRINT 'Created LN01 table with CORRECTED temporal definition ✅';
GO

-- Bước 4: Tạo columnstore indexes
CREATE NONCLUSTERED COLUMNSTORE INDEX IX_LN01_Columnstore ON LN01 (
    NGAY_DL, BRCD, CUSTSEQ, CUSTNM, TAI_KHOAN, CCY, DU_NO, DSBSSEQ, TRANSACTION_DATE, DSBSDT,
    DISBUR_CCY, DISBURSEMENT_AMOUNT, DSBSMATDT, BSRTCD, INTEREST_RATE, APPRSEQ, APPRDT, APPR_CCY,
    APPRAMT, APPRMATDT, LOAN_TYPE, FUND_RESOURCE_CODE, FUND_PURPOSE_CODE, REPAYMENT_AMOUNT,
    NEXT_REPAY_DATE, NEXT_REPAY_AMOUNT, NEXT_INT_REPAY_DATE, OFFICER_ID, OFFICER_NAME, INTEREST_AMOUNT,
    PASTDUE_INTEREST_AMOUNT, TOTAL_INTEREST_REPAY_AMOUNT, CUSTOMER_TYPE_CODE, CUSTOMER_TYPE_CODE_DETAIL,
    TRCTCD, TRCTNM, ADDR1, PROVINCE, LCLPROVINNM, DISTRICT, LCLDISTNM, COMMCD, LCLWARDNM,
    LAST_REPAY_DATE, SECURED_PERCENT, NHOM_NO, LAST_INT_CHARGE_DATE, EXEMPTINT, EXEMPTINTTYPE,
    EXEMPTINTAMT, GRPNO, BUSCD, BSNSSCLTPCD, USRIDOP, ACCRUAL_AMOUNT, ACCRUAL_AMOUNT_END_OF_MONTH,
    INTCMTH, INTRPYMTH, INTTRMMTH, YRDAYS, REMARK, CHITIEU, CTCV, CREDIT_LINE_YPE,
    INT_LUMPSUM_PARTIAL_TYPE, INT_PARTIAL_PAYMENT_TYPE, INT_PAYMENT_INTERVAL, AN_HAN_LAI,
    PHUONG_THUC_GIAI_NGAN_1, TAI_KHOAN_GIAI_NGAN_1, SO_TIEN_GIAI_NGAN_1, PHUONG_THUC_GIAI_NGAN_2,
    TAI_KHOAN_GIAI_NGAN_2, SO_TIEN_GIAI_NGAN_2, CMT_HC, NGAY_SINH, MA_CB_AGRI, MA_NGANH_KT,
    TY_GIA, OFFICER_IPCAS, FILE_NAME, CREATED_DATE
);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_LN01_History_Columnstore ON LN01_History (
    NGAY_DL, BRCD, CUSTSEQ, CUSTNM, TAI_KHOAN, CCY, DU_NO, DSBSSEQ, TRANSACTION_DATE, DSBSDT,
    DISBUR_CCY, DISBURSEMENT_AMOUNT, DSBSMATDT, BSRTCD, INTEREST_RATE, APPRSEQ, APPRDT, APPR_CCY,
    APPRAMT, APPRMATDT, LOAN_TYPE, FUND_RESOURCE_CODE, FUND_PURPOSE_CODE, REPAYMENT_AMOUNT,
    NEXT_REPAY_DATE, NEXT_REPAY_AMOUNT, NEXT_INT_REPAY_DATE, OFFICER_ID, OFFICER_NAME, INTEREST_AMOUNT,
    PASTDUE_INTEREST_AMOUNT, TOTAL_INTEREST_REPAY_AMOUNT, CUSTOMER_TYPE_CODE, CUSTOMER_TYPE_CODE_DETAIL,
    TRCTCD, TRCTNM, ADDR1, PROVINCE, LCLPROVINNM, DISTRICT, LCLDISTNM, COMMCD, LCLWARDNM,
    LAST_REPAY_DATE, SECURED_PERCENT, NHOM_NO, LAST_INT_CHARGE_DATE, EXEMPTINT, EXEMPTINTTYPE,
    EXEMPTINTAMT, GRPNO, BUSCD, BSNSSCLTPCD, USRIDOP, ACCRUAL_AMOUNT, ACCRUAL_AMOUNT_END_OF_MONTH,
    INTCMTH, INTRPYMTH, INTTRMMTH, YRDAYS, REMARK, CHITIEU, CTCV, CREDIT_LINE_YPE,
    INT_LUMPSUM_PARTIAL_TYPE, INT_PARTIAL_PAYMENT_TYPE, INT_PAYMENT_INTERVAL, AN_HAN_LAI,
    PHUONG_THUC_GIAI_NGAN_1, TAI_KHOAN_GIAI_NGAN_1, SO_TIEN_GIAI_NGAN_1, PHUONG_THUC_GIAI_NGAN_2,
    TAI_KHOAN_GIAI_NGAN_2, SO_TIEN_GIAI_NGAN_2, CMT_HC, NGAY_SINH, MA_CB_AGRI, MA_NGANH_KT,
    TY_GIA, OFFICER_IPCAS, FILE_NAME, CREATED_DATE, ValidFrom, ValidTo
);

PRINT 'Created columnstore indexes successfully ✅';
GO

-- Final verification
SELECT '=== FINAL VERIFICATION ===' as Status;

SELECT
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    CASE
        WHEN ORDINAL_POSITION = 1 AND COLUMN_NAME = 'NGAY_DL' THEN '✅ CORRECT'
        WHEN ORDINAL_POSITION BETWEEN 2 AND 80 THEN '✅ BUSINESS'
        WHEN ORDINAL_POSITION > 80 THEN '✅ SYSTEM'
        ELSE '❌ WRONG'
    END as Status
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'LN01'
ORDER BY ORDINAL_POSITION;

SELECT
    COUNT(*) as BusinessColumns,
    CASE
        WHEN COUNT(*) = 79 THEN '✅ PERFECT MATCH WITH CSV'
        ELSE '❌ WRONG COUNT'
    END as Result
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'LN01'
AND COLUMN_NAME NOT IN ('NGAY_DL', 'Id', 'FILE_NAME', 'CREATED_DATE', 'ValidFrom', 'ValidTo');

PRINT '';
PRINT '🎉 LN01 FIX COMPLETED SUCCESSFULLY! 🎉';
PRINT '✅ NGAY_DL at position 1';
PRINT '✅ 79 business columns in CSV order';
PRINT '✅ UPDATED_DATE removed (extra column)';
PRINT '✅ System columns properly positioned';
PRINT '✅ Temporal table with history tracking';
PRINT '✅ Columnstore indexes for performance';
PRINT '';
PRINT 'All issues resolved - 100% compliant!';
GO
