-- ================================================================
-- REBUILD 8 CORE DATATABLES - TÔN TRỌNG CSV GỐC
-- Thứ tự: NGAY_DL + Business Columns (CSV gốc) + System/Temporal Columns
-- ================================================================

USE TinhKhoanDB;
GO

-- ================================================================
-- 1. DROP TẤT CẢ TABLES (Temporal + History)
-- ================================================================
PRINT 'Dropping all existing tables and history tables...';

IF OBJECT_ID('DP01', 'U') IS NOT NULL
BEGIN
    ALTER TABLE DP01 SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS DP01_History;
    DROP TABLE IF EXISTS DP01;
END

IF OBJECT_ID('EI01', 'U') IS NOT NULL
BEGIN
    ALTER TABLE EI01 SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS EI01_History;
    DROP TABLE IF EXISTS EI01;
END

IF OBJECT_ID('GL01', 'U') IS NOT NULL
    DROP TABLE IF EXISTS GL01;

IF OBJECT_ID('GL41', 'U') IS NOT NULL
BEGIN
    ALTER TABLE GL41 SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS GL41_History;
    DROP TABLE IF EXISTS GL41;
END

IF OBJECT_ID('LN01', 'U') IS NOT NULL
BEGIN
    ALTER TABLE LN01 SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS LN01_History;
    DROP TABLE IF EXISTS LN01;
END

IF OBJECT_ID('LN03', 'U') IS NOT NULL
BEGIN
    ALTER TABLE LN03 SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS LN03_History;
    DROP TABLE IF EXISTS LN03;
END

IF OBJECT_ID('RR01', 'U') IS NOT NULL
BEGIN
    ALTER TABLE RR01 SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS RR01_History;
    DROP TABLE IF EXISTS RR01;
END

IF OBJECT_ID('DPDA', 'U') IS NOT NULL
BEGIN
    ALTER TABLE DPDA SET (SYSTEM_VERSIONING = OFF);
    DROP TABLE IF EXISTS DPDA_History;
    DROP TABLE IF EXISTS DPDA;
END

PRINT 'All tables dropped successfully.';
GO

-- ================================================================
-- 2. DP01 - TEMPORAL TABLE (ĐÚNG THỨ TỰ: NGAY_DL + 63 Business + System/Temporal)
-- ================================================================
PRINT 'Creating DP01 table with correct column order...';
CREATE TABLE DP01 (
    -- System column FIRST (theo yêu cầu user)
    NGAY_DL DATETIME NOT NULL,

    -- 63 Business columns từ CSV DP01 (exact order from DuLieuMau)
    MA_CN NVARCHAR(50),
    TAI_KHOAN_HACH_TOAN NVARCHAR(50),
    MA_KH NVARCHAR(50),
    TEN_KH NVARCHAR(255),
    DP_TYPE_NAME NVARCHAR(100),
    CCY NVARCHAR(10),
    CURRENT_BALANCE DECIMAL(18,2),
    RATE DECIMAL(10,4),
    SO_TAI_KHOAN NVARCHAR(50),
    OPENING_DATE DATETIME,
    MATURITY_DATE DATETIME,
    ADDRESS NVARCHAR(500),
    NOTENO NVARCHAR(50),
    MONTH_TERM INT,
    TERM_DP_NAME NVARCHAR(100),
    TIME_DP_NAME NVARCHAR(100),
    MA_PGD NVARCHAR(50),
    TEN_PGD NVARCHAR(255),
    DP_TYPE_CODE NVARCHAR(50),
    RENEW_DATE DATETIME,
    CUST_TYPE NVARCHAR(50),
    CUST_TYPE_NAME NVARCHAR(100),
    CUST_TYPE_DETAIL NVARCHAR(50),
    CUST_DETAIL_NAME NVARCHAR(100),
    PREVIOUS_DP_CAP_DATE DATETIME,
    NEXT_DP_CAP_DATE DATETIME,
    ID_NUMBER NVARCHAR(50),
    ISSUED_BY NVARCHAR(255),
    ISSUE_DATE DATETIME,
    SEX_TYPE NVARCHAR(10),
    BIRTH_DATE DATETIME,
    TELEPHONE NVARCHAR(50),
    ACRUAL_AMOUNT DECIMAL(18,2),
    ACRUAL_AMOUNT_END DECIMAL(18,2),
    ACCOUNT_STATUS NVARCHAR(50),
    DRAMT DECIMAL(18,2),
    CRAMT DECIMAL(18,2),
    EMPLOYEE_NUMBER NVARCHAR(50),
    EMPLOYEE_NAME NVARCHAR(255),
    SPECIAL_RATE DECIMAL(10,4),
    AUTO_RENEWAL NVARCHAR(10),
    CLOSE_DATE DATETIME,
    LOCAL_PROVIN_NAME NVARCHAR(100),
    LOCAL_DISTRICT_NAME NVARCHAR(100),
    LOCAL_WARD_NAME NVARCHAR(100),
    TERM_DP_TYPE NVARCHAR(50),
    TIME_DP_TYPE NVARCHAR(50),
    STATES_CODE NVARCHAR(50),
    ZIP_CODE NVARCHAR(20),
    COUNTRY_CODE NVARCHAR(10),
    TAX_CODE_LOCATION NVARCHAR(50),
    MA_CAN_BO_PT NVARCHAR(50),
    TEN_CAN_BO_PT NVARCHAR(255),
    PHONG_CAN_BO_PT NVARCHAR(100),
    NGUOI_NUOC_NGOAI NVARCHAR(10),
    QUOC_TICH NVARCHAR(50),
    MA_CAN_BO_AGRIBANK NVARCHAR(50),
    NGUOI_GIOI_THIEU NVARCHAR(50),
    TEN_NGUOI_GIOI_THIEU NVARCHAR(255),
    CONTRACT_COUTS_DAY INT,
    SO_KY_AD_LSDB NVARCHAR(50),
    UNTBUSCD NVARCHAR(50),
    TYGIA DECIMAL(10,4),

    -- System/Temporal columns LAST (theo yêu cầu user)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    FILE_NAME NVARCHAR(255),
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.DP01_History));
PRINT '✅ DP01 created with correct CSV column order.';
GO

-- ================================================================
-- 3. LN01 - TEMPORAL TABLE (ĐÚNG THỨ TỰ: NGAY_DL + 79 Business + System/Temporal)
-- ================================================================
PRINT 'Creating LN01 table with correct column order...';
CREATE TABLE LN01 (
    -- System column FIRST
    NGAY_DL DATETIME NOT NULL,

    -- 79 Business columns từ CSV LN01 (exact order from file 7808_ln01_20241231.csv)
    BRCD NVARCHAR(50),
    CUSTSEQ NVARCHAR(100),
    CUSTNM NVARCHAR(500),
    TAI_KHOAN NVARCHAR(100),
    CCY NVARCHAR(10),
    DU_NO DECIMAL(18,2),
    DSBSSEQ NVARCHAR(100),
    TRANSACTION_DATE DATETIME,
    DSBSDT DATETIME,
    DISBUR_CCY NVARCHAR(10),
    DISBURSEMENT_AMOUNT DECIMAL(18,2),
    DSBSMATDT DATETIME,
    BSRTCD NVARCHAR(50),
    INTEREST_RATE DECIMAL(10,4),
    APPRSEQ NVARCHAR(100),
    APPRDT DATETIME,
    APPR_CCY NVARCHAR(10),
    APPRAMT DECIMAL(18,2),
    APPRMATDT DATETIME,
    LOAN_TYPE NVARCHAR(100),
    FUND_RESOURCE_CODE NVARCHAR(50),
    FUND_PURPOSE_CODE NVARCHAR(50),
    REPAYMENT_AMOUNT DECIMAL(18,2),
    NEXT_REPAY_DATE DATETIME,
    NEXT_REPAY_AMOUNT DECIMAL(18,2),
    NEXT_INT_REPAY_DATE DATETIME,
    OFFICER_ID NVARCHAR(50),
    OFFICER_NAME NVARCHAR(255),
    INTEREST_AMOUNT DECIMAL(18,2),
    PASTDUE_INTEREST_AMOUNT DECIMAL(18,2),
    TOTAL_INTEREST_REPAY_AMOUNT DECIMAL(18,2),
    CUSTOMER_TYPE_CODE NVARCHAR(50),
    CUSTOMER_TYPE_CODE_DETAIL NVARCHAR(100),
    TRCTCD NVARCHAR(50),
    TRCTNM NVARCHAR(255),
    ADDR1 NVARCHAR(500),
    PROVINCE NVARCHAR(100),
    LCLPROVINNM NVARCHAR(100),
    DISTRICT NVARCHAR(100),
    LCLDISTNM NVARCHAR(100),
    COMMCD NVARCHAR(50),
    LCLWARDNM NVARCHAR(100),
    LAST_REPAY_DATE DATETIME,
    SECURED_PERCENT DECIMAL(10,4),
    NHOM_NO INT,
    LAST_INT_CHARGE_DATE DATETIME,
    EXEMPTINT DECIMAL(18,2),
    EXEMPTINTTYPE NVARCHAR(50),
    EXEMPTINTAMT DECIMAL(18,2),
    GRPNO INT,
    BUSCD NVARCHAR(50),
    BUSNM NVARCHAR(255),
    ACCRINTBASE INT,
    RATECD NVARCHAR(50),
    RLSCD NVARCHAR(50),
    RLSNM NVARCHAR(255),
    INTERESTTYPE NVARCHAR(50),
    FEETYPE NVARCHAR(50),
    CURRENCYTYPE NVARCHAR(10),
    LOANSTATUS NVARCHAR(50),
    MATURITYTYPE NVARCHAR(50),
    REPAYTYPE NVARCHAR(50),
    COLLATERALTYPE NVARCHAR(100),
    CREDITLIMIT DECIMAL(18,2),
    AVAILABLELIMIT DECIMAL(18,2),
    LOANORIGINALAMT DECIMAL(18,2),
    DOWNPAYMENT DECIMAL(18,2),
    INSTALMENTAMT DECIMAL(18,2),
    TOTALPAIDAMT DECIMAL(18,2),
    CHARGEOFFAMT DECIMAL(18,2),
    WRITEOFFAMT DECIMAL(18,2),
    RESERVEAMT DECIMAL(18,2),
    ACCRUALBALANCE DECIMAL(18,2),
    OUTSRC NVARCHAR(50),
    ORIGINAL_TRANS_ID NVARCHAR(100),
    CREATED_DATE_CSV DATETIME,
    UPDATED_DATE_CSV DATETIME,

    -- System/Temporal columns LAST
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    FILE_NAME NVARCHAR(255),
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LN01_History));
PRINT '✅ LN01 created with correct CSV column order.';
GO

-- ================================================================
-- 4. EI01 - TEMPORAL TABLE (ĐÚNG THỨ TỰ: NGAY_DL + 24 Business + System/Temporal)
-- ================================================================
PRINT 'Creating EI01 table with correct column order...';
CREATE TABLE EI01 (
    -- System column FIRST
    NGAY_DL DATETIME NOT NULL,

    -- 24 Business columns từ CSV EI01 (exact order)
    MA_CN NVARCHAR(50),
    MA_KH NVARCHAR(50),
    TEN_KH NVARCHAR(255),
    LOAI_KH NVARCHAR(50),
    SDT_EMB NVARCHAR(50),
    TRANG_THAI_EMB NVARCHAR(50),
    NGAY_DK_EMB DATETIME,
    SDT_OTT NVARCHAR(50),
    TRANG_THAI_OTT NVARCHAR(50),
    NGAY_DK_OTT DATETIME,
    SDT_SMS NVARCHAR(50),
    TRANG_THAI_SMS NVARCHAR(50),
    NGAY_DK_SMS DATETIME,
    SDT_SAV NVARCHAR(50),
    TRANG_THAI_SAV NVARCHAR(50),
    NGAY_DK_SAV DATETIME,
    SDT_LN NVARCHAR(50),
    TRANG_THAI_LN NVARCHAR(50),
    NGAY_DK_LN DATETIME,
    USER_EMB NVARCHAR(50),
    USER_OTT NVARCHAR(50),
    USER_SMS NVARCHAR(50),
    USER_SAV NVARCHAR(50),
    USER_LN NVARCHAR(50),

    -- System/Temporal columns LAST
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    FILE_NAME NVARCHAR(255),
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.EI01_History));
PRINT '✅ EI01 created with correct CSV column order.';
GO

-- ================================================================
-- 5. GL01 - NON-TEMPORAL TABLE (ĐÚNG THỨ TỰ: NGAY_DL từ TR_TIME + 27 Business + System)
-- ================================================================
PRINT 'Creating GL01 table (NON-TEMPORAL) with correct column order...';
CREATE TABLE GL01 (
    -- System column FIRST (NGAY_DL lấy từ TR_TIME column)
    NGAY_DL DATETIME NOT NULL,

    -- 27 Business columns từ CSV GL01 (exact order)
    STS NVARCHAR(50),
    NGAY_GD DATETIME,
    NGUOI_TAO NVARCHAR(50),
    DYSEQ BIGINT,
    TR_TYPE NVARCHAR(50),
    DT_SEQ BIGINT,
    TAI_KHOAN NVARCHAR(50),
    TEN_TK NVARCHAR(255),
    SO_TIEN_GD DECIMAL(18,2),
    POST_BR NVARCHAR(50),
    LOAI_TIEN NVARCHAR(10),
    DR_CR NVARCHAR(10),
    MA_KH NVARCHAR(50),
    TEN_KH NVARCHAR(255),
    CCA_USRID NVARCHAR(50),
    TR_EX_RT DECIMAL(10,4),
    REMARK NVARCHAR(500),
    BUS_CODE NVARCHAR(50),
    UNIT_BUS_CODE NVARCHAR(50),
    TR_CODE NVARCHAR(50),
    TR_NAME NVARCHAR(255),
    REFERENCE NVARCHAR(255),
    VALUE_DATE DATETIME,
    DEPT_CODE NVARCHAR(50),
    TR_TIME DATETIME, -- Column từ CSV - source cho NGAY_DL
    COMFIRM NVARCHAR(50),
    TRDT_TIME DATETIME,

    -- System columns LAST (NO temporal for GL01)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    FILE_NAME NVARCHAR(255),
    CREATED_DATE DATETIME2 DEFAULT GETDATE(),
    UPDATED_DATE DATETIME2 DEFAULT GETDATE()
);
PRINT '✅ GL01 created (NON-TEMPORAL) with correct CSV column order.';
GO

-- ================================================================
-- 6. GL41 - TEMPORAL TABLE (ĐÚNG THỨ TỰ: NGAY_DL + 13 Business + System/Temporal)
-- ================================================================
PRINT 'Creating GL41 table with correct column order...';
CREATE TABLE GL41 (
    -- System column FIRST
    NGAY_DL DATETIME NOT NULL,

    -- 13 Business columns từ CSV GL41 (exact order)
    MA_CN NVARCHAR(50),
    LOAI_TIEN NVARCHAR(10),
    MA_TK NVARCHAR(50),
    TEN_TK NVARCHAR(255),
    LOAI_BT NVARCHAR(50),
    DN_DAUKY DECIMAL(18,2),
    DC_DAUKY DECIMAL(18,2),
    SBT_NO INT,
    ST_GHINO DECIMAL(18,2),
    SBT_CO INT,
    ST_GHICO DECIMAL(18,2),
    DN_CUOIKY DECIMAL(18,2),
    DC_CUOIKY DECIMAL(18,2),

    -- System/Temporal columns LAST
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    FILE_NAME NVARCHAR(255),
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.GL41_History));
PRINT '✅ GL41 created with correct CSV column order.';
GO

-- ================================================================
-- 7. LN03 - TEMPORAL TABLE (ĐÚNG THỨ TỰ: NGAY_DL + 17 Business + System/Temporal)
-- ================================================================
PRINT 'Creating LN03 table with correct column order...';
CREATE TABLE LN03 (
    -- System column FIRST
    NGAY_DL DATETIME NOT NULL,

    -- 17 Business columns từ CSV LN03 (exact order)
    MACHINHANH NVARCHAR(50),
    TENCHINHANH NVARCHAR(255),
    MAKH NVARCHAR(50),
    TENKH NVARCHAR(255),
    SOTIENXLRR DECIMAL(18,2),
    DUNONOIBANG DECIMAL(18,2),
    DUNONGOAIBANG DECIMAL(18,2),
    THUNOSAUXL DECIMAL(18,2),
    CONLAINGOAIBANG DECIMAL(18,2),
    NHOMNO INT,
    MACBTD NVARCHAR(50),
    TENCBTD NVARCHAR(255),
    MAPGD NVARCHAR(50),
    TAIKHOANHACHTOAN NVARCHAR(50),
    REFNO NVARCHAR(100),
    LOAINGUONVON NVARCHAR(100),
    GHICHU NVARCHAR(500),

    -- System/Temporal columns LAST
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    FILE_NAME NVARCHAR(255),
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LN03_History));
PRINT '✅ LN03 created with correct CSV column order.';
GO

-- ================================================================
-- 8. RR01 - TEMPORAL TABLE (ĐÚNG THỨ TỰ: NGAY_DL + 25 Business + System/Temporal)
-- ================================================================
PRINT 'Creating RR01 table with correct column order...';
CREATE TABLE RR01 (
    -- System column FIRST
    NGAY_DL DATETIME NOT NULL,

    -- 25 Business columns từ CSV RR01 (exact order)
    CN_LOAI_I NVARCHAR(50),
    BRCD NVARCHAR(50),
    MA_KH NVARCHAR(50),
    TEN_KH NVARCHAR(255),
    SO_LDS NVARCHAR(50),
    CCY NVARCHAR(10),
    SO_LAV NVARCHAR(50),
    LOAI_KH NVARCHAR(50),
    NGAY_GIAI_NGAN DATETIME,
    NGAY_DEN_HAN DATETIME,
    VAMC_FLG NVARCHAR(10),
    NGAY_XLRR DATETIME,
    DUNO_GOC_BAN_DAU DECIMAL(18,2),
    DUNO_LAI_TICHLUY_BD DECIMAL(18,2),
    DUNO_PHI_TICHLUY_BD DECIMAL(18,2),
    DUNO_GOC_HIENTAI DECIMAL(18,2),
    DUNO_LAI_HIENTAI DECIMAL(18,2),
    DUNO_PHI_HIENTAI DECIMAL(18,2),
    SOTIENXLRR DECIMAL(18,2),
    TONG_DUNO_TRUOCXL DECIMAL(18,2),
    TONG_DUNO_SAUXL DECIMAL(18,2),
    DUNOTAMUNG DECIMAL(18,2),
    SO_NGAY_QH INT,
    NHOM_NO_TRUOC_XL INT,
    NHOM_NO_SAU_XL INT,

    -- System/Temporal columns LAST
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    FILE_NAME NVARCHAR(255),
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RR01_History));
PRINT '✅ RR01 created with correct CSV column order.';
GO

-- ================================================================
-- 9. DPDA - TEMPORAL TABLE (ĐÚNG THỨ TỰ: NGAY_DL + 13 Business + System/Temporal)
-- ================================================================
PRINT 'Creating DPDA table with correct column order...';
CREATE TABLE DPDA (
    -- System column FIRST
    NGAY_DL DATETIME NOT NULL,

    -- 13 Business columns từ CSV DPDA (exact order)
    MA_CHI_NHANH NVARCHAR(50),
    MA_KHACH_HANG NVARCHAR(50),
    TEN_KHACH_HANG NVARCHAR(255),
    SO_TAI_KHOAN NVARCHAR(50),
    LOAI_THE NVARCHAR(50),
    TRANG_THAI NVARCHAR(50),
    NGAY_PHAT_HANH DATETIME,
    NGAY_HET_HAN DATETIME,
    SO_DU_HIEN_TAI DECIMAL(18,2),
    HAN_MUC_THE DECIMAL(18,2),
    SO_GIAO_DICH_TRONG_THANG INT,
    SO_TIEN_GIAO_DICH_TRONG_THANG DECIMAL(18,2),
    PHI_DICH_VU_THANG DECIMAL(18,2),

    -- System/Temporal columns LAST
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    FILE_NAME NVARCHAR(255),
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.DPDA_History));
PRINT '✅ DPDA created with correct CSV column order.';
GO

-- ================================================================
-- 10. TẠO COLUMNSTORE INDEXES (Performance optimization)
-- ================================================================
PRINT 'Creating columnstore indexes for performance...';

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_DP01_Columnstore ON DP01
(NGAY_DL, MA_CN, TAI_KHOAN_HACH_TOAN, MA_KH, TEN_KH, CURRENT_BALANCE);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_LN01_Columnstore ON LN01
(NGAY_DL, BRCD, CUSTSEQ, CUSTNM, TAI_KHOAN, CCY, DU_NO, INTEREST_RATE);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_EI01_Columnstore ON EI01
(NGAY_DL, MA_CN, MA_KH, TEN_KH, LOAI_KH);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_GL01_Columnstore ON GL01
(NGAY_DL, STS, TAI_KHOAN, TEN_TK, SO_TIEN_GD, LOAI_TIEN, MA_KH, TEN_KH);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_GL41_Columnstore ON GL41
(NGAY_DL, MA_CN, LOAI_TIEN, MA_TK, TEN_TK, DN_CUOIKY, DC_CUOIKY);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_LN03_Columnstore ON LN03
(NGAY_DL, MACHINHANH, TENCHINHANH, MAKH, TENKH, SOTIENXLRR, DUNONOIBANG);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_RR01_Columnstore ON RR01
(NGAY_DL, CN_LOAI_I, BRCD, MA_KH, TEN_KH, DUNO_GOC_HIENTAI, DUNO_LAI_HIENTAI);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_DPDA_Columnstore ON DPDA
(NGAY_DL, MA_CHI_NHANH, MA_KHACH_HANG, TEN_KHACH_HANG, SO_TAI_KHOAN, LOAI_THE);

PRINT '✅ All columnstore indexes created successfully.';
GO

-- ================================================================
-- 11. VERIFICATION - Check table structures
-- ================================================================
PRINT '📊 VERIFICATION: Checking all 8 tables structure...';

SELECT
    TABLE_NAME,
    COUNT(*) as ColumnCount,
    STRING_AGG(COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) as ColumnOrder
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('DP01', 'LN01', 'EI01', 'GL01', 'GL41', 'LN03', 'RR01', 'DPDA')
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;

PRINT '🎯 SUCCESS: All 8 core datatables rebuilt with correct CSV column structure!';
PRINT 'Structure: NGAY_DL + Business Columns (CSV order) + System/Temporal Columns';
GO
