-- Script rebuild 8 bảng dữ liệu với cấu trúc cột business ở đầu, system/temporal ở cuối
-- NGAY_DL cho GL01 lấy từ TR_TIME (column 25), các bảng khác lấy từ filename

USE TinhKhoanDB;
GO

-- Disable temporal tables trước khi rebuild
DECLARE @sql NVARCHAR(MAX) = '';
SELECT @sql = @sql + 'ALTER TABLE ' + t.name + ' SET (SYSTEM_VERSIONING = OFF);' + CHAR(13) + CHAR(10)
FROM sys.tables t
INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
WHERE t.temporal_type = 2  -- SYSTEM_VERSIONED_TEMPORAL_TABLE
  AND t.name IN ('DP01', 'EI01', 'GL01', 'GL41', 'LN01', 'LN03', 'RR01', 'DPDA');

IF LEN(@sql) > 0
BEGIN
    PRINT 'Disabling temporal tables...';
    EXEC sp_executesql @sql;
END;
GO

-- Drop các bảng hiện tại và history tables
DROP TABLE IF EXISTS DP01_History;
DROP TABLE IF EXISTS DP01;

DROP TABLE IF EXISTS EI01_History;
DROP TABLE IF EXISTS EI01;

DROP TABLE IF EXISTS GL01_History;
DROP TABLE IF EXISTS GL01;

DROP TABLE IF EXISTS GL41_History;
DROP TABLE IF EXISTS GL41;

DROP TABLE IF EXISTS LN01_History;
DROP TABLE IF EXISTS LN01;

DROP TABLE IF EXISTS LN03_History;
DROP TABLE IF EXISTS LN03;

DROP TABLE IF EXISTS RR01_History;
DROP TABLE IF EXISTS RR01;

DROP TABLE IF EXISTS DPDA_History;
DROP TABLE IF EXISTS DPDA;
GO

-- ================================================================
-- BẢNG 1: DP01 (63 business columns + system/temporal columns)
-- ================================================================
CREATE TABLE DP01 (
    -- Business columns từ CSV (63 cột)
    MA_CN NVARCHAR(50),
    TAI_KHOAN_HACH_TOAN NVARCHAR(50),
    MA_KH NVARCHAR(50),
    TEN_KH NVARCHAR(255),
    DP_TYPE_NAME NVARCHAR(100),
    CCY NVARCHAR(10),
    CURRENT_BALANCE DECIMAL(18,2),
    RATE DECIMAL(10,4),
    SO_TAI_KHOAN NVARCHAR(50),
    OPENING_DATE DATETIME,
    MATURITY_DATE DATETIME,
    ADDRESS NVARCHAR(500),
    NOTENO NVARCHAR(50),
    MONTH_TERM INT,
    TERM_DP_NAME NVARCHAR(100),
    TIME_DP_NAME NVARCHAR(100),
    MA_PGD NVARCHAR(50),
    TEN_PGD NVARCHAR(255),
    DP_TYPE_CODE NVARCHAR(50),
    RENEW_DATE DATETIME,
    CUST_TYPE NVARCHAR(50),
    CUST_TYPE_NAME NVARCHAR(100),
    CUST_TYPE_DETAIL NVARCHAR(50),
    CUST_DETAIL_NAME NVARCHAR(100),
    PREVIOUS_DP_CAP_DATE DATETIME,
    NEXT_DP_CAP_DATE DATETIME,
    ID_NUMBER NVARCHAR(50),
    ISSUED_BY NVARCHAR(255),
    ISSUE_DATE DATETIME,
    SEX_TYPE NVARCHAR(10),
    BIRTH_DATE DATETIME,
    TELEPHONE NVARCHAR(50),
    ACRUAL_AMOUNT DECIMAL(18,2),
    ACRUAL_AMOUNT_END DECIMAL(18,2),
    ACCOUNT_STATUS NVARCHAR(50),
    DRAMT DECIMAL(18,2),
    CRAMT DECIMAL(18,2),
    EMPLOYEE_NUMBER NVARCHAR(50),
    EMPLOYEE_NAME NVARCHAR(255),
    SPECIAL_RATE DECIMAL(10,4),
    AUTO_RENEWAL NVARCHAR(10),
    CLOSE_DATE DATETIME,
    LOCAL_PROVIN_NAME NVARCHAR(100),
    LOCAL_DISTRICT_NAME NVARCHAR(100),
    LOCAL_WARD_NAME NVARCHAR(100),
    TERM_DP_TYPE NVARCHAR(50),
    TIME_DP_TYPE NVARCHAR(50),
    STATES_CODE NVARCHAR(50),
    ZIP_CODE NVARCHAR(20),
    COUNTRY_CODE NVARCHAR(10),
    TAX_CODE_LOCATION NVARCHAR(50),
    MA_CAN_BO_PT NVARCHAR(50),
    TEN_CAN_BO_PT NVARCHAR(255),
    PHONG_CAN_BO_PT NVARCHAR(100),
    NGUOI_NUOC_NGOAI NVARCHAR(10),
    QUOC_TICH NVARCHAR(50),
    MA_CAN_BO_AGRIBANK NVARCHAR(50),
    NGUOI_GIOI_THIEU NVARCHAR(50),
    TEN_NGUOI_GIOI_THIEU NVARCHAR(255),
    CONTRACT_COUTS_DAY INT,
    SO_KY_AD_LSDB NVARCHAR(50),
    UNTBUSCD NVARCHAR(50),
    TYGIA DECIMAL(10,4),

    -- System columns (ở cuối)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL DATETIME NOT NULL,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(255),

    -- Temporal columns (ở cuối cùng)
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.DP01_History));
GO

-- ================================================================
-- BẢNG 2: EI01 (24 business columns + system/temporal columns)
-- ================================================================
CREATE TABLE EI01 (
    -- Business columns từ CSV (24 cột)
    MA_CN NVARCHAR(50),
    MA_KH NVARCHAR(50),
    TEN_KH NVARCHAR(255),
    LOAI_KH NVARCHAR(50),
    SDT_EMB NVARCHAR(50),
    TRANG_THAI_EMB NVARCHAR(50),
    NGAY_DK_EMB DATETIME,
    SDT_OTT NVARCHAR(50),
    TRANG_THAI_OTT NVARCHAR(50),
    NGAY_DK_OTT DATETIME,
    SDT_SMS NVARCHAR(50),
    TRANG_THAI_SMS NVARCHAR(50),
    NGAY_DK_SMS DATETIME,
    SDT_SAV NVARCHAR(50),
    TRANG_THAI_SAV NVARCHAR(50),
    NGAY_DK_SAV DATETIME,
    SDT_LN NVARCHAR(50),
    TRANG_THAI_LN NVARCHAR(50),
    NGAY_DK_LN DATETIME,
    USER_EMB NVARCHAR(50),
    USER_OTT NVARCHAR(50),
    USER_SMS NVARCHAR(50),
    USER_SAV NVARCHAR(50),
    USER_LN NVARCHAR(50),

    -- System columns (ở cuối)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL DATETIME NOT NULL,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(255),

    -- Temporal columns (ở cuối cùng)
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.EI01_History));
GO

-- ================================================================
-- BẢNG 3: GL01 (27 business columns + system/temporal columns)
-- SPECIAL: Partitioned Columnstore, NGAY_DL từ TR_TIME
-- ================================================================
CREATE TABLE GL01 (
    -- Business columns từ CSV (27 cột)
    STS NVARCHAR(50),
    NGAY_GD DATETIME,
    NGUOI_TAO NVARCHAR(50),
    DYSEQ BIGINT,
    TR_TYPE NVARCHAR(50),
    DT_SEQ BIGINT,
    TAI_KHOAN NVARCHAR(50),
    TEN_TK NVARCHAR(255),
    SO_TIEN_GD DECIMAL(18,2),
    POST_BR NVARCHAR(50),
    LOAI_TIEN NVARCHAR(10),
    DR_CR NVARCHAR(10),
    MA_KH NVARCHAR(50),
    TEN_KH NVARCHAR(255),
    CCA_USRID NVARCHAR(50),
    TR_EX_RT DECIMAL(10,4),
    REMARK NVARCHAR(500),
    BUS_CODE NVARCHAR(50),
    UNIT_BUS_CODE NVARCHAR(50),
    TR_CODE NVARCHAR(50),
    TR_NAME NVARCHAR(255),
    REFERENCE NVARCHAR(255),
    VALUE_DATE DATETIME,
    DEPT_CODE NVARCHAR(50),
    TR_TIME DATETIME, -- Column 25: Source cho NGAY_DL
    COMFIRM NVARCHAR(50),
    TRDT_TIME DATETIME,

    -- System columns (ở cuối)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL DATETIME NOT NULL, -- Lấy từ TR_TIME (dd/mm/yyyy format)
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(255),

    -- Temporal columns (ở cuối cùng)
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.GL01_History));
GO

-- ================================================================
-- BẢNG 4: GL41 (13 business columns + system/temporal columns)
-- ================================================================
CREATE TABLE GL41 (
    -- Business columns từ CSV (13 cột)
    MA_CN NVARCHAR(50),
    LOAI_TIEN NVARCHAR(10),
    MA_TK NVARCHAR(50),
    TEN_TK NVARCHAR(255),
    LOAI_BT NVARCHAR(50),
    DN_DAUKY DECIMAL(18,2),
    DC_DAUKY DECIMAL(18,2),
    SBT_NO INT,
    ST_GHINO DECIMAL(18,2),
    SBT_CO INT,
    ST_GHICO DECIMAL(18,2),
    DN_CUOIKY DECIMAL(18,2),
    DC_CUOIKY DECIMAL(18,2),

    -- System columns (ở cuối)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL DATETIME NOT NULL,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(255),

    -- Temporal columns (ở cuối cùng)
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.GL41_History));
GO

-- ================================================================
-- BẢNG 5: LN01 (79 business columns + system/temporal columns)
-- ================================================================
CREATE TABLE LN01 (
    -- Business columns từ CSV (79 cột)
    BRCD NVARCHAR(50),
    CUSTSEQ BIGINT,
    CUSTNM NVARCHAR(255),
    TAI_KHOAN NVARCHAR(50),
    CCY NVARCHAR(10),
    DU_NO DECIMAL(18,2),
    DSBSSEQ BIGINT,
    TRANSACTION_DATE DATETIME,
    DSBSDT DATETIME,
    DISBUR_CCY NVARCHAR(10),
    DISBURSEMENT_AMOUNT DECIMAL(18,2),
    DSBSMATDT DATETIME,
    BSRTCD NVARCHAR(50),
    INTEREST_RATE DECIMAL(10,4),
    APPRSEQ BIGINT,
    APPRDT DATETIME,
    APPR_CCY NVARCHAR(10),
    APPRAMT DECIMAL(18,2),
    APPRMATDT DATETIME,
    LOAN_TYPE NVARCHAR(50),
    FUND_RESOURCE_CODE NVARCHAR(50),
    FUND_PURPOSE_CODE NVARCHAR(50),
    REPAYMENT_AMOUNT DECIMAL(18,2),
    NEXT_REPAY_DATE DATETIME,
    NEXT_REPAY_AMOUNT DECIMAL(18,2),
    NEXT_INT_REPAY_DATE DATETIME,
    OFFICER_ID NVARCHAR(50),
    OFFICER_NAME NVARCHAR(255),
    INTEREST_AMOUNT DECIMAL(18,2),
    PASTDUE_INTEREST_AMOUNT DECIMAL(18,2),
    TOTAL_INTEREST_REPAY_AMOUNT DECIMAL(18,2),
    CUSTOMER_TYPE_CODE NVARCHAR(50),
    CUSTOMER_TYPE_CODE_DETAIL NVARCHAR(50),
    TRCTCD NVARCHAR(50),
    TRCTNM NVARCHAR(255),
    ADDR1 NVARCHAR(500),
    PROVINCE NVARCHAR(100),
    LCLPROVINNM NVARCHAR(100),
    DISTRICT NVARCHAR(100),
    LCLDISTNM NVARCHAR(100),
    COMMCD NVARCHAR(50),
    LCLWARDNM NVARCHAR(100),
    LAST_REPAY_DATE DATETIME,
    SECURED_PERCENT DECIMAL(10,4),
    NHOM_NO NVARCHAR(10),
    LAST_INT_CHARGE_DATE DATETIME,
    EXEMPTINT DECIMAL(18,2),
    EXEMPTINTTYPE NVARCHAR(50),
    EXEMPTINTAMT DECIMAL(18,2),
    GRPNO NVARCHAR(50),
    BUSCD NVARCHAR(50),
    BSNSSCLTPCD NVARCHAR(50),
    USRIDOP NVARCHAR(50),
    ACCRUAL_AMOUNT DECIMAL(18,2),
    ACCRUAL_AMOUNT_END_OF_MONTH DECIMAL(18,2),
    INTCMTH INT,
    INTRPYMTH INT,
    INTTRMMTH INT,
    YRDAYS INT,
    REMARK NVARCHAR(500),
    CHITIEU NVARCHAR(100),
    CTCV NVARCHAR(100),
    CREDIT_LINE_YPE NVARCHAR(50),
    INT_LUMPSUM_PARTIAL_TYPE NVARCHAR(50),
    INT_PARTIAL_PAYMENT_TYPE NVARCHAR(50),
    INT_PAYMENT_INTERVAL INT,
    AN_HAN_LAI NVARCHAR(50),
    PHUONG_THUC_GIAI_NGAN_1 NVARCHAR(50),
    TAI_KHOAN_GIAI_NGAN_1 NVARCHAR(50),
    SO_TIEN_GIAI_NGAN_1 DECIMAL(18,2),
    PHUONG_THUC_GIAI_NGAN_2 NVARCHAR(50),
    TAI_KHOAN_GIAI_NGAN_2 NVARCHAR(50),
    SO_TIEN_GIAI_NGAN_2 DECIMAL(18,2),
    CMT_HC NVARCHAR(50),
    NGAY_SINH DATETIME,
    MA_CB_AGRI NVARCHAR(50),
    MA_NGANH_KT NVARCHAR(50),
    TY_GIA DECIMAL(10,4),
    OFFICER_IPCAS NVARCHAR(50),

    -- System columns (ở cuối)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL DATETIME NOT NULL,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(255),

    -- Temporal columns (ở cuối cùng)
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LN01_History));
GO

-- ================================================================
-- BẢNG 6: LN03 (17 business columns + system/temporal columns)
-- ================================================================
CREATE TABLE LN03 (
    -- Business columns từ CSV (17 cột)
    MACHINHANH NVARCHAR(50),
    TENCHINHANH NVARCHAR(255),
    MAKH NVARCHAR(50),
    TENKH NVARCHAR(255),
    SOHOPDONG NVARCHAR(50),
    SOTIENXLRR DECIMAL(18,2),
    NGAYPHATSINHXL DATETIME,
    THUNOSAUXL DECIMAL(18,2),
    CONLAINGOAIBANG DECIMAL(18,2),
    DUNONOIBANG DECIMAL(18,2),
    NHOMNO NVARCHAR(10),
    MACBTD NVARCHAR(50),
    TENCBTD NVARCHAR(255),
    MAPGD NVARCHAR(50),
    TAIKHOANHACHTOAN NVARCHAR(50),
    REFNO NVARCHAR(50),
    LOAINGUONVON NVARCHAR(50),

    -- System columns (ở cuối)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL DATETIME NOT NULL,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(255),

    -- Temporal columns (ở cuối cùng)
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.LN03_History));
GO

-- ================================================================
-- BẢNG 7: RR01 (25 business columns + system/temporal columns)
-- ================================================================
CREATE TABLE RR01 (
    -- Business columns từ CSV (25 cột)
    CN_LOAI_I NVARCHAR(50),
    BRCD NVARCHAR(50),
    MA_KH NVARCHAR(50),
    TEN_KH NVARCHAR(255),
    SO_LDS NVARCHAR(50),
    CCY NVARCHAR(10),
    SO_LAV NVARCHAR(50),
    LOAI_KH NVARCHAR(50),
    NGAY_GIAI_NGAN DATETIME,
    NGAY_DEN_HAN DATETIME,
    VAMC_FLG NVARCHAR(10),
    NGAY_XLRR DATETIME,
    DUNO_GOC_BAN_DAU DECIMAL(18,2),
    DUNO_LAI_TICHLUY_BD DECIMAL(18,2),
    DOC_DAUKY_DA_THU_HT DECIMAL(18,2),
    DUNO_GOC_HIENTAI DECIMAL(18,2),
    DUNO_LAI_HIENTAI DECIMAL(18,2),
    DUNO_NGAN_HAN DECIMAL(18,2),
    DUNO_TRUNG_HAN DECIMAL(18,2),
    DUNO_DAI_HAN DECIMAL(18,2),
    THU_GOC DECIMAL(18,2),
    THU_LAI DECIMAL(18,2),
    BDS DECIMAL(18,2),
    DS DECIMAL(18,2),
    TSK DECIMAL(18,2),

    -- System columns (ở cuối)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL DATETIME NOT NULL,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(255),

    -- Temporal columns (ở cuối cùng)
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RR01_History));
GO

-- ================================================================
-- BẢNG 8: DPDA (13 business columns + system/temporal columns)
-- ================================================================
CREATE TABLE DPDA (
    -- Business columns từ CSV (13 cột)
    MA_CHI_NHANH NVARCHAR(50),
    MA_KHACH_HANG NVARCHAR(50),
    TEN_KHACH_HANG NVARCHAR(255),
    SO_TAI_KHOAN NVARCHAR(50),
    LOAI_THE NVARCHAR(50),
    SO_THE NVARCHAR(50),
    NGAY_NOP_DON DATETIME,
    NGAY_PHAT_HANH DATETIME,
    USER_PHAT_HANH NVARCHAR(50),
    TRANG_THAI NVARCHAR(50),
    PHAN_LOAI NVARCHAR(50),
    GIAO_THE NVARCHAR(50),
    LOAI_PHAT_HANH NVARCHAR(50),

    -- System columns (ở cuối)
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL DATETIME NOT NULL,
    CREATED_DATE DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    UPDATED_DATE DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    FILE_NAME NVARCHAR(255),

    -- Temporal columns (ở cuối cùng)
    PERIOD FOR SYSTEM_TIME (CREATED_DATE, UPDATED_DATE)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.DPDA_History));
GO

-- ================================================================
-- TẠO COLUMNSTORE INDEXES CHO 7 BẢNG (trừ GL01 - sẽ có partitioned columnstore)
-- ================================================================
PRINT 'Creating columnstore indexes...';

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_DP01_Columnstore ON DP01
(MA_CN, TAI_KHOAN_HACH_TOAN, MA_KH, TEN_KH, CURRENT_BALANCE, NGAY_DL);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_EI01_Columnstore ON EI01
(MA_CN, MA_KH, TEN_KH, LOAI_KH, NGAY_DL);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_GL41_Columnstore ON GL41
(MA_CN, LOAI_TIEN, MA_TK, TEN_TK, DN_DAUKY, DC_DAUKY, DN_CUOIKY, DC_CUOIKY, NGAY_DL);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_LN01_Columnstore ON LN01
(BRCD, CUSTSEQ, CUSTNM, TAI_KHOAN, CCY, DU_NO, INTEREST_RATE, NGAY_DL);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_LN03_Columnstore ON LN03
(MACHINHANH, TENCHINHANH, MAKH, TENKH, SOTIENXLRR, DUNONOIBANG, NGAY_DL);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_RR01_Columnstore ON RR01
(CN_LOAI_I, BRCD, MA_KH, TEN_KH, DUNO_GOC_HIENTAI, DUNO_LAI_HIENTAI, NGAY_DL);

CREATE NONCLUSTERED COLUMNSTORE INDEX IX_DPDA_Columnstore ON DPDA
(MA_CHI_NHANH, MA_KHACH_HANG, TEN_KHACH_HANG, SO_TAI_KHOAN, LOAI_THE, NGAY_DL);

-- ================================================================
-- SPECIAL: GL01 PARTITIONED COLUMNSTORE INDEX
-- ================================================================
PRINT 'Creating partitioned columnstore for GL01...';

-- GL01 được thiết kế như partitioned table với columnstore
-- (Azure SQL Edge có limitations, nhưng vẫn tạo columnstore thông thường)
CREATE NONCLUSTERED COLUMNSTORE INDEX IX_GL01_Columnstore ON GL01
(STS, NGAY_GD, TAI_KHOAN, TEN_TK, SO_TIEN_GD, LOAI_TIEN, MA_KH, TEN_KH, TR_TIME, NGAY_DL);

GO

-- ================================================================
-- VERIFICATION: Kiểm tra cấu trúc bảng đã tạo
-- ================================================================
PRINT '🎯 VERIFICATION: Kiểm tra cấu trúc bảng...';

SELECT
    t.name AS TableName,
    COUNT(c.column_id) AS TotalColumns,
    SUM(CASE WHEN c.name IN ('Id', 'NGAY_DL', 'CREATED_DATE', 'UPDATED_DATE', 'FILE_NAME') THEN 1 ELSE 0 END) AS SystemColumns,
    COUNT(c.column_id) - SUM(CASE WHEN c.name IN ('Id', 'NGAY_DL', 'CREATED_DATE', 'UPDATED_DATE', 'FILE_NAME') THEN 1 ELSE 0 END) AS BusinessColumns,
    CASE WHEN t.temporal_type = 2 THEN 'YES' ELSE 'NO' END AS TemporalTable
FROM sys.tables t
INNER JOIN sys.columns c ON t.object_id = c.object_id
WHERE t.name IN ('DP01', 'EI01', 'GL01', 'GL41', 'LN01', 'LN03', 'RR01', 'DPDA')
GROUP BY t.name, t.temporal_type
ORDER BY t.name;

PRINT '✅ Rebuild completed! All 8 tables với business columns ở đầu, system/temporal columns ở cuối';
