-- Recreate 8 data tables with EXACT CSV structure
-- This ensures 100% column matching between CSV files and database tables

-- Drop existing tables
IF OBJECT_ID('dbo.DP01', 'U') IS NOT NULL DROP TABLE DP01;
IF OBJECT_ID('dbo.EI01', 'U') IS NOT NULL DROP TABLE EI01;
IF OBJECT_ID('dbo.GL01', 'U') IS NOT NULL DROP TABLE GL01;
IF OBJECT_ID('dbo.GL41', 'U') IS NOT NULL DROP TABLE GL41;
IF OBJECT_ID('dbo.LN01', 'U') IS NOT NULL DROP TABLE LN01;
IF OBJECT_ID('dbo.LN03', 'U') IS NOT NULL DROP TABLE LN03;
IF OBJECT_ID('dbo.RR01', 'U') IS NOT NULL DROP TABLE RR01;
IF OBJECT_ID('dbo.DPDA', 'U') IS NOT NULL DROP TABLE DPDA;

-- Create DP01 with 63 business columns + 4 temporal columns
CREATE TABLE DP01 (
    -- Temporal columns first
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL NVARCHAR(20) NOT NULL, -- DD-MM-YYYY format

    -- 63 Business columns (exact CSV order)
    MA_CN NVARCHAR(200),
    TAI_KHOAN_HACH_TOAN NVARCHAR(200),
    MA_KH NVARCHAR(200),
    TEN_KH NVARCHAR(200),
    DP_TYPE_NAME NVARCHAR(200),
    CCY NVARCHAR(200),
    CURRENT_BALANCE NVARCHAR(200),
    RATE NVARCHAR(200),
    SO_TAI_KHOAN NVARCHAR(200),
    OPENING_DATE NVARCHAR(200),
    MATURITY_DATE NVARCHAR(200),
    ADDRESS NVARCHAR(200),
    NOTENO NVARCHAR(200),
    MONTH_TERM NVARCHAR(200),
    TERM_DP_NAME NVARCHAR(200),
    TIME_DP_NAME NVARCHAR(200),
    MA_PGD NVARCHAR(200),
    TEN_PGD NVARCHAR(200),
    DP_TYPE_CODE NVARCHAR(200),
    RENEW_DATE NVARCHAR(200),
    CUST_TYPE NVARCHAR(200),
    CUST_TYPE_NAME NVARCHAR(200),
    CUST_TYPE_DETAIL NVARCHAR(200),
    CUST_DETAIL_NAME NVARCHAR(200),
    PREVIOUS_DP_CAP_DATE NVARCHAR(200),
    NEXT_DP_CAP_DATE NVARCHAR(200),
    ID_NUMBER NVARCHAR(200),
    ISSUED_BY NVARCHAR(200),
    ISSUE_DATE NVARCHAR(200),
    SEX_TYPE NVARCHAR(200),
    BIRTH_DATE NVARCHAR(200),
    TELEPHONE NVARCHAR(200),
    ACRUAL_AMOUNT NVARCHAR(200),
    ACRUAL_AMOUNT_END NVARCHAR(200),
    ACCOUNT_STATUS NVARCHAR(200),
    DRAMT NVARCHAR(200),
    CRAMT NVARCHAR(200),
    EMPLOYEE_NUMBER NVARCHAR(200),
    EMPLOYEE_NAME NVARCHAR(200),
    SPECIAL_RATE NVARCHAR(200),
    AUTO_RENEWAL NVARCHAR(200),
    CLOSE_DATE NVARCHAR(200),
    LOCAL_PROVIN_NAME NVARCHAR(200),
    LOCAL_DISTRICT_NAME NVARCHAR(200),
    LOCAL_WARD_NAME NVARCHAR(200),
    TERM_DP_TYPE NVARCHAR(200),
    TIME_DP_TYPE NVARCHAR(200),
    STATES_CODE NVARCHAR(200),
    ZIP_CODE NVARCHAR(200),
    COUNTRY_CODE NVARCHAR(200),
    TAX_CODE_LOCATION NVARCHAR(200),
    MA_CAN_BO_PT NVARCHAR(200),
    TEN_CAN_BO_PT NVARCHAR(200),
    PHONG_CAN_BO_PT NVARCHAR(200),
    NGUOI_NUOC_NGOAI NVARCHAR(200),
    QUOC_TICH NVARCHAR(200),
    MA_CAN_BO_AGRIBANK NVARCHAR(200),
    NGUOI_GIOI_THIEU NVARCHAR(200),
    TEN_NGUOI_GIOI_THIEU NVARCHAR(200),
    CONTRACT_COUTS_DAY NVARCHAR(200),
    SO_KY_AD_LSDB NVARCHAR(200),
    UNTBUSCD NVARCHAR(200),
    TYGIA NVARCHAR(200),

    -- Temporal tracking columns
    CREATED_DATE DATETIME2 DEFAULT GETDATE(),
    UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
    FILE_NAME NVARCHAR(500)
);

-- Create EI01 with 24 business columns + 4 temporal columns
CREATE TABLE EI01 (
    -- Temporal columns first
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL NVARCHAR(20) NOT NULL,

    -- 24 Business columns (exact CSV order)
    MA_CN NVARCHAR(200),
    MA_KH NVARCHAR(200),
    TEN_KH NVARCHAR(200),
    LOAI_KH NVARCHAR(200),
    SDT_EMB NVARCHAR(200),
    TRANG_THAI_EMB NVARCHAR(200),
    NGAY_DK_EMB NVARCHAR(200),
    SDT_OTT NVARCHAR(200),
    TRANG_THAI_OTT NVARCHAR(200),
    NGAY_DK_OTT NVARCHAR(200),
    SDT_SMS NVARCHAR(200),
    TRANG_THAI_SMS NVARCHAR(200),
    NGAY_DK_SMS NVARCHAR(200),
    SDT_SAV NVARCHAR(200),
    TRANG_THAI_SAV NVARCHAR(200),
    NGAY_DK_SAV NVARCHAR(200),
    SDT_LN NVARCHAR(200),
    TRANG_THAI_LN NVARCHAR(200),
    NGAY_DK_LN NVARCHAR(200),
    USER_EMB NVARCHAR(200),
    USER_OTT NVARCHAR(200),
    USER_SMS NVARCHAR(200),
    USER_SAV NVARCHAR(200),
    USER_LN NVARCHAR(200),

    -- Temporal tracking columns
    CREATED_DATE DATETIME2 DEFAULT GETDATE(),
    UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
    FILE_NAME NVARCHAR(500)
);

-- Create GL01 with 27 business columns + 4 temporal columns
CREATE TABLE GL01 (
    -- Temporal columns first
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL NVARCHAR(20) NOT NULL,

    -- 27 Business columns (exact CSV order)
    STS NVARCHAR(200),
    NGAY_GD NVARCHAR(200),
    NGUOI_TAO NVARCHAR(200),
    DYSEQ NVARCHAR(200),
    TR_TYPE NVARCHAR(200),
    DT_SEQ NVARCHAR(200),
    TAI_KHOAN NVARCHAR(200),
    TEN_TK NVARCHAR(200),
    SO_TIEN_GD NVARCHAR(200),
    POST_BR NVARCHAR(200),
    LOAI_TIEN NVARCHAR(200),
    DR_CR NVARCHAR(200),
    MA_KH NVARCHAR(200),
    TEN_KH NVARCHAR(200),
    CCA_USRID NVARCHAR(200),
    TR_EX_RT NVARCHAR(200),
    REMARK NVARCHAR(200),
    BUS_CODE NVARCHAR(200),
    UNIT_BUS_CODE NVARCHAR(200),
    TR_CODE NVARCHAR(200),
    TR_NAME NVARCHAR(200),
    REFERENCE NVARCHAR(200),
    VALUE_DATE NVARCHAR(200),
    DEPT_CODE NVARCHAR(200),
    TR_TIME NVARCHAR(200),
    COMFIRM NVARCHAR(200),
    TRDT_TIME NVARCHAR(200),

    -- Temporal tracking columns
    CREATED_DATE DATETIME2 DEFAULT GETDATE(),
    UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
    FILE_NAME NVARCHAR(500)
);

-- Create GL41 with 13 business columns + 4 temporal columns
CREATE TABLE GL41 (
    -- Temporal columns first
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL NVARCHAR(20) NOT NULL,

    -- 13 Business columns (exact CSV order)
    MA_CN NVARCHAR(200),
    LOAI_TIEN NVARCHAR(200),
    MA_TK NVARCHAR(200),
    TEN_TK NVARCHAR(200),
    LOAI_BT NVARCHAR(200),
    DN_DAUKY NVARCHAR(200),
    DC_DAUKY NVARCHAR(200),
    SBT_NO NVARCHAR(200),
    ST_GHINO NVARCHAR(200),
    SBT_CO NVARCHAR(200),
    ST_GHICO NVARCHAR(200),
    DN_CUOIKY NVARCHAR(200),
    DC_CUOIKY NVARCHAR(200),

    -- Temporal tracking columns
    CREATED_DATE DATETIME2 DEFAULT GETDATE(),
    UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
    FILE_NAME NVARCHAR(500)
);

-- Create LN01 with 79 business columns + 4 temporal columns
CREATE TABLE LN01 (
    -- Temporal columns first
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL NVARCHAR(20) NOT NULL,

    -- 79 Business columns (exact CSV order)
    BRCD NVARCHAR(200),
    CUSTSEQ NVARCHAR(200),
    CUSTNM NVARCHAR(200),
    TAI_KHOAN NVARCHAR(200),
    CCY NVARCHAR(200),
    DU_NO NVARCHAR(200),
    DSBSSEQ NVARCHAR(200),
    TRANSACTION_DATE NVARCHAR(200),
    DSBSDT NVARCHAR(200),
    DISBUR_CCY NVARCHAR(200),
    DISBURSEMENT_AMOUNT NVARCHAR(200),
    DSBSMATDT NVARCHAR(200),
    BSRTCD NVARCHAR(200),
    INTEREST_RATE NVARCHAR(200),
    APPRSEQ NVARCHAR(200),
    APPRDT NVARCHAR(200),
    APPR_CCY NVARCHAR(200),
    APPRAMT NVARCHAR(200),
    APPRMATDT NVARCHAR(200),
    LOAN_TYPE NVARCHAR(200),
    FUND_RESOURCE_CODE NVARCHAR(200),
    FUND_PURPOSE_CODE NVARCHAR(200),
    REPAYMENT_AMOUNT NVARCHAR(200),
    NEXT_REPAY_DATE NVARCHAR(200),
    NEXT_REPAY_AMOUNT NVARCHAR(200),
    NEXT_INT_REPAY_DATE NVARCHAR(200),
    OFFICER_ID NVARCHAR(200),
    OFFICER_NAME NVARCHAR(200),
    INTEREST_AMOUNT NVARCHAR(200),
    PASTDUE_INTEREST_AMOUNT NVARCHAR(200),
    TOTAL_INTEREST_REPAY_AMOUNT NVARCHAR(200),
    CUSTOMER_TYPE_CODE NVARCHAR(200),
    CUSTOMER_TYPE_CODE_DETAIL NVARCHAR(200),
    TRCTCD NVARCHAR(200),
    TRCTNM NVARCHAR(200),
    ADDR1 NVARCHAR(200),
    PROVINCE NVARCHAR(200),
    LCLPROVINNM NVARCHAR(200),
    DISTRICT NVARCHAR(200),
    LCLDISTNM NVARCHAR(200),
    COMMCD NVARCHAR(200),
    LCLWARDNM NVARCHAR(200),
    LAST_REPAY_DATE NVARCHAR(200),
    SECURED_PERCENT NVARCHAR(200),
    NHOM_NO NVARCHAR(200),
    LAST_INT_CHARGE_DATE NVARCHAR(200),
    EXEMPTINT NVARCHAR(200),
    EXEMPTINTTYPE NVARCHAR(200),
    EXEMPTINTAMT NVARCHAR(200),
    GRPNO NVARCHAR(200),
    BUSCD NVARCHAR(200),
    BSNSSCLTPCD NVARCHAR(200),
    USRIDOP NVARCHAR(200),
    ACCRUAL_AMOUNT NVARCHAR(200),
    ACCRUAL_AMOUNT_END_OF_MONTH NVARCHAR(200),
    INTCMTH NVARCHAR(200),
    INTRPYMTH NVARCHAR(200),
    INTTRMMTH NVARCHAR(200),
    YRDAYS NVARCHAR(200),
    REMARK NVARCHAR(200),
    CHITIEU NVARCHAR(200),
    CTCV NVARCHAR(200),
    CREDIT_LINE_YPE NVARCHAR(200),
    INT_LUMPSUM_PARTIAL_TYPE NVARCHAR(200),
    INT_PARTIAL_PAYMENT_TYPE NVARCHAR(200),
    INT_PAYMENT_INTERVAL NVARCHAR(200),
    AN_HAN_LAI NVARCHAR(200),
    PHUONG_THUC_GIAI_NGAN_1 NVARCHAR(200),
    TAI_KHOAN_GIAI_NGAN_1 NVARCHAR(200),
    SO_TIEN_GIAI_NGAN_1 NVARCHAR(200),
    PHUONG_THUC_GIAI_NGAN_2 NVARCHAR(200),
    TAI_KHOAN_GIAI_NGAN_2 NVARCHAR(200),
    SO_TIEN_GIAI_NGAN_2 NVARCHAR(200),
    CMT_HC NVARCHAR(200),
    NGAY_SINH NVARCHAR(200),
    MA_CB_AGRI NVARCHAR(200),
    MA_NGANH_KT NVARCHAR(200),
    TY_GIA NVARCHAR(200),
    OFFICER_IPCAS NVARCHAR(200),

    -- Temporal tracking columns
    CREATED_DATE DATETIME2 DEFAULT GETDATE(),
    UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
    FILE_NAME NVARCHAR(500)
);

-- Create LN03 with 17 business columns + 4 temporal columns
CREATE TABLE LN03 (
    -- Temporal columns first
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL NVARCHAR(20) NOT NULL,

    -- 17 Business columns (exact CSV order)
    MACHINHANH NVARCHAR(200),
    TENCHINHANH NVARCHAR(200),
    MAKH NVARCHAR(200),
    TENKH NVARCHAR(200),
    SOHOPDONG NVARCHAR(200),
    SOTIENXLRR NVARCHAR(200),
    NGAYPHATSINHXL NVARCHAR(200),
    THUNOSAUXL NVARCHAR(200),
    CONLAINGOAIBANG NVARCHAR(200),
    DUNONOIBANG NVARCHAR(200),
    NHOMNO NVARCHAR(200),
    MACBTD NVARCHAR(200),
    TENCBTD NVARCHAR(200),
    MAPGD NVARCHAR(200),
    TAIKHOANHACHTOAN NVARCHAR(200),
    REFNO NVARCHAR(200),
    LOAINGUONVON NVARCHAR(200),

    -- Temporal tracking columns
    CREATED_DATE DATETIME2 DEFAULT GETDATE(),
    UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
    FILE_NAME NVARCHAR(500)
);

-- Create RR01 with 25 business columns + 4 temporal columns
CREATE TABLE RR01 (
    -- Temporal columns first
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL NVARCHAR(20) NOT NULL,

    -- 25 Business columns (exact CSV order)
    CN_LOAI_I NVARCHAR(200),
    BRCD NVARCHAR(200),
    MA_KH NVARCHAR(200),
    TEN_KH NVARCHAR(200),
    SO_LDS NVARCHAR(200),
    CCY NVARCHAR(200),
    SO_LAV NVARCHAR(200),
    LOAI_KH NVARCHAR(200),
    NGAY_GIAI_NGAN NVARCHAR(200),
    NGAY_DEN_HAN NVARCHAR(200),
    VAMC_FLG NVARCHAR(200),
    NGAY_XLRR NVARCHAR(200),
    DUNO_GOC_BAN_DAU NVARCHAR(200),
    DUNO_LAI_TICHLUY_BD NVARCHAR(200),
    DOC_DAUKY_DA_THU_HT NVARCHAR(200),
    DUNO_GOC_HIENTAI NVARCHAR(200),
    DUNO_LAI_HIENTAI NVARCHAR(200),
    DUNO_NGAN_HAN NVARCHAR(200),
    DUNO_TRUNG_HAN NVARCHAR(200),
    DUNO_DAI_HAN NVARCHAR(200),
    THU_GOC NVARCHAR(200),
    THU_LAI NVARCHAR(200),
    BDS NVARCHAR(200),
    DS NVARCHAR(200),
    TSK NVARCHAR(200),

    -- Temporal tracking columns
    CREATED_DATE DATETIME2 DEFAULT GETDATE(),
    UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
    FILE_NAME NVARCHAR(500)
);

-- Create DPDA with 13 business columns + 4 temporal columns
CREATE TABLE DPDA (
    -- Temporal columns first
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    NGAY_DL NVARCHAR(20) NOT NULL,

    -- 13 Business columns (exact CSV order)
    MA_CHI_NHANH NVARCHAR(200),
    MA_KHACH_HANG NVARCHAR(200),
    TEN_KHACH_HANG NVARCHAR(200),
    SO_TAI_KHOAN NVARCHAR(200),
    LOAI_THE NVARCHAR(200),
    SO_THE NVARCHAR(200),
    NGAY_NOP_DON NVARCHAR(200),
    NGAY_PHAT_HANH NVARCHAR(200),
    USER_PHAT_HANH NVARCHAR(200),
    TRANG_THAI NVARCHAR(200),
    PHAN_LOAI NVARCHAR(200),
    GIAO_THE NVARCHAR(200),
    LOAI_PHAT_HANH NVARCHAR(200),

    -- Temporal tracking columns
    CREATED_DATE DATETIME2 DEFAULT GETDATE(),
    UPDATED_DATE DATETIME2 DEFAULT GETDATE(),
    FILE_NAME NVARCHAR(500)
);

SELECT 'All 8 tables recreated with exact CSV structure' as Result;
