-- Update all business columns in 8 data tables to NVARCHAR(200)
-- This ensures CSV import can handle longer text data

-- DP01 Table
ALTER TABLE DP01 ALTER COLUMN MA_CN NVARCHAR(200);
ALTER TABLE DP01 ALTER COLUMN MA_KH NVARCHAR(200);
ALTER TABLE DP01 ALTER COLUMN TEN_KH NVARCHAR(200);
ALTER TABLE DP01 ALTER COLUMN SO_TK_KH NVARCHAR(200);
ALTER TABLE DP01 ALTER COLUMN MA_SP NVARCHAR(200);
ALTER TABLE DP01 ALTER COLUMN TEN_SP NVARCHAR(200);
ALTER TABLE DP01 ALTER COLUMN LOAI_TIEN NVARCHAR(200);
ALTER TABLE DP01 ALTER COLUMN DU_NO_HIEN_VAL NVARCHAR(200);
ALTER TABLE DP01 ALTER COLUMN DU_NO_QUY_DOI NVARCHAR(200);
ALTER TABLE DP01 ALTER COLUMN LOAI_KH NVARCHAR(200);
ALTER TABLE DP01 ALTER COLUMN PGD NVARCHAR(200);

-- GL01 Table
ALTER TABLE GL01 ALTER COLUMN MA_CN NVARCHAR(200);
ALTER TABLE GL01 ALTER COLUMN LOAI_TIEN NVARCHAR(200);
ALTER TABLE GL01 ALTER COLUMN MA_TK NVARCHAR(200);
ALTER TABLE GL01 ALTER COLUMN TEN_TK NVARCHAR(200);
ALTER TABLE GL01 ALTER COLUMN SO_DU_DAU_KY NVARCHAR(200);
ALTER TABLE GL01 ALTER COLUMN SO_PHAT_SINH_NO NVARCHAR(200);
ALTER TABLE GL01 ALTER COLUMN SO_PHAT_SINH_CO NVARCHAR(200);
ALTER TABLE GL01 ALTER COLUMN LK_SO_PHAT_SINH_NO NVARCHAR(200);
ALTER TABLE GL01 ALTER COLUMN LK_SO_PHAT_SINH_CO NVARCHAR(200);
ALTER TABLE GL01 ALTER COLUMN LK_SO_DU_NO NVARCHAR(200);
ALTER TABLE GL01 ALTER COLUMN LK_SO_DU_CO NVARCHAR(200);
ALTER TABLE GL01 ALTER COLUMN ST_GHINO NVARCHAR(200);
ALTER TABLE GL01 ALTER COLUMN ST_GHICO NVARCHAR(200);
-- (continued for other GL01 columns...)

-- EI01 Table
ALTER TABLE EI01 ALTER COLUMN MA_CN NVARCHAR(200);
ALTER TABLE EI01 ALTER COLUMN MA_NV NVARCHAR(200);
ALTER TABLE EI01 ALTER COLUMN TEN_NV NVARCHAR(200);
ALTER TABLE EI01 ALTER COLUMN DON_VI NVARCHAR(200);
ALTER TABLE EI01 ALTER COLUMN CHUC_VU NVARCHAR(200);
-- (will add all EI01 columns...)

-- DPDA Table
ALTER TABLE DPDA ALTER COLUMN MA_CN NVARCHAR(200);
ALTER TABLE DPDA ALTER COLUMN MA_KH NVARCHAR(200);
ALTER TABLE DPDA ALTER COLUMN TEN_KH NVARCHAR(200);
-- (will add all DPDA columns...)

-- RR01 Table
ALTER TABLE RR01 ALTER COLUMN MA_CN NVARCHAR(200);
ALTER TABLE RR01 ALTER COLUMN MA_KH NVARCHAR(200);
ALTER TABLE RR01 ALTER COLUMN TEN_KH NVARCHAR(200);
-- (will add all RR01 columns...)

-- LN01 Table
ALTER TABLE LN01 ALTER COLUMN MA_CN NVARCHAR(200);
ALTER TABLE LN01 ALTER COLUMN MA_KH NVARCHAR(200);
ALTER TABLE LN01 ALTER COLUMN TEN_KH NVARCHAR(200);
-- (will add all LN01 columns...)

-- LN03 Table
ALTER TABLE LN03 ALTER COLUMN MA_CN NVARCHAR(200);
ALTER TABLE LN03 ALTER COLUMN MA_KH NVARCHAR(200);
ALTER TABLE LN03 ALTER COLUMN TEN_KH NVARCHAR(200);
-- (will add all LN03 columns...)

SELECT 'All 8 tables updated to NVARCHAR(200) successfully!' as Result;
