#!/bin/bash
# Script để tái cấu trúc thứ tự cột cho tất cả 8 bảng dữ liệu
# Business columns FIRST, System columns MIDDLE, Temporal columns LAST

echo "🔄 TỔNG HỢP RESTRUCTURE CỘT CHO 8 BẢNG DỮ LIỆU"
echo "================================================"
echo "📅 $(date)"
echo ""

# Kết nối database
SQLCMD="sqlcmd -S localhost,1433 -U SA -P 'Dientoan@303' -d TinhKhoanDB -C"

echo "🔍 KIỂM TRA BUSINESS COLUMNS THEO CSV GỐC:"
echo "=========================================="

echo "📊 GL01 - Business columns từ CSV:"
echo "STS,NGAY_GD,NGUOI_TAO,DYSEQ,TR_TYPE,DT_SEQ,TAI_KHOAN,TEN_TK,SO_TIEN_GD,POST_BR,LOAI_TIEN,DR_CR,MA_KH,TEN_KH,CCA_USRID,TR_EX_RT,REMARK,BUS_CODE,UNIT_BUS_CODE,TR_CODE,TR_NAME,REFERENCE,VALUE_DATE,DEPT_CODE,TR_TIME,COMFIRM,TRDT_TIME"
echo ""

echo "📊 DP01 - Business columns từ CSV:"
echo "MA_CN,TAI_KHOAN_HACH_TOAN,MA_KH,TEN_KH,DP_TYPE_NAME,CCY,CURRENT_BALANCE,RATE,SO_TAI_KHOAN,OPENING_DATE,MATURITY_DATE,ADDRESS,NOTENO,MONTH_TERM,TERM_DP_NAME,TIME_DP_NAME,MA_PGD,TEN_PGD,DP_TYPE_CODE,RENEW_DATE,CUST_TYPE,CUST_TYPE_NAME,CUST_TYPE_DETAIL,CUST_DETAIL_NAME,PREVIOUS_DP_CAP_DATE,NEXT_DP_CAP_DATE,ID_NUMBER,ISSUED_BY,ISSUE_DATE,SEX_TYPE,BIRTH_DATE,TELEPHONE,ACRUAL_AMOUNT,ACRUAL_AMOUNT_END,ACCOUNT_STATUS,DRAMT,CRAMT,EMPLOYEE_NUMBER,EMPLOYEE_NAME,SPECIAL_RATE,AUTO_RENEWAL,CLOSE_DATE,LOCAL_PROVIN_NAME,LOCAL_DISTRICT_NAME,LOCAL_WARD_NAME,TERM_DP_TYPE,TIME_DP_TYPE,STATES_CODE,ZIP_CODE,COUNTRY_CODE,TAX_CODE_LOCATION,MA_CAN_BO_PT,TEN_CAN_BO_PT,PHONG_CAN_BO_PT,NGUOI_NUOC_NGOAI,QUOC_TICH,MA_CAN_BO_AGRIBANK,NGUOI_GIOI_THIEU,TEN_NGUOI_GIOI_THIEU,CONTRACT_COUTS_DAY,SO_KY_AD_LSDB,UNTBUSCD,TYGIA"
echo ""

echo "📊 LN01 - Business columns từ CSV:"
echo "BRCD,CUSTSEQ,CUSTNM,TAI_KHOAN,CCY,DU_NO,DSBSSEQ,TRANSACTION_DATE,DSBSDT,DISBUR_CCY,DISBURSEMENT_AMOUNT,DSBSMATDT,BSRTCD,INTEREST_RATE,APPRSEQ,APPRDT,APPR_CCY,APPRAMT,APPRMATDT,LOAN_TYPE,FUND_RESOURCE_CODE,FUND_PURPOSE_CODE,REPAYMENT_AMOUNT,NEXT_REPAY_DATE,NEXT_REPAY_AMOUNT,NEXT_INT_REPAY_DATE,OFFICER_ID,OFFICER_NAME,INTEREST_AMOUNT,PASTDUE_INTEREST_AMOUNT,TOTAL_INTEREST_REPAY_AMOUNT,CUSTOMER_TYPE_CODE,CUSTOMER_TYPE_CODE_DETAIL,TRCTCD,TRCTNM,ADDR1,PROVINCE,LCLPROVINNM,DISTRICT,LCLDISTNM,COMMCD,LCLWARDNM,LAST_REPAY_DATE,SECURED_PERCENT,NHOM_NO,LAST_INT_CHARGE_DATE,EXEMPTINT,EXEMPTINTTYPE,EXEMPTINTAMT,GRPNO,BUSCD,BSNSSCLTPCD,USRIDOP,ACCRUAL_AMOUNT,ACCRUAL_AMOUNT_END_OF_MONTH,INTCMTH,INTRPYMTH,INTTRMMTH,YRDAYS,REMARK,CHITIEU,CTCV,CREDIT_LINE_YPE,INT_LUMPSUM_PARTIAL_TYPE,INT_PARTIAL_PAYMENT_TYPE,INT_PAYMENT_INTERVAL,AN_HAN_LAI,PHUONG_THUC_GIAI_NGAN_1,TAI_KHOAN_GIAI_NGAN_1,SO_TIEN_GIAI_NGAN_1,PHUONG_THUC_GIAI_NGAN_2,TAI_KHOAN_GIAI_NGAN_2,SO_TIEN_GIAI_NGAN_2,CMT_HC,NGAY_SINH,MA_CB_AGRI,MA_NGANH_KT,TY_GIA,OFFICER_IPCAS"
echo ""

echo "📊 LN03 - Business columns từ CSV:"
echo "MACHINHANH,TENCHINHANH,MAKH,TENKH,SOHOPDONG,SOTIENXLRR,NGAYPHATSINHXL,THUNOSAUXL,CONLAINGOAIBANG,DUNONOIBANG,NHOMNO,MACBTD,TENCBTD,MAPGD,TAIKHOANHACHTOAN,REFNO,LOAINGUONVON"
echo ""

echo "📊 GL41 - Business columns từ CSV:"
echo "MA_CN,LOAI_TIEN,MA_TK,TEN_TK,LOAI_BT,DN_DAUKY,DC_DAUKY,SBT_NO,ST_GHINO,SBT_CO,ST_GHICO,DN_CUOIKY,DC_CUOIKY"
echo ""

echo "📊 DPDA - Business columns từ CSV:"
echo "MA_CHI_NHANH,MA_KHACH_HANG,TEN_KHACH_HANG,SO_TAI_KHOAN,LOAI_THE,SO_THE,NGAY_NOP_DON,NGAY_PHAT_HANH,USER_PHAT_HANH,TRANG_THAI,PHAN_LOAI,GIAO_THE,LOAI_PHAT_HANH"
echo ""

echo "📊 EI01 - Business columns từ CSV:"
echo "MA_CN,MA_KH,TEN_KH,LOAI_KH,SDT_EMB,TRANG_THAI_EMB,NGAY_DK_EMB,SDT_OTT,TRANG_THAI_OTT,NGAY_DK_OTT,SDT_SMS,TRANG_THAI_SMS,NGAY_DK_SMS,SDT_SAV,TRANG_THAI_SAV,NGAY_DK_SAV,SDT_LN,TRANG_THAI_LN,NGAY_DK_LN,USER_EMB,USER_OTT,USER_SMS,USER_SAV,USER_LN"
echo ""

echo "📊 RR01 - Business columns từ CSV:"
echo "CN_LOAI_I,BRCD,MA_KH,TEN_KH,SO_LDS,CCY,SO_LAV,LOAI_KH,NGAY_GIAI_NGAN,NGAY_DEN_HAN,VAMC_FLG,NGAY_XLRR,DUNO_GOC_BAN_DAU,DUNO_LAI_TICHLUY_BD,DOC_DAUKY_DA_THU_HT,DUNO_GOC_HIENTAI,DUNO_LAI_HIENTAI,DUNO_NGAN_HAN,DUNO_TRUNG_HAN,DUNO_DAI_HAN,THU_GOC,THU_LAI,BDS,DS,TSK"
echo ""

echo "⚠️  CẢNH BÁO: Tái cấu trúc này sẽ recreate tables."
echo "📋 System columns (tất cả bảng): Id, NGAY_DL, CreatedAt, UpdatedAt, IsDeleted"
echo "⏰ Temporal columns (7 bảng): SysStartTime, SysEndTime (trừ GL01)"

echo ""
echo "✅ Script hoàn thành. Kiểm tra xong, chạy migration nếu cần."
